/* Unidad 0 — Repaso de integrales
   Los ejemplos salen de la clase del 30/07 (Revisión de integrales). */
(window.__UNIDADES = window.__UNIDADES || []).push({
  id: 'u0',
  n: 0,
  titulo: 'Repaso: integrales',
  glifo: '\u222b',
  resumen: 'Sin integrar no hay ecuaciones diferenciales. Sustitución, partes y fracciones simples.',
  lecciones: [

    /* ------------------------------------------------------------------ */
    {
      id: 'u0l1',
      titulo: 'La primitiva y la tabla',
      objetivo: 'Entender qué se busca al integrar y tener la tabla básica a mano.',
      teoria: [
        { p: 'Integrar es **derivar al revés**. Si encontrás una función $F$ tal que $F\'(x)=f(x)$, entonces $F$ es una **primitiva** de $f$.' },
        { def: ['Integral indefinida', 'Si $F\'(x)=f(x)$, escribimos $$\\int f(x)\\,dx = F(x) + C$$'] },
        { p: 'El $+C$ no es un adorno: **todas** las funciones que difieren en una constante tienen la misma derivada. Si $F(x)=x^2$ y $G(x)=x^2+7$, las dos derivan en $2x$. Así que la respuesta no es una función, es una familia infinita de funciones.' },
        { h: 'La tabla que hay que saber de memoria' },
        { tabla: [['$f(x)$', '$\\int f(x)\\,dx$'], [
          ['$x^n$ (con $n\\neq-1$)', '$\\dfrac{x^{n+1}}{n+1}+C$'],
          ['$\\dfrac{1}{x}$', '$\\ln|x|+C$'],
          ['$e^{x}$', '$e^{x}+C$'],
          ['$e^{kx}$', '$\\dfrac{1}{k}e^{kx}+C$'],
          ['$\\sen x$', '$-\\cos x+C$'],
          ['$\\cos x$', '$\\sen x+C$'],
          ['$\\dfrac{1}{a^{2}+x^{2}}$', '$\\dfrac{1}{a}\\arctan\\dfrac{x}{a}+C$'],
        ]] },
        { truco: 'La fila de $\\dfrac{1}{a^{2}+x^{2}}$ parece de relleno pero aparece **siempre** en el caso 3 de fracciones simples. Marcala.' },
        { h: 'Linealidad' },
        { p: 'La integral respeta sumas y constantes:' },
        { mat: '\\int \\big[k\\,f(x) \\pm g(x)\\big]\\,dx = k\\int f(x)\\,dx \\pm \\int g(x)\\,dx' },
        { ojo: 'La integral **no** respeta productos ni cocientes. $\\int f\\cdot g \\neq \\int f \\cdot \\int g$. Para productos existen sustitución y partes; para cocientes, fracciones simples.' },
        { ej: ['Resolver $\\int (3x^{2}-4\\cos x)\\,dx$', [
          'Separo por linealidad: $3\\int x^{2}dx - 4\\int \\cos x\\,dx$',
          'Voy a la tabla: $3\\cdot\\dfrac{x^{3}}{3} - 4\\,\\sen x$',
          'Simplifico y agrego la constante: $x^{3}-4\\,\\sen x + C$',
        ]] },
        { truco: 'Toda integral se verifica **derivando el resultado**. Si no te da el integrando original, está mal. Es gratis y te salva en el parcial.' },
      ],
      formulas: [
        ['Potencia', '\\int x^{n}dx = \\frac{x^{n+1}}{n+1}+C \\quad (n \\neq -1)'],
        ['Caso especial $n=-1$', '\\int \\frac{1}{x}dx = \\ln|x|+C'],
        ['Exponencial', '\\int e^{kx}dx = \\frac{1}{k}e^{kx}+C'],
        ['Arcotangente', '\\int \\frac{1}{a^{2}+x^{2}}dx = \\frac{1}{a}\\arctan\\frac{x}{a}+C'],
      ],
      ejercicios: [
        { t: 'vf', p: 'Si $F\'(x)=f(x)$, entonces $F$ es una primitiva de $f$.', r: true,
          x: 'Esa es justo la definición: la primitiva es la función que al derivarse te devuelve el integrando.' },
        { t: 'mc', p: '¿Por qué toda integral indefinida termina con $+C$?', fijo: true,
          o: ['Porque infinitas funciones que difieren en una constante tienen la misma derivada', 'Porque hay que sumarle algo al resultado', 'Porque la integral siempre da un número más una función', 'Porque $C$ es la constante de la función original'],
          r: 0, x: '$x^{2}$, $x^{2}+7$ y $x^{2}-100$ derivan todas en $2x$. Al integrar $2x$ no podés saber cuál era: la respuesta es la familia entera.' },
        { t: 'mc', p: 'Resolvé $\\int x^{5}\\,dx$', o: ['$\\dfrac{x^{6}}{6}+C$', '$5x^{4}+C$', '$\\dfrac{x^{6}}{5}+C$', '$x^{6}+C$'], r: 0,
          x: 'Regla de la potencia: subís uno el exponente y dividís por el nuevo exponente. $\\dfrac{x^{5+1}}{5+1}=\\dfrac{x^{6}}{6}$.' },
        { t: 'in', p: 'Sabemos que $\\int e^{5x}dx = k\\,e^{5x}+C$. ¿Cuánto vale $k$?', r: ['1/5', '0.2'], ph: 'Escribí 1/5 o 0.2',
          x: '$\\int e^{kx}dx=\\frac{1}{k}e^{kx}+C$. Acá $k=5$, así que el factor de afuera es $\\frac{1}{5}$. Verificá derivando: $\\frac{1}{5}\\cdot 5e^{5x}=e^{5x}$.', teclas: ['/', '-'] },
        { t: 'mc', p: 'Resolvé $\\int \\dfrac{1}{x}\\,dx$', o: ['$\\ln|x|+C$', '$\\dfrac{x^{0}}{0}+C$', '$-\\dfrac{1}{x^{2}}+C$', '$\\dfrac{1}{2}x^{2}+C$'], r: 0,
          x: 'La regla de la potencia se rompe en $n=-1$ (te daría dividir por cero). Por eso $\\frac{1}{x}$ tiene su propia fila en la tabla, y el módulo importa: el logaritmo no existe para negativos.' },
        { t: 'par', p: 'Emparejá cada función con su primitiva',
          o: [['$\\cos x$', '$\\sen x + C$'], ['$\\sen x$', '$-\\cos x + C$'], ['$e^{x}$', '$e^{x}+C$'], ['$\\dfrac{1}{x}$', '$\\ln|x|+C$']],
          x: 'Ojo con el signo: la primitiva de $\\sen$ lleva menos, la de $\\cos$ no. Es la trampa más barata de un parcial.' },
        { t: 'mc', p: 'Resolvé $\\int (3x^{2}-4\\cos x)\\,dx$', o: ['$x^{3}-4\\,\\sen x+C$', '$x^{3}+4\\,\\sen x+C$', '$6x-4\\,\\sen x+C$', '$\\dfrac{3x^{3}}{3}-4\\cos x+C$'], r: 0,
          x: 'Por linealidad: $3\\cdot\\frac{x^{3}}{3}=x^{3}$ y $-4\\int\\cos x\\,dx=-4\\,\\sen x$.' },
        { t: 'in', p: 'En $\\int \\dfrac{1}{x^{2}+9}dx = \\dfrac{1}{a}\\arctan\\dfrac{x}{a}+C$, ¿cuánto vale $a$?', r: ['3'], ph: 'Un número',
          x: 'La fórmula usa $a^{2}+x^{2}$. Como $9=3^{2}$, resulta $a=3$: $\\frac{1}{3}\\arctan\\frac{x}{3}+C$.' },
        { t: 'mc', p: '¿Cuál es la forma más rápida de comprobar que una integral te dio bien?', fijo: true,
          o: ['Derivar el resultado y ver si da el integrando', 'Volver a integrar el resultado', 'Reemplazar $x$ por $1$', 'Comparar con la tabla'], r: 0,
          x: 'Integrar y derivar son operaciones inversas. Si derivás tu respuesta y no recuperás el integrando, hay un error.' },
        { t: 'in', p: 'En $\\int x^{-3}dx=\\dfrac{x^{-2}}{k}+C$, ¿cuánto vale $k$?', r: ['-2'], ph: 'Puede ser negativo',
          x: 'Subís el exponente: $-3+1=-2$, y dividís por ese mismo número. Queda $\\frac{x^{-2}}{-2}+C$, o sea $-\\frac{1}{2x^{2}}+C$.', teclas: ['-'] },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u0l2',
      titulo: 'Sustitución',
      objetivo: 'Reconocer cuándo hay una función "de adentro" y cambiar de variable.',
      teoria: [
        { p: 'La sustitución sirve cuando en el integrando hay **una función metida dentro de otra**, y además anda dando vueltas algo parecido a su derivada.' },
        { def: ['El método en 5 pasos', 'Elegís $u$ · derivás $\\frac{du}{dx}$ · despejás $dx$ · reemplazás todo · integrás y volvés a $x$.'] },
        { p: '¿Qué se elige como $u$? La función **de adentro**: lo que está dentro del coseno, dentro de la raíz, dentro del exponente, o el denominador entero.' },
        { ej: ['$\\int x\\cos(7x^{2}+9)\\,dx$  — el ejemplo de la clase', [
          'Elijo lo de adentro: $u = 7x^{2}+9$',
          'Derivo: $\\dfrac{du}{dx}=14x$',
          'Despejo $dx$: $dx=\\dfrac{du}{14x}$',
          'Reemplazo: $\\displaystyle\\int x\\cos u\;\\dfrac{du}{14x}$ — la $x$ se simplifica, por eso funcionaba',
          'Queda $\\dfrac{1}{14}\\displaystyle\\int \\cos u\\,du=\\dfrac{1}{14}\\sen u$',
          'Vuelvo a $x$: $\\dfrac{1}{14}\\sen(7x^{2}+9)+C$',
        ]] },
        { ojo: 'Si después de reemplazar **te sobra una $x$ suelta**, elegiste mal el $u$ (o el ejercicio no es de sustitución). Todo tiene que quedar en función de $u$.' },
        { h: 'El caso que más vas a usar' },
        { p: 'Cuando el numerador es la derivada del denominador, sale logaritmo:' },
        { mat: '\\int \\frac{f\'(x)}{f(x)}\\,dx = \\ln|f(x)| + C' },
        { ej: ['$\\int \\dfrac{x}{x^{2}+4}\\,dx$', [
          '$u=x^{2}+4$, entonces $\\dfrac{du}{dx}=2x$ y $dx=\\dfrac{du}{2x}$',
          '$\\displaystyle\\int \\dfrac{x}{u}\\cdot\\dfrac{du}{2x}=\\dfrac{1}{2}\\displaystyle\\int\\dfrac{1}{u}du$',
          '$=\\dfrac{1}{2}\\ln|u| = \\dfrac{1}{2}\\ln|x^{2}+4| + C$',
        ]] },
        { truco: 'Para $\\int e^{kx}dx$ y $\\int \\cos(kx)\\,dx$ con $k$ constante no hace falta escribir toda la sustitución: el resultado sale directo dividiendo por $k$.' },
      ],
      formulas: [
        ['Cambio de variable', '\\int f(g(x))\\,g\'(x)\\,dx = \\int f(u)\\,du \\quad\\text{con } u=g(x)'],
        ['Derivada sobre función', '\\int \\frac{f\'(x)}{f(x)}dx = \\ln|f(x)|+C'],
        ['Atajo exponencial', '\\int e^{kx}dx = \\frac{1}{k}e^{kx}+C'],
      ],
      ejercicios: [
        { t: 'ord', p: 'Ordená los pasos del método de sustitución',
          o: ['Elegir $u$ (la función de adentro)', 'Derivar: calcular $\\dfrac{du}{dx}$', 'Despejar $dx$', 'Reemplazar y simplificar hasta que todo quede en $u$', 'Integrar y volver a la variable $x$'],
          x: 'Siempre igual. Si te salteás el "despejar $dx$" terminás mezclando diferenciales y el resultado sale mal por un factor.' },
        { t: 'mc', p: 'En $\\int x\\cos(7x^{2}+9)\\,dx$, ¿qué conviene tomar como $u$?',
          o: ['$u=7x^{2}+9$', '$u=x$', '$u=\\cos(7x^{2}+9)$', '$u=14x$'], r: 0,
          x: 'Lo de adentro del coseno. Su derivada es $14x$, y afuera hay una $x$ que se va a simplificar. Ese es exactamente el indicio de que la sustitución va a funcionar.' },
        { t: 'in', p: 'Si $u=7x^{2}+9$, ¿cuánto vale $\\dfrac{du}{dx}$?', r: ['14x', '14*x'], ph: 'Por ejemplo: 14x',
          x: 'Derivás término a término: la derivada de $7x^{2}$ es $14x$ y la de la constante $9$ es $0$.' },
        { t: 'mc', p: 'Terminá el ejercicio: $\\int x\\cos(7x^{2}+9)\\,dx =$',
          o: ['$\\dfrac{1}{14}\\sen(7x^{2}+9)+C$', '$14\\,\\sen(7x^{2}+9)+C$', '$\\sen(7x^{2}+9)+C$', '$-\\dfrac{1}{14}\\sen(7x^{2}+9)+C$'], r: 0,
          x: 'Queda $\\frac{1}{14}\\int\\cos u\\,du=\\frac{1}{14}\\sen u$. Verificá derivando: $\\frac{1}{14}\\cdot\\cos(7x^2+9)\\cdot 14x = x\\cos(7x^2+9)$.' },
        { t: 'mc', p: 'Resolvé $\\int e^{-3x}dx$', o: ['$-\\dfrac{1}{3}e^{-3x}+C$', '$\\dfrac{1}{3}e^{-3x}+C$', '$-3e^{-3x}+C$', '$e^{-3x}+C$'], r: 0,
          x: 'Dividís por el $k$ del exponente, que acá es $-3$. Esta integral te va a aparecer en cada ecuación diferencial lineal.' },
        { t: 'in', p: 'Resolvé $\\int \\sen(5x)\\,dx = k\\cos(5x)+C$. ¿Cuánto vale $k$?', r: ['-1/5', '-0.2'], ph: 'Ojo con el signo',
          x: 'Dos cosas se juntan: la primitiva de $\\sen$ lleva menos, y hay que dividir por $5$. Queda $-\\frac{1}{5}\\cos(5x)+C$.', teclas: ['-', '/'] },
        { t: 'hue', p: 'Completá el resultado', tpl: '$\\displaystyle\\int \\frac{2x}{x^{2}+1}\\,dx = $ ___ $|x^{2}+1| + C$',
          r: [['ln', 'log']], x: 'El numerador $2x$ es exactamente la derivada de $x^{2}+1$. Cuando pasa eso, el resultado es el logaritmo natural del denominador.' },
        { t: 'mc', p: 'Resolvé $\\int \\dfrac{x}{x^{2}+4}\\,dx$', o: ['$\\dfrac{1}{2}\\ln|x^{2}+4|+C$', '$\\ln|x^{2}+4|+C$', '$2\\ln|x^{2}+4|+C$', '$\\dfrac{1}{2}\\arctan\\dfrac{x}{2}+C$'], r: 0,
          x: 'La derivada de $x^{2}+4$ es $2x$, pero arriba hay sólo $x$: falta un $2$, y eso deja el $\\frac{1}{2}$ afuera. La última opción es la trampa: esa sería la integral de $\\frac{1}{x^{2}+4}$, sin la $x$.' },
        { t: 'mc', p: 'Estás resolviendo $\\int x\\sqrt{x^{2}-1}\\,dx$ y tomás $u=x^{2}-1$. Después de reemplazar, ¿qué queda?',
          o: ['$\\dfrac{1}{2}\\displaystyle\\int \\sqrt{u}\\,du$', '$\\displaystyle\\int x\\sqrt{u}\\,du$', '$2\\displaystyle\\int \\sqrt{u}\\,du$', '$\\displaystyle\\int \\sqrt{u}\\,du$'], r: 0,
          x: '$du=2x\\,dx$, así que $dx=\\frac{du}{2x}$. La $x$ de afuera se simplifica con la de abajo y sobrevive el $\\frac{1}{2}$.' },
        { t: 'vf', p: 'Si después de sustituir te queda una $x$ suelta mezclada con $u$, podés seguir igual.', r: false,
          x: 'No. Ese es el aviso de que la sustitución elegida no sirve: o cambiás el $u$, o el ejercicio se resuelve por otro método.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u0l3',
      titulo: 'Integración por partes',
      objetivo: 'Usar la fórmula cuando hay un producto de funciones de distinta familia.',
      teoria: [
        { p: 'Sustitución no siempre alcanza. Cuando el integrando es un **producto de dos funciones distintas** —un polinomio por una exponencial, un polinomio por un logaritmo— se usa partes.' },
        { def: ['Fórmula', '$$\\int u\\,dv = u\\cdot v - \\int v\\,du$$'] },
        { p: 'La gracia es que la integral nueva, $\\int v\\,du$, tiene que ser **más fácil** que la original. Si te queda más difícil, elegiste mal quién es $u$.' },
        { h: '¿Quién es $u$?' },
        { p: 'Se elige como $u$ lo que se **simplifica al derivar**, y como $dv$ lo que se **sabe integrar**. El orden de preferencia para $u$ es:' },
        { num: ['**L**ogarítmica ($\\ln x$)', '**I**nversa trigonométrica ($\\arctan x$)', '**A**lgebraica ($x$, $x^{2}$)', '**T**rigonométrica ($\\sen x$, $\\cos x$)', '**E**xponencial ($e^{x}$)'] },
        { truco: 'La regla nemotécnica es **LIATE**. Lo que aparece primero en la lista, ese es tu $u$.' },
        { ej: ['$\\int x\\,e^{2x}\\,dx$  — el ejemplo de la clase', [
          'Por LIATE, algebraica antes que exponencial: $u=x$, $dv=e^{2x}dx$',
          'Derivo $u$: $du = dx$. Integro $dv$: $v=\\dfrac{1}{2}e^{2x}$',
          'Aplico la fórmula: $x\\cdot\\dfrac{1}{2}e^{2x}-\\displaystyle\\int \\dfrac{1}{2}e^{2x}dx$',
          '$=\\dfrac{1}{2}xe^{2x}-\\dfrac{1}{2}\\cdot\\dfrac{1}{2}e^{2x}$',
          'Resultado: $\\dfrac{1}{2}xe^{2x}-\\dfrac{1}{4}e^{2x}+C$, o sacando factor común $\\dfrac{1}{2}e^{2x}\\left(x-\\dfrac{1}{2}\\right)+C$',
        ]] },
        { ej: ['$\\int x\\ln x\\,dx$', [
          'Acá el logaritmo manda: $u=\\ln x$, $dv = x\\,dx$',
          '$du=\\dfrac{1}{x}dx$ y $v=\\dfrac{x^{2}}{2}$',
          '$\\dfrac{x^{2}}{2}\\ln x - \\displaystyle\\int \\dfrac{x^{2}}{2}\\cdot\\dfrac{1}{x}dx = \\dfrac{x^{2}}{2}\\ln x - \\dfrac{1}{2}\\displaystyle\\int x\\,dx$',
          '$=\\dfrac{x^{2}}{2}\\ln x - \\dfrac{x^{2}}{4}+C$',
        ]] },
        { ojo: 'No sabemos integrar $\\ln x$ directamente. Por eso, cuando aparece un logaritmo, **siempre** va como $u$: lo vamos a derivar, no a integrar.' },
      ],
      formulas: [
        ['Por partes', '\\int u\\,dv = u\\,v - \\int v\\,du'],
        ['Elección de $u$ (LIATE)', '\\text{Log} \\to \\text{Inv.trig} \\to \\text{Alg} \\to \\text{Trig} \\to \\text{Exp}'],
        ['Resultado tipo', '\\int x\\,e^{kx}dx = \\frac{1}{k}xe^{kx}-\\frac{1}{k^{2}}e^{kx}+C'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Cuál es la fórmula de integración por partes?',
          o: ['$\\int u\\,dv = uv - \\int v\\,du$', '$\\int u\\,dv = uv + \\int v\\,du$', '$\\int u\\,dv = \\int u \\cdot \\int dv$', '$\\int u\\,dv = u\\,du - v\\,dv$'], r: 0,
          x: 'Sale de derivar un producto y despejar. El signo menos es lo que más se olvida.' },
        { t: 'mc', p: 'En $\\int x\\,e^{2x}dx$, ¿qué tomás como $u$?', o: ['$u=x$', '$u=e^{2x}$', '$u=2x$', '$u=xe^{2x}$'], r: 0,
          x: 'Por LIATE, la algebraica va antes que la exponencial. Además $x$ se simplifica al derivar (queda $1$), que es justo lo que buscamos.' },
        { t: 'mc', p: 'Si $dv = e^{2x}dx$, ¿cuánto vale $v$?', o: ['$v=\\dfrac{1}{2}e^{2x}$', '$v=e^{2x}$', '$v=2e^{2x}$', '$v=\\dfrac{1}{2}e^{x}$'], r: 0,
          x: 'Integrás $dv$: $\\int e^{2x}dx=\\frac{1}{2}e^{2x}$. Acá no hace falta poner $+C$, se absorbe al final.' },
        { t: 'mc', p: 'Terminá: $\\int x\\,e^{2x}dx =$',
          o: ['$\\dfrac{1}{2}xe^{2x}-\\dfrac{1}{4}e^{2x}+C$', '$\\dfrac{1}{2}xe^{2x}+\\dfrac{1}{4}e^{2x}+C$', '$\\dfrac{1}{2}xe^{2x}-\\dfrac{1}{2}e^{2x}+C$', '$xe^{2x}-e^{2x}+C$'], r: 0,
          x: 'La segunda integral es $\\int\\frac{1}{2}e^{2x}dx=\\frac{1}{4}e^{2x}$, y va restando. Equivale a $\\frac{1}{2}e^{2x}\\left(x-\\frac{1}{2}\\right)+C$.' },
        { t: 'in', p: 'En $\\int x\\,e^{2x}dx = \\dfrac{1}{2}xe^{2x} - k\\,e^{2x}+C$, ¿cuánto vale $k$?', r: ['1/4', '0.25'], ph: 'Una fracción',
          x: '$\\int \\frac{1}{2}e^{2x}dx = \\frac{1}{2}\\cdot\\frac{1}{2}e^{2x}=\\frac{1}{4}e^{2x}$.', teclas: ['/'] },
        { t: 'mc', p: 'En $\\int x\\ln x\\,dx$, ¿qué tomás como $u$?', o: ['$u=\\ln x$', '$u=x$', '$u=x\\ln x$', '$u=\\dfrac{1}{x}$'], r: 0,
          x: 'El logaritmo siempre va como $u$, porque no sabemos integrarlo pero sí derivarlo ($\\frac{1}{x}$). Es la primera letra de LIATE.' },
        { t: 'mc', p: 'Resolvé $\\int x\\ln x\\,dx$',
          o: ['$\\dfrac{x^{2}}{2}\\ln x - \\dfrac{x^{2}}{4}+C$', '$\\dfrac{x^{2}}{2}\\ln x - \\dfrac{x^{2}}{2}+C$', '$\\dfrac{x^{2}}{2}\\ln x + \\dfrac{x^{2}}{4}+C$', '$\\ln x \\cdot \\dfrac{x^{2}}{2}+C$'], r: 0,
          x: 'Con $u=\\ln x$, $v=\\frac{x^2}{2}$: queda $\\frac{x^{2}}{2}\\ln x-\\frac{1}{2}\\int x\\,dx = \\frac{x^{2}}{2}\\ln x-\\frac{x^{2}}{4}$.' },
        { t: 'mc', p: 'Resolvé $\\int x\\,e^{x}dx$', o: ['$e^{x}(x-1)+C$', '$e^{x}(x+1)+C$', '$xe^{x}+C$', '$\\dfrac{x^{2}}{2}e^{x}+C$'], r: 0,
          x: '$u=x$, $v=e^{x}$: $xe^{x}-\\int e^{x}dx = xe^{x}-e^{x}=e^{x}(x-1)$. Este resultado aparece tal cual en las ecuaciones lineales.' },
        { t: 'ord', p: 'Ordená los pasos de integración por partes',
          o: ['Elegir $u$ con LIATE y llamar $dv$ al resto', 'Calcular $du$ derivando $u$', 'Calcular $v$ integrando $dv$', 'Armar $uv - \\int v\\,du$', 'Resolver la integral que quedó'],
          x: 'Si la integral final te quedó peor que la original, volvé al paso 1 y cambiá la elección.' },
        { t: 'vf', p: 'Integración por partes sirve cuando el integrando es un producto de funciones de distinta familia.', r: true,
          x: 'Polinomio por exponencial, polinomio por logaritmo, exponencial por trigonométrica. Si son de la misma familia normalmente conviene sustitución.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u0l4',
      titulo: 'Fracciones simples: raíces reales distintas',
      objetivo: 'Partir un cociente de polinomios en fracciones que sí sabés integrar.',
      teoria: [
        { p: 'Cuando tenés $\\displaystyle\\int\\frac{P(x)}{Q(x)}dx$ con polinomios y no es una sustitución directa, el camino es **romper la fracción en pedazos chicos**. A eso se le dice descomponer en fracciones simples (o parciales).' },
        { ojo: 'Antes de arrancar, verificá que el grado del numerador sea **menor** que el del denominador. Si no lo es, hay que dividir los polinomios primero.' },
        { def: ['Los 3 casos', 'Todo depende de cómo son las raíces del **denominador**: reales distintas (caso 1), reales repetidas (caso 2) o complejas (caso 3).'] },
        { h: 'Caso 1: raíces reales distintas' },
        { p: 'Si $Q(x)=(x-x_1)(x-x_2)$ con $x_1\\neq x_2$, se propone una fracción por cada factor:' },
        { mat: '\\frac{1}{(x-x_1)(x-x_2)} = \\frac{A}{x-x_1}+\\frac{B}{x-x_2}' },
        { ej: ['$\\int \\dfrac{1}{x^{2}+3x-4}\\,dx$  — el ejemplo de la clase', [
          'Factorizo el denominador. Raíces de $x^{2}+3x-4=0$: con la resolvente, $x_1=1$ y $x_2=-4$',
          'Entonces $x^{2}+3x-4=(x-1)(x+4)$',
          'Propongo: $\\dfrac{1}{(x-1)(x+4)}=\\dfrac{A}{x-1}+\\dfrac{B}{x+4}$',
          'Multiplico todo por el denominador: $1 = A(x+4)+B(x-1)$',
          'Truco: reemplazo por las raíces. Con $x=1$: $1=5A \\Rightarrow A=\\dfrac{1}{5}$',
          'Con $x=-4$: $1=-5B \\Rightarrow B=-\\dfrac{1}{5}$',
          'Integro cada pedazo: $\\dfrac{1}{5}\\ln|x-1|-\\dfrac{1}{5}\\ln|x+4|+C$',
        ]] },
        { truco: 'Para encontrar $A$ y $B$ no hace falta armar un sistema: **reemplazá $x$ por cada raíz**. Cada vez se te anula un término y despejás la constante de una.' },
        { code: ['resultado', '∫ 1/(x²+3x−4) dx = (1/5)·ln|x−1| − (1/5)·ln|x+4| + C\n                  = (1/5)·ln|(x−1)/(x+4)| + C'] },
      ],
      formulas: [
        ['Caso 1 (raíces reales $\\neq$)', '\\frac{P(x)}{(x-x_1)(x-x_2)} = \\frac{A}{x-x_1}+\\frac{B}{x-x_2}'],
        ['Cada pedazo integra a', '\\int \\frac{A}{x-a}dx = A\\ln|x-a|+C'],
        ['Resolvente', 'x = \\frac{-b \\pm \\sqrt{b^{2}-4ac}}{2a}'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Cuándo se usa el método de fracciones simples?', fijo: true,
          o: ['Cuando el integrando es un cociente de polinomios', 'Cuando hay un producto de funciones', 'Cuando hay una función dentro de otra', 'Cuando aparece un logaritmo'], r: 0,
          x: 'Cociente de polinomios, con el grado de arriba menor que el de abajo. Producto es partes; función dentro de función es sustitución.' },
        { t: 'vf', p: 'Si el grado del numerador es mayor o igual al del denominador, primero hay que dividir los polinomios.', r: true,
          x: 'Sí. La descomposición sólo funciona con fracciones propias. Si no, dividís y te queda un polinomio más una fracción propia.' },
        { t: 'hue', p: 'Factorizá el denominador', tpl: '$x^{2}+3x-4 = (x-$ ___ $)(x+$ ___ $)$', r: [['1'], ['4']],
          x: 'Con la resolvente: $x=\\frac{-3\\pm\\sqrt{9+16}}{2}=\\frac{-3\\pm 5}{2}$, o sea $x_1=1$ y $x_2=-4$. La forma factorizada es $(x-1)(x+4)$.' },
        { t: 'mc', p: '¿Cómo se propone la descomposición de $\\dfrac{1}{(x-1)(x+4)}$?',
          o: ['$\\dfrac{A}{x-1}+\\dfrac{B}{x+4}$', '$\\dfrac{Ax+B}{(x-1)(x+4)}$', '$\\dfrac{A}{x-1}+\\dfrac{B}{(x-1)^{2}}$', '$\\dfrac{Ax+B}{x-1}+\\dfrac{C}{x+4}$'], r: 0,
          x: 'Caso 1: una constante sobre cada factor lineal distinto. La tercera opción sería el caso 2 (raíz repetida) y la segunda mezcla el caso 3.' },
        { t: 'in', p: 'En $\\dfrac{1}{(x-1)(x+4)}=\\dfrac{A}{x-1}+\\dfrac{B}{x+4}$, ¿cuánto vale $A$?', r: ['1/5', '0.2'], ph: 'Una fracción',
          x: 'De $1=A(x+4)+B(x-1)$, reemplazo $x=1$: se anula el término de $B$ y queda $1=5A$, así que $A=\\frac{1}{5}$.', teclas: ['/'] },
        { t: 'in', p: '¿Y cuánto vale $B$?', r: ['-1/5', '-0.2'], ph: 'Ojo con el signo', teclas: ['-', '/'],
          x: 'Reemplazo $x=-4$: $1=B(-4-1)=-5B$, entonces $B=-\\frac{1}{5}$.' },
        { t: 'mc', p: 'Terminá: $\\int \\dfrac{1}{x^{2}+3x-4}dx=$',
          o: ['$\\dfrac{1}{5}\\ln|x-1|-\\dfrac{1}{5}\\ln|x+4|+C$', '$\\dfrac{1}{5}\\ln|x-1|+\\dfrac{1}{5}\\ln|x+4|+C$', '$\\ln|x-1|-\\ln|x+4|+C$', '$\\dfrac{1}{5}\\ln|x^{2}+3x-4|+C$'], r: 0,
          x: 'Cada fracción integra a un logaritmo con su constante adelante. Usando propiedades se puede juntar en $\\frac{1}{5}\\ln\\left|\\frac{x-1}{x+4}\\right|+C$.' },
        { t: 'mc', p: '¿Cuál es la forma correcta para $\\dfrac{5}{(x-3)(x+1)}$?',
          o: ['$\\dfrac{A}{x-3}+\\dfrac{B}{x+1}$', '$\\dfrac{5A}{x-3}+\\dfrac{5B}{x+1}$', '$\\dfrac{A}{(x-3)(x+1)}$', '$\\dfrac{Ax+B}{x-3}+\\dfrac{C}{x+1}$'], r: 0,
          x: 'El $5$ del numerador no cambia la forma de la propuesta: va a aparecer al despejar $A$ y $B$.' },
        { t: 'ord', p: 'Ordená el método de fracciones simples',
          o: ['Comprobar que el grado de arriba sea menor que el de abajo', 'Factorizar el denominador buscando sus raíces', 'Proponer la descomposición según el caso', 'Hallar las constantes reemplazando por las raíces', 'Integrar cada fracción por separado'],
          x: 'El paso de factorizar es el que decide todo: según cómo salgan las raíces, estás en el caso 1, 2 o 3.' },
        { t: 'in', p: 'En $\\dfrac{1}{(x-2)(x+3)}=\\dfrac{A}{x-2}+\\dfrac{B}{x+3}$, ¿cuánto vale $A$?', r: ['1/5', '0.2'], ph: 'Una fracción', teclas: ['/'],
          x: 'De $1=A(x+3)+B(x-2)$ con $x=2$: $1=5A$, así que $A=\\frac{1}{5}$.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u0l5',
      titulo: 'Fracciones simples: raíces repetidas y complejas',
      objetivo: 'Resolver los casos 2 y 3, que son los que aparecen en Laplace.',
      teoria: [
        { h: 'Caso 2: raíz real repetida' },
        { p: 'Si el denominador tiene una raíz que se repite, no alcanza con una sola fracción: hay que poner **una por cada potencia**, desde la primera hasta la máxima.' },
        { mat: '\\frac{P(x)}{(x+a)^{m}} = \\frac{A}{(x+a)^{1}}+\\frac{B}{(x+a)^{2}}+\\cdots+\\frac{C}{(x+a)^{m}}' },
        { ej: ['$\\int \\dfrac{x+4}{x^{2}+2x+1}\\,dx$  — el ejemplo de la clase', [
          'Raíces de $x^{2}+2x+1=0$: $x_1=x_2=-1$. Es una raíz doble: $(x+1)^{2}$',
          'Propongo: $\\dfrac{x+4}{(x+1)^{2}}=\\dfrac{A}{x+1}+\\dfrac{B}{(x+1)^{2}}$',
          'Multiplico: $x+4 = A(x+1)+B$',
          'Con $x=-1$: $-1+4=B \\Rightarrow B=3$',
          'Con cualquier otro valor (o comparando el coeficiente de $x$): $A=1$',
          'Integro: $\\displaystyle\\int\\dfrac{1}{x+1}dx+3\\displaystyle\\int (x+1)^{-2}dx = \\ln|x+1| - \\dfrac{3}{x+1}+C$',
        ]] },
        { ojo: 'La segunda fracción **no** da logaritmo: $\\int (x+1)^{-2}dx$ se resuelve con la regla de la potencia y da $-\\dfrac{1}{x+1}$. Sólo el exponente $1$ da logaritmo.' },
        { h: 'Caso 3: raíces complejas' },
        { p: 'Si un factor cuadrático **no tiene raíces reales** (su discriminante da negativo), no se puede factorizar más. Encima de ese factor va un numerador **lineal**:' },
        { mat: '\\frac{P(x)}{x\\,(x^{2}+k)} = \\frac{A}{x}+\\frac{Bx+C}{x^{2}+k}' },
        { ej: ['$\\int \\dfrac{2x^{2}-x+4}{x^{3}+4x}\\,dx$  — el ejemplo de la clase', [
          'Factor común en el denominador: $x^{3}+4x = x(x^{2}+4)$',
          '$x^{2}+4=0$ daría $x=\\sqrt{-4}$: no tiene raíces reales, es el caso 3',
          'Propongo: $\\dfrac{2x^{2}-x+4}{x(x^{2}+4)}=\\dfrac{A}{x}+\\dfrac{Bx+C}{x^{2}+4}$',
          'Multiplico: $2x^{2}-x+4 = A(x^{2}+4)+(Bx+C)\\,x$',
          'Igualo coeficientes: en $x^{0}$, $4=4A \\Rightarrow A=1$; en $x^{2}$, $2=A+B \\Rightarrow B=1$; en $x^{1}$, $-1=C$',
          'Queda $\\displaystyle\\int\\dfrac{1}{x}dx+\\displaystyle\\int\\dfrac{x}{x^{2}+4}dx-\\displaystyle\\int\\dfrac{1}{x^{2}+4}dx$',
          'La primera es tabla, la segunda sustitución y la tercera arcotangente:',
          '$\\ln|x|+\\dfrac{1}{2}\\ln|x^{2}+4|-\\dfrac{1}{2}\\arctan\\dfrac{x}{2}+C$',
        ]] },
        { truco: 'En el caso 3 el truco de "reemplazar por la raíz" no alcanza, porque las raíces son complejas. Ahí conviene **igualar coeficientes**: agrupás por potencias de $x$ y armás el sistema.' },
        { p: 'Estos dos casos son los que más vas a usar más adelante: al aplicar la **transformada inversa de Laplace** casi siempre hay que descomponer una fracción en $s$ exactamente así.' },
      ],
      formulas: [
        ['Caso 2 (raíz repetida)', '\\frac{P(x)}{(x+a)^{2}}=\\frac{A}{x+a}+\\frac{B}{(x+a)^{2}}'],
        ['Caso 3 (raíces complejas)', '\\frac{P(x)}{x(x^{2}+k)}=\\frac{A}{x}+\\frac{Bx+C}{x^{2}+k}'],
        ['Potencia negativa', '\\int \\frac{dx}{(x+a)^{2}} = -\\frac{1}{x+a}+C'],
        ['Arcotangente', '\\int \\frac{dx}{x^{2}+a^{2}} = \\frac{1}{a}\\arctan\\frac{x}{a}+C'],
      ],
      ejercicios: [
        { t: 'mc', p: 'Las raíces de $x^{2}+2x+1=0$ son $x_1=x_2=-1$. ¿Qué descomposición corresponde para $\\dfrac{x+4}{x^{2}+2x+1}$?',
          o: ['$\\dfrac{A}{x+1}+\\dfrac{B}{(x+1)^{2}}$', '$\\dfrac{A}{x+1}+\\dfrac{B}{x-1}$', '$\\dfrac{Ax+B}{(x+1)^{2}}$', '$\\dfrac{A}{(x+1)^{2}}$'], r: 0,
          x: 'Raíz doble = caso 2. Va una fracción por cada potencia, de la $1$ a la máxima. Poner sólo la de exponente 2 no alcanza para representar cualquier numerador.' },
        { t: 'in', p: 'De $x+4=A(x+1)+B$, reemplazando $x=-1$, ¿cuánto vale $B$?', r: ['3'], ph: 'Un número',
          x: 'Con $x=-1$ se anula el término de $A$ y queda $-1+4=B$, o sea $B=3$.' },
        { t: 'in', p: '¿Y cuánto vale $A$?', r: ['1'], ph: 'Un número',
          x: 'Comparando el coeficiente de $x$ a los dos lados de $x+4=A(x+1)+B$: a la izquierda hay $1\\cdot x$, a la derecha $A\\cdot x$. Entonces $A=1$.' },
        { t: 'mc', p: 'Resolvé $\\int \\dfrac{x+4}{x^{2}+2x+1}dx$',
          o: ['$\\ln|x+1|-\\dfrac{3}{x+1}+C$', '$\\ln|x+1|+3\\ln|x+1|^{2}+C$', '$\\ln|x+1|+\\dfrac{3}{x+1}+C$', '$\\dfrac{1}{x+1}-\\dfrac{3}{(x+1)^{2}}+C$'], r: 0,
          x: 'El primer pedazo da logaritmo; el segundo es $3\\int(x+1)^{-2}dx = 3\\cdot\\frac{(x+1)^{-1}}{-1}=-\\frac{3}{x+1}$.' },
        { t: 'vf', p: 'La fracción $\\dfrac{B}{(x+1)^{2}}$ también integra a un logaritmo.', r: false,
          x: 'No. Sólo el exponente $1$ da logaritmo. Con exponente $2$ se usa la regla de la potencia y da $-\\frac{B}{x+1}$.' },
        { t: 'mc', p: 'Factorizá $x^{3}+4x$', o: ['$x(x^{2}+4)$', '$(x+2)(x-2)x$', '$x^{2}(x+4)$', '$(x^{2}+4)(x^{2}-4)$'], r: 0,
          x: 'Factor común $x$. Y $x^{2}+4$ no se puede factorizar en reales: $x^{2}=-4$ no tiene solución real.' },
        { t: 'mc', p: '¿Qué descomposición corresponde para $\\dfrac{2x^{2}-x+4}{x(x^{2}+4)}$?',
          o: ['$\\dfrac{A}{x}+\\dfrac{Bx+C}{x^{2}+4}$', '$\\dfrac{A}{x}+\\dfrac{B}{x^{2}+4}$', '$\\dfrac{A}{x}+\\dfrac{B}{x+2}+\\dfrac{C}{x-2}$', '$\\dfrac{Ax+B}{x}+\\dfrac{C}{x^{2}+4}$'], r: 0,
          x: 'Caso 3: arriba de un factor cuadrático irreducible va un numerador lineal $Bx+C$, no una constante sola.' },
        { t: 'hue', p: 'De $2x^{2}-x+4=A(x^{2}+4)+(Bx+C)x$, igualando coeficientes:', tpl: '$A=$ ___ , $B=$ ___ , $C=$ ___',
          r: [['1'], ['1'], ['-1']],
          x: 'Término independiente: $4=4A \\Rightarrow A=1$. Coeficiente de $x^{2}$: $2=A+B \\Rightarrow B=1$. Coeficiente de $x$: $-1=C$.' },
        { t: 'mc', p: '¿Cómo se integra $\\displaystyle\\int\\dfrac{1}{x^{2}+4}dx$?',
          o: ['$\\dfrac{1}{2}\\arctan\\dfrac{x}{2}+C$', '$\\ln|x^{2}+4|+C$', '$\\dfrac{1}{2}\\ln|x^{2}+4|+C$', '$\\arctan(x^{2}+4)+C$'], r: 0,
          x: 'Es la fila de arcotangente con $a^{2}=4$, o sea $a=2$. Sin la $x$ arriba no hay sustitución posible: va directo a la tabla.' },
        { t: 'mc', p: 'Terminá: $\\int \\dfrac{2x^{2}-x+4}{x^{3}+4x}dx=$',
          o: ['$\\ln|x|+\\dfrac{1}{2}\\ln|x^{2}+4|-\\dfrac{1}{2}\\arctan\\dfrac{x}{2}+C$', '$\\ln|x|+\\ln|x^{2}+4|-\\arctan\\dfrac{x}{2}+C$', '$\\ln|x|-\\dfrac{1}{2}\\ln|x^{2}+4|+\\dfrac{1}{2}\\arctan\\dfrac{x}{2}+C$', '$\\ln|x|+\\dfrac{1}{2}\\arctan\\dfrac{x}{2}+C$'], r: 0,
          x: 'Los tres pedazos: tabla, sustitución (deja $\\frac{1}{2}$) y arcotangente (deja $\\frac{1}{2}$ y va restando porque $C=-1$).' },
        { t: 'vf', p: 'En el caso 3 conviene igualar coeficientes en vez de reemplazar por las raíces.', r: true,
          x: 'Las raíces de un factor irreducible son complejas, así que reemplazarlas no es práctico. Agrupar por potencias de $x$ y armar el sistema es el camino.' },
      ],
    },
  ],
});
