/* Unidad 1 — Qué es una ecuación diferencial
   Guía Teórica N° 1 del cuadernillo + clase del 30/07. */
(window.__UNIDADES = window.__UNIDADES || []).push({
  id: 'u1',
  n: 1,
  titulo: 'Qué es una ecuación diferencial',
  glifo: 'y\u2032',
  resumen: 'Orden, grado, solución general y particular. La base de toda la materia.',
  lecciones: [

    /* ------------------------------------------------------------------ */
    {
      id: 'u1l1',
      titulo: 'La idea',
      objetivo: 'Reconocer una ecuación diferencial y saber para qué sirve.',
      teoria: [
        { def: ['Ecuación diferencial', 'Una ecuación que contiene una **función desconocida** y una o más de **sus derivadas**.'] },
        { p: 'En una ecuación común, la incógnita es un número: en $2x+3=7$ buscás el $x$ que la cumple. En una ecuación diferencial la incógnita es una **función entera**: buscás la $y(x)$ que la cumple.' },
        { ej: ['Comparación', [
          'Ecuación común: $2x+3=7$ — la respuesta es $x=2$',
          'Ecuación diferencial: $y\'=-x\\,y$ — la respuesta es una función, $y=e^{-x^{2}/2}\\cdot k$',
        ]] },
        { h: '¿Por qué aparecen?' },
        { p: 'Porque casi todo lo que nos interesa medir se describe mejor por **cómo cambia** que por su valor. La velocidad de enfriamiento de un procesador, la carga de un capacitor, el crecimiento de una población, la caída de la señal en un cable: todos son enunciados sobre derivadas.' },
        { code: ['idea', 'temperatura que se enfría:\n   la velocidad de enfriamiento es proporcional\n   a la diferencia con el ambiente\n\n   dT/dt = -k · (T - Tamb)      ← eso es una ecuación diferencial'] },
        { h: 'Orden y grado' },
        { def: ['Orden', 'El de la derivada **más alta** que aparece. $y\'$ es orden 1, $y\'\'$ es orden 2.'] },
        { def: ['Grado', 'El mayor **exponente** con el que aparece esa derivada de orden más alto.'] },
        { ej: ['$(y\'\')^{4}-y\'x+y^{5}=\\cos x$', [
          'La derivada más alta es $y\'\'$ → **orden 2**',
          'Esa derivada está elevada a la cuarta → **grado 4**',
          'El $y^{5}$ no cuenta: el grado mira la derivada, no la función',
        ]] },
        { ojo: 'Confundir grado con orden es un error clásico. El **orden** mira *cuántas veces derivaste*; el **grado** mira *a qué potencia está elevada* la derivada más alta.' },
        { p: 'En esta materia vas a trabajar con ecuaciones de **primer orden** (unidades 2, 3 y 4) y de **segundo orden** (unidad 5), siempre de grado 1.' },
      ],
      formulas: [
        ['Notaciones equivalentes', 'y\' = \\frac{dy}{dx} \\qquad y\'\' = \\frac{d^{2}y}{dx^{2}}'],
        ['Forma general de 1er orden', '\\frac{dy}{dx} = f(x, y)'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Qué es una ecuación diferencial?', fijo: true,
          o: ['Una ecuación que contiene una función desconocida y una o más de sus derivadas', 'Una ecuación con más de una incógnita', 'Una ecuación donde hay que derivar los dos lados', 'Una ecuación cuya solución es un número'], r: 0,
          x: 'La clave es que la incógnita es una función, no un número, y que aparece junto a sus derivadas.' },
        { t: 'mc', p: '¿Cuál de estas NO es una ecuación diferencial?',
          o: ['$x^{2}+3x-4=0$', '$y\'=-xy$', '$\\dfrac{dy}{dx}+2y=x$', '$y\'\'+y=0$'], r: 0, fijo: true,
          x: 'La primera es una ecuación algebraica común: no aparece ninguna derivada. Su solución son números ($1$ y $-4$), no funciones.' },
        { t: 'in', p: '¿Cuál es el **orden** de $(y\'\')^{4}-y\'x+y^{5}=\\cos x$?', r: ['2'], ph: 'Un número',
          x: 'La derivada más alta que aparece es $y\'\'$, que es la segunda derivada. Orden 2.' },
        { t: 'in', p: '¿Y cuál es el **grado**?', r: ['4'], ph: 'Un número',
          x: 'El grado es el exponente de la derivada de mayor orden. Como $y\'\'$ está elevada a la cuarta, el grado es 4. El $y^{5}$ no interviene.' },
        { t: 'par', p: 'Emparejá cada ecuación con su orden',
          o: [['$y\'+2y=x$', 'Orden 1'], ['$y\'\'-6y\'+9y=0$', 'Orden 2'], ['$\\dfrac{d^{3}y}{dx^{3}}=x$', 'Orden 3'], ['$(y\')^{5}=x$', 'Orden 1']],
          x: 'Fijate en la última: está elevada a la quinta, pero sigue siendo la **primera** derivada. Eso es grado 5, orden 1.' },
        { t: 'vf', p: 'La ecuación $(y\')^{3}+y=x$ es de orden 3.', r: false,
          x: 'Es de **orden 1** y **grado 3**. Sólo aparece la primera derivada; el 3 es el exponente.' },
        { t: 'mc', p: '¿Cuál es el orden y el grado de $\\dfrac{d^{2}y}{dx^{2}}+\\left(\\dfrac{dy}{dx}\\right)^{7}=x$?',
          o: ['Orden 2, grado 1', 'Orden 2, grado 7', 'Orden 7, grado 2', 'Orden 1, grado 7'], r: 0,
          x: 'La derivada más alta es la segunda, y está elevada a la $1$. El exponente 7 está sobre la primera derivada, que no es la que define el grado.' },
        { t: 'mc', p: 'En $y\'=-x\\,y$, ¿qué es lo que hay que encontrar?',
          o: ['Una función $y(x)$', 'Un número $x$', 'Un número $y$', 'La derivada de $y$'], r: 0,
          x: 'Resolver una ecuación diferencial es encontrar la función (o la familia de funciones) que la satisface.' },
        { t: 'ord', p: 'Ordená de menor a mayor orden',
          o: ['$y\'=x^{2}$', '$y\'\'+y=0$', '$y\'\'\'-2y\'=x$', '$\\dfrac{d^{4}y}{dx^{4}}=0$'],
          x: 'Basta contar las comillas (o el número de arriba en la notación de Leibniz).' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u1l2',
      titulo: 'Verificar una solución',
      objetivo: 'Comprobar si una función dada satisface la ecuación.',
      teoria: [
        { def: ['Solución', 'Una función $f$ es solución de una ecuación diferencial si, al reemplazar $y=f(x)$ **y sus derivadas** en la ecuación, la igualdad se cumple.'] },
        { p: 'Verificar es mecánico y no falla: derivás la candidata tantas veces como haga falta, la metés en la ecuación, y ves si los dos lados quedan iguales.' },
        { ej: ['¿Es $y=e^{\\frac{1}{3}x^{3}+C}$ solución de $\\dfrac{dy}{dx}=x^{2}y$?  — de la clase del 06/08', [
          'Derivo con la regla de la cadena: $y\'=e^{\\frac{1}{3}x^{3}+C}\\cdot\\left(\\dfrac{1}{3}\\cdot 3x^{2}\\right)$',
          'Simplifico: $y\'=x^{2}\\cdot e^{\\frac{1}{3}x^{3}+C}$',
          'Pero $e^{\\frac{1}{3}x^{3}+C}$ es justamente $y$. Entonces $y\'=x^{2}y$',
          'Coincide con la ecuación original: **sí es solución** ✓',
        ]] },
        { truco: 'Cuando la solución es una exponencial, casi siempre te va a quedar "la propia $y$" multiplicada por algo. Reconocer eso te ahorra media hoja de cuentas.' },
        { h: 'Por qué aparece siempre una constante' },
        { p: 'Resolver una ecuación diferencial implica integrar, y cada integración suelta un $+C$. Por eso el resultado no es una función sola sino una **familia de funciones**.' },
        { def: ['Solución general', 'La familia completa, con la constante $C$ (o $K$) sin determinar.'] },
        { def: ['Solución particular', 'Una sola de esas funciones, la que cumple además una **condición inicial** del tipo $y(x_0)=y_0$.'] },
        { ej: ['$\\dfrac{dy}{dx}=\\dfrac{x^{2}}{y^{2}}$ con $y(0)=2$  — de la clase del 30/07', [
          'Separando e integrando queda la solución general: $y^{3}=x^{3}+K$, o sea $y=\\sqrt[3]{x^{3}+K}$',
          'Ahora uso la condición: $x=0$, $y=2$',
          '$2=\\sqrt[3]{0+K} \\Rightarrow 2^{3}=K \\Rightarrow K=8$',
          'Solución particular: $y=\\sqrt[3]{x^{3}+8}$',
        ]] },
        { ojo: 'La condición inicial se reemplaza **en la solución general ya despejada**, no en la ecuación diferencial ni a mitad de camino.' },
      ],
      formulas: [
        ['Verificar', '\\text{derivar la candidata} \\to \\text{reemplazar} \\to \\text{comparar los dos lados}'],
        ['General vs particular', 'y = F(x, C) \;\\xrightarrow{\;y(x_0)=y_0\;}\; y = F(x, C_0)'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Cómo se comprueba que una función es solución de una ecuación diferencial?', fijo: true,
          o: ['Se derivan la función y se reemplazan ella y sus derivadas en la ecuación', 'Se integra la función y se compara', 'Se reemplaza $x$ por cero', 'Se despeja la constante'], r: 0,
          x: 'Reemplazás $y$, $y\'$, $y\'\'$... según lo que pida la ecuación, y verificás que los dos lados den lo mismo.' },
        { t: 'mc', p: 'Si $y=e^{\\frac{1}{3}x^{3}+C}$, ¿cuánto vale $y\'$?',
          o: ['$x^{2}\\,e^{\\frac{1}{3}x^{3}+C}$', '$e^{\\frac{1}{3}x^{3}+C}$', '$\\dfrac{1}{3}x^{3}e^{\\frac{1}{3}x^{3}+C}$', '$x^{2}$'], r: 0,
          x: 'Regla de la cadena: la exponencial se copia y se multiplica por la derivada del exponente, que es $\\frac{1}{3}\\cdot 3x^{2}=x^{2}$.' },
        { t: 'vf', p: '$y=e^{\\frac{1}{3}x^{3}+C}$ es solución de $\\dfrac{dy}{dx}=x^{2}y$.', r: true,
          x: 'Al derivar quedó $y\'=x^{2}e^{\\frac{1}{3}x^{3}+C}$, y esa exponencial es la propia $y$. Entonces $y\'=x^{2}y$ ✓' },
        { t: 'vf', p: '$y=x^{2}$ es solución de $y\'=2y$.', r: false,
          x: '$y\'=2x$, pero $2y=2x^{2}$. Como $2x \\neq 2x^{2}$, no es solución. La solución de $y\'=2y$ es $y=Ce^{2x}$.' },
        { t: 'mc', p: '¿Cuál es la diferencia entre solución general y particular?', fijo: true,
          o: ['La general tiene la constante sin determinar; la particular usa una condición inicial para fijarla', 'La general vale para todo $x$ y la particular sólo para algunos', 'La general es aproximada y la particular exacta', 'No hay diferencia, son sinónimos'], r: 0,
          x: 'La general es la familia entera de curvas; la condición inicial elige una sola de ellas.' },
        { t: 'in', p: 'La solución general es $y=\\sqrt[3]{x^{3}+K}$ y la condición es $y(0)=2$. ¿Cuánto vale $K$?', r: ['8'], ph: 'Un número',
          x: 'Reemplazo $x=0$, $y=2$: $2=\\sqrt[3]{K}$. Elevo al cubo los dos lados: $K=8$.' },
        { t: 'mc', p: 'Con $K=8$, ¿cuál es la solución particular?',
          o: ['$y=\\sqrt[3]{x^{3}+8}$', '$y=\\sqrt[3]{x^{3}}+8$', '$y=x^{3}+8$', '$y=\\sqrt[3]{x^{3}}+2$'], r: 0,
          x: 'Se reemplaza el valor hallado en la solución general, sin tocar el resto.' },
        { t: 'in', p: 'La solución general de $y\'=-xy$ es $y=e^{-\\frac{1}{2}x^{2}+C}$. Si $y(0)=1$, ¿cuánto vale $e^{C}$?', r: ['1'], ph: 'Un número',
          x: 'Con $x=0$: $1=e^{0+C}=e^{C}$. Entonces $e^{C}=1$ (y $C=0$). Queda $y=e^{-x^{2}/2}$.' },
        { t: 'ord', p: 'Ordená los pasos para hallar una solución particular',
          o: ['Resolver la ecuación diferencial', 'Despejar $y$ para obtener la solución general', 'Reemplazar los valores de la condición inicial', 'Despejar la constante', 'Escribir la solución general con la constante ya calculada'],
          x: 'La condición inicial se usa **al final**, sobre la solución general ya despejada.' },
        { t: 'vf', p: 'Una ecuación diferencial de primer orden tiene una sola solución.', r: false,
          x: 'Tiene infinitas: una por cada valor de la constante. Recién con una condición inicial se elige una.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u1l3',
      titulo: 'Reconocer el método',
      objetivo: 'Mirar una ecuación de primer orden y saber con qué método atacarla.',
      teoria: [
        { p: 'De acá en adelante vas a ver tres métodos para ecuaciones de primer orden. Perder tiempo con el método equivocado es el error más caro de un parcial, así que conviene tener el criterio claro **antes** de empezar a despejar.' },
        { h: 'El árbol de decisión' },
        { num: [
          '**¿Podés separar las $x$ de un lado y las $y$ del otro?** → **Variables separables** (unidad 2)',
          '**¿Se puede escribir como $\\dfrac{dy}{dx}+P(x)\\,y=Q(x)$?** → **Lineal** (unidad 3)',
          '**¿Está en la forma $M(x,y)dx+N(x,y)dy=0$ con $M$ y $N$ del mismo grado?** → **Homogénea** (unidad 4)',
        ] },
        { tabla: [['Ecuación', 'Método'], [
          ['$dx+e^{3x}dy=0$', 'Separables'],
          ['$\\dfrac{dy}{dx}=e^{(3x+2y)}$', 'Separables'],
          ['$x\\dfrac{dy}{dx}-4y=x^{6}e^{x}$', 'Lineal'],
          ['$\\dfrac{dy}{dx}-3y=6$', 'Lineal'],
          ['$(y^{2}-x^{2})dx-2xy\\,dy=0$', 'Homogénea'],
          ['$(x^{2}+2y^{2})\\dfrac{dx}{dy}=xy$', 'Homogénea'],
        ]] },
        { truco: 'Una exponencial como $e^{3x+2y}$ **parece** que mezcla todo, pero por propiedad de potencias $e^{3x+2y}=e^{3x}\\cdot e^{2y}$: se separa perfecto. Ese es un clásico del cuadernillo.' },
        { def: ['Grado de un término', 'La suma de los exponentes de $x$ e $y$. En $x^{2}$ el grado es 2, en $xy$ también es 2, y en $y^{2}$ igual. Por eso $(x^{2}+2y^{2})$ y $xy$ son del mismo grado y la ecuación es homogénea.'] },
        { ojo: 'La palabra "homogénea" se usa con **dos sentidos distintos** en la materia. Acá, en primer orden, significa que $M$ y $N$ tienen el mismo grado. En segundo orden (unidad 5) significa que el lado derecho vale cero. No son lo mismo.' },
        { h: 'Una duda frecuente' },
        { p: 'Si una ecuación entra en más de una categoría, resolvela por el método **más simple** que la contenga. $\\dfrac{dy}{dx}=-xy$ es separable y también lineal; por separables sale en tres renglones.' },
      ],
      formulas: [
        ['Separables', '\\frac{dy}{dx}=g(x)\\cdot h(y)'],
        ['Lineales', '\\frac{dy}{dx}+P(x)\\,y = Q(x)'],
        ['Homogéneas', 'M(x,y)\\,dx + N(x,y)\\,dy = 0 \\quad (\\text{mismo grado})'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Qué método usarías para $\\dfrac{dy}{dx}=\\dfrac{x^{2}}{y^{2}}$?',
          o: ['Variables separables', 'Lineal', 'Homogénea', 'Por partes'], r: 0,
          x: 'Pasás $y^{2}$ multiplicando y $dx$ también: $y^{2}dy=x^{2}dx$. Todo lo de $y$ de un lado y lo de $x$ del otro.' },
        { t: 'mc', p: '¿Y para $x\\dfrac{dy}{dx}-4y=x^{6}e^{x}$?',
          o: ['Lineal', 'Variables separables', 'Homogénea', 'Bernoulli'], r: 0,
          x: 'Dividiendo todo por $x$ queda $\\frac{dy}{dx}-\\frac{4}{x}y=x^{5}e^{x}$, que es exactamente la forma estándar $y\'+P(x)y=Q(x)$.' },
        { t: 'mc', p: '¿Y para $(y^{2}-x^{2})dx-2xy\\,dy=0$?',
          o: ['Homogénea', 'Variables separables', 'Lineal', 'De segundo orden'], r: 0,
          x: 'Está en la forma $M\\,dx+N\\,dy=0$, y todos los términos ($y^{2}$, $x^{2}$, $xy$) son de grado 2. Mismo grado = homogénea.' },
        { t: 'mc', p: '$\\dfrac{dy}{dx}=e^{(3x+2y)}$. ¿Es separable?',
          o: ['Sí, porque $e^{3x+2y}=e^{3x}\\cdot e^{2y}$', 'No, porque $x$ e $y$ están sumadas', 'Sí, porque las exponenciales siempre se separan', 'No, hay que usar el método lineal'], r: 0,
          x: 'Propiedad de potencias: $a^{m+n}=a^{m}\\cdot a^{n}$. Eso convierte una suma en el exponente en un producto, y el producto sí se separa.' },
        { t: 'par', p: 'Emparejá cada ecuación con su método',
          o: [['$dx+e^{3x}dy=0$', 'Separables'], ['$\\dfrac{dy}{dx}-3y=6$', 'Lineal'], ['$(x^{2}+2y^{2})dx=xy\\,dy$', 'Homogénea'], ['$y\'\'+y=0$', 'Segundo orden']],
          x: 'El truco es mirar la forma, no los números: ¿se separa? ¿está en forma estándar? ¿mismo grado?' },
        { t: 'in', p: '¿Cuál es el grado del término $xy$?', r: ['2'], ph: 'Un número',
          x: 'Se suman los exponentes: $x^{1}y^{1}$ da $1+1=2$. Por eso $xy$ convive con $x^{2}$ y con $y^{2}$ en una homogénea.' },
        { t: 'vf', p: 'En primer orden, "homogénea" significa que el lado derecho de la ecuación vale cero.', r: false,
          x: 'Eso es en **segundo orden**. En primer orden significa que $M$ y $N$ tienen el mismo grado. Es la misma palabra para dos cosas distintas.' },
        { t: 'mc', p: '$\\dfrac{dy}{dx}=-xy$ se puede resolver por separables y también por lineal. ¿Qué conviene?',
          o: ['Separables, porque es más corto', 'Lineal, porque es más general', 'Cualquiera, dan resultados distintos', 'Ninguno: hay que usar homogéneas'], r: 0,
          x: 'Los dos métodos dan la misma solución, pero separables sale en tres renglones y lineal te obliga a calcular el factor de integración.' },
        { t: 'ord', p: 'Ordená el criterio de decisión para una ecuación de primer orden',
          o: ['¿Se pueden separar las variables?', '¿Se puede llevar a la forma $y\'+P(x)y=Q(x)$?', '¿Es $M\\,dx+N\\,dy=0$ con $M$ y $N$ del mismo grado?', 'Si no entra en ninguna, revisar si es de Bernoulli'],
          x: 'Siempre de lo más simple a lo más general: si es separable, no hace falta ir más lejos.' },
      ],
    },
  ],
});
