/* Unidad 2 — Variables separables
   Guía 1 del cuadernillo (pág. 6 y 8) + clases del 30/07 y 06/08. */
(window.__UNIDADES = window.__UNIDADES || []).push({
  id: 'u2',
  n: 2,
  titulo: 'Variables separables',
  glifo: '⇄',
  resumen: 'Cada variable de su lado, integrar los dos miembros y despejar. El método más usado.',
  lecciones: [

    /* ------------------------------------------------------------------ */
    {
      id: 'u2l1',
      titulo: 'Separar e integrar',
      objetivo: 'Llevar cada variable a su lado del igual y resolver.',
      teoria: [
        { def: ['Forma', 'Son las que se pueden escribir como $$\\frac{dy}{dx}=g(x)\\cdot h(y)$$ es decir, un producto de algo que sólo depende de $x$ por algo que sólo depende de $y$.'] },
        { p: 'La idea es tratar a $\\dfrac{dy}{dx}$ como si fuera una fracción común (no lo es, pero acá funciona) y mandar todo lo de $y$ a la izquierda y todo lo de $x$ a la derecha. Después se integran **los dos miembros**.' },
        { h: 'El método' },
        { num: ['Separar: todo lo de $y$ con $dy$, todo lo de $x$ con $dx$', 'Integrar ambos lados', 'Despejar $y$'] },
        { ej: ['$dx+e^{3x}dy=0$  — ejercicio 1 de la página 8', [
          'Paso el $dx$: $\;e^{3x}dy = -dx$',
          'Separo: $\;dy = \\dfrac{-dx}{e^{3x}}$, o sea $\;1\\,dy = -e^{-3x}dx$',
          'Integro los dos lados: $\\displaystyle\\int 1\\,dy = -\\displaystyle\\int e^{-3x}dx$',
          'La de la derecha sale por sustitución (o con el atajo $\\int e^{kx}=\\frac{1}{k}e^{kx}$): $-\\left(-\\dfrac{1}{3}e^{-3x}\\right)$',
          'Solución general: $\;y=\\dfrac{1}{3}e^{-3x}+C$',
        ]] },
        { truco: 'Del lado que queda "pelado" se escribe $\\int 1\\,dy$, que da simplemente $y$. Mucha gente se olvida ese lado y se come la incógnita.' },
        { ej: ['$x\\dfrac{dy}{dx}=4y$  — ejercicio 3 de la página 8', [
          'Separo: $\;\\dfrac{dy}{4y}=\\dfrac{dx}{x}$',
          'Integro: $\;\\dfrac{1}{4}\\displaystyle\\int\\dfrac{1}{y}dy=\\displaystyle\\int\\dfrac{1}{x}dx$',
          '$\;\\dfrac{1}{4}\\ln|y| = \\ln|x|+C$',
          'Multiplico todo por 4: $\;\\ln|y| = 4\\ln|x|+4C$',
        ]] },
        { ojo: 'Sólo hace falta **una** constante, y va de un solo lado. Si ponés $C_1$ y $C_2$ terminás arrastrando una resta de constantes que es, otra vez, una constante.' },
        { p: 'Un caso que engaña: cuando en el exponente hay una suma de $x$ e $y$, se separa igual usando propiedades de potencias.' },
        { ej: ['$\\dfrac{dy}{dx}=e^{(3x+2y)}$  — ejercicio 2 de la página 8', [
          'Uso $a^{m+n}=a^{m}\\cdot a^{n}$: $\;\\dfrac{dy}{dx}=e^{3x}\\cdot e^{2y}$',
          'Ahora sí separa: $\;\\dfrac{dy}{e^{2y}}=e^{3x}dx$, o sea $\;e^{-2y}dy=e^{3x}dx$',
          'Integro: $\;-\\dfrac{1}{2}e^{-2y}=\\dfrac{1}{3}e^{3x}+C$',
        ]] },
      ],
      formulas: [
        ['Forma separable', '\\frac{dy}{dx}=g(x)\\cdot h(y)'],
        ['Separada e integrada', '\\int \\frac{dy}{h(y)} = \\int g(x)\\,dx'],
        ['Propiedad clave', 'a^{m+n}=a^{m}\\cdot a^{n}'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Cuál es la forma de una ecuación de variables separables?',
          o: ['$\\dfrac{dy}{dx}=g(x)\\cdot h(y)$', '$\\dfrac{dy}{dx}+P(x)y=Q(x)$', '$M(x,y)dx+N(x,y)dy=0$', '$ay\'\'+by\'+cy=0$'], r: 0,
          x: 'Un producto de una función de $x$ por una función de $y$. Eso es lo que permite mandar cada una a su lado.' },
        { t: 'ord', p: 'Ordená el método de variables separables',
          o: ['Separar: lo de $y$ con $dy$, lo de $x$ con $dx$', 'Integrar los dos miembros', 'Sumar la constante $C$ de un solo lado', 'Despejar $y$'],
          x: 'Con una sola constante alcanza: la diferencia de dos constantes vuelve a ser una constante.' },
        { t: 'mc', p: 'Separá $dx+e^{3x}dy=0$',
          o: ['$1\\,dy = -e^{-3x}dx$', '$e^{3x}dy = dx$', '$dy = e^{3x}dx$', '$\\dfrac{dy}{dx}=e^{3x}$'], r: 0,
          x: 'Pasás $dx$ restando y dividís por $e^{3x}$. Dividir por $e^{3x}$ es lo mismo que multiplicar por $e^{-3x}$.' },
        { t: 'mc', p: 'Resolvé $dx+e^{3x}dy=0$',
          o: ['$y=\\dfrac{1}{3}e^{-3x}+C$', '$y=-\\dfrac{1}{3}e^{-3x}+C$', '$y=\\dfrac{1}{3}e^{3x}+C$', '$y=3e^{-3x}+C$'], r: 0,
          x: '$-\\int e^{-3x}dx = -\\left(-\\frac{1}{3}e^{-3x}\\right)=\\frac{1}{3}e^{-3x}$. Los dos signos menos se cancelan.' },
        { t: 'mc', p: '$\\dfrac{dy}{dx}=e^{(3x+2y)}$. ¿Cómo queda después de separar?',
          o: ['$e^{-2y}dy=e^{3x}dx$', '$e^{2y}dy=e^{3x}dx$', '$dy=e^{3x+2y}dx$', '$\\dfrac{dy}{2y}=3x\\,dx$'], r: 0,
          x: 'Primero $e^{3x+2y}=e^{3x}e^{2y}$, después dividís por $e^{2y}$, que es multiplicar por $e^{-2y}$.' },
        { t: 'hue', p: 'Separá $x\\dfrac{dy}{dx}=4y$', tpl: '$\\dfrac{dy}{4y} = \\dfrac{dx}{$ ___ $}$', r: [['x']],
          x: 'Pasás $x$ dividiendo y $4y$ dividiendo. Queda cada variable de su lado.' },
        { t: 'mc', p: 'Al integrar $\\displaystyle\\int\\dfrac{dy}{4y}$ obtenés',
          o: ['$\\dfrac{1}{4}\\ln|y|$', '$4\\ln|y|$', '$\\ln|4y|$', '$\\dfrac{1}{4y^{2}}$'], r: 0,
          x: 'El $\\frac{1}{4}$ es constante y sale afuera de la integral. Adentro queda $\\int\\frac{1}{y}dy=\\ln|y|$.' },
        { t: 'in', p: 'Al separar $\\dfrac{dy}{dx}=\\dfrac{x^{2}}{y^{2}}$ e integrar, queda $\\dfrac{y^{3}}{3}=\\dfrac{x^{3}}{k}+C$. ¿Cuánto vale $k$?', r: ['3'], ph: 'Un número',
          x: 'Separás a $y^{2}dy=x^{2}dx$ y las dos integrales dan lo mismo: $\\frac{y^{3}}{3}=\\frac{x^{3}}{3}+C$.' },
        { t: 'vf', p: 'Al integrar los dos miembros hay que poner una constante de cada lado.', r: false,
          x: 'Con una alcanza. Si ponés $C_1$ a la izquierda y $C_2$ a la derecha, al pasarlas juntas te queda $C_2-C_1$, que es una sola constante nueva.' },
        { t: 'mc', p: 'Resolvé $\\dfrac{dy}{dx}=-xy$ (solución general)',
          o: ['$y=e^{-\\frac{1}{2}x^{2}+C}$', '$y=e^{-x^{2}+C}$', '$y=-\\dfrac{1}{2}x^{2}+C$', '$y=e^{\\frac{1}{2}x^{2}+C}$'], r: 0,
          x: 'Separás: $\\frac{dy}{y}=-x\\,dx$, integrás: $\\ln|y|=-\\frac{x^{2}}{2}+C$, y aplicás exponencial a los dos lados.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u2l2',
      titulo: 'Despejar la y',
      objetivo: 'Sacarse el logaritmo de encima sin perder constantes por el camino.',
      teoria: [
        { p: 'Casi siempre, después de integrar te queda un $\\ln|y|$ de un lado. Para despejar $y$ hay que **aplicar la exponencial a los dos miembros**, y ahí aparecen las propiedades que la profe repite en cada clase.' },
        { h: 'Las propiedades que se usan' },
        { tabla: [['Propiedad', 'Para qué sirve'], [
          ['$\\log_a b = c \\iff a^{c}=b$', 'Definición de logaritmo'],
          ['$e^{\\ln a}=a$', 'Sacarse el logaritmo de encima'],
          ['$a^{m+n}=a^{m}\\cdot a^{n}$', 'Partir el exponente en dos'],
          ['$\\log_a b^{m}=m\\cdot\\log_a b$', 'Bajar un exponente'],
          ['$\\log_a(b\\cdot c)=\\log_a b+\\log_a c$', 'Juntar o separar logaritmos'],
          ['$\\log_a\\left(\\frac{b}{c}\\right)=\\log_a b-\\log_a c$', 'Idem con cocientes'],
        ]] },
        { ej: ['Terminar $\\ln|y|=-\\dfrac{1}{2}x^{2}+C$', [
          'Aplico exponencial a los dos lados: $\;e^{\\ln|y|}=e^{-\\frac{1}{2}x^{2}+C}$',
          'A la izquierda, $e^{\\ln|y|}=y$',
          'Solución general: $\;y=e^{-\\frac{1}{2}x^{2}+C}$',
          'Si querés separarla: $\;y=e^{-\\frac{1}{2}x^{2}}\\cdot e^{C}$, y como $e^{C}$ es una constante, se la llama $K$: $\;y=K\\,e^{-\\frac{1}{2}x^{2}}$',
        ]] },
        { truco: '$e^{C}$ es una constante nueva. Renombrala $K$ y listo: $e^{C}=K$. Queda todo mucho más limpio y es lo que se hace en clase.' },
        { ej: ['Terminar $\\dfrac{1}{4}\\ln|y|=\\ln|x|+C$  — el ejercicio 3 de la página 8', [
          'Multiplico todo por 4: $\;\\ln|y|=4\\ln|x|+4C$',
          'Uso $m\\log b=\\log b^{m}$ a la izquierda del $4$: $\;\\ln|y|=\\ln|x|^{4}+4C$',
          'Exponencial a los dos lados: $\;y=e^{\\ln|x|^{4}+4C}=e^{\\ln|x|^{4}}\\cdot e^{4C}$',
          'Y como $e^{\\ln a}=a$: $\;y=|x|^{4}\\cdot e^{4C}$, o sea $\;y=K\\,x^{4}$',
        ]] },
        { ojo: 'No te olvides de multiplicar **todo** el otro lado por el mismo número. Si multiplicás por 4 la izquierda, la constante también pasa a ser $4C$ (que después renombrás igual).' },
        { h: 'Cuando no se puede despejar' },
        { p: 'A veces el cuadernillo pide directamente "dejar expresada la solución en forma implícita". Ahí no hace falta despejar: alcanza con dejar la igualdad entre las dos primitivas.' },
      ],
      formulas: [
        ['Definición', '\\log_a b = c \\iff a^{c}=b'],
        ['Cancelar', 'e^{\\ln a}=a \\qquad \\ln(e^{a})=a'],
        ['Partir exponente', 'e^{m+n}=e^{m}\\cdot e^{n}'],
        ['Bajar exponente', '\\ln(b^{m})=m\\ln b'],
        ['Renombrar', 'e^{C}=K'],
      ],
      ejercicios: [
        { t: 'mc', p: 'Para despejar $y$ de $\\ln|y|=f(x)+C$, ¿qué hacés?',
          o: ['Aplico exponencial a los dos miembros', 'Derivo los dos miembros', 'Divido por $\\ln$', 'Paso el $\\ln$ multiplicando'], r: 0,
          x: 'La exponencial es la función inversa del logaritmo natural: $e^{\\ln|y|}=y$.' },
        { t: 'mc', p: '$\\ln|y|=-\\dfrac{1}{2}x^{2}+C$. Despejá $y$.',
          o: ['$y=e^{-\\frac{1}{2}x^{2}+C}$', '$y=-\\dfrac{1}{2}x^{2}+e^{C}$', '$y=\\ln\\left(-\\dfrac{1}{2}x^{2}+C\\right)$', '$y=e^{-\\frac{1}{2}x^{2}}+C$'], r: 0,
          x: 'La exponencial se aplica a **todo** el miembro derecho, con constante incluida. La última opción es el error clásico: dejar el $+C$ afuera.' },
        { t: 'mc', p: '$y=e^{-\\frac{1}{2}x^{2}+C}$ también se escribe como',
          o: ['$y=K\\,e^{-\\frac{1}{2}x^{2}}$', '$y=e^{-\\frac{1}{2}x^{2}}+K$', '$y=K-\\dfrac{1}{2}x^{2}$', '$y=e^{K}-\\dfrac{1}{2}x^{2}$'], r: 0,
          x: 'Partís el exponente con $e^{m+n}=e^{m}e^{n}$ y renombrás $e^{C}=K$.' },
        { t: 'par', p: 'Emparejá cada propiedad con su resultado',
          o: [['$e^{\\ln 7}$', '$7$'], ['$\\ln(e^{5})$', '$5$'], ['$e^{a+b}$', '$e^{a}\\cdot e^{b}$'], ['$\\ln(x^{4})$', '$4\\ln x$']],
          x: 'Estas cuatro resuelven el 90 % de los despejes de la materia.' },
        { t: 'in', p: 'Si $\\dfrac{1}{4}\\ln|y|=\\ln|x|+C$, al multiplicar todo por 4 el coeficiente de $\\ln|x|$ pasa a ser', r: ['4'], ph: 'Un número',
          x: 'Queda $\\ln|y|=4\\ln|x|+4C$. Hay que multiplicar todos los términos, también la constante.' },
        { t: 'mc', p: 'Terminá de despejar $\\ln|y|=4\\ln|x|+4C$',
          o: ['$y=K\\,x^{4}$', '$y=4x+K$', '$y=x^{4}+K$', '$y=4\\ln|x|+K$'], r: 0,
          x: '$4\\ln|x|=\\ln|x|^{4}$, entonces $y=e^{\\ln|x|^{4}}\\cdot e^{4C}=|x|^{4}\\cdot K$.' },
        { t: 'vf', p: '$e^{C}$ se puede renombrar como una constante nueva $K$.', r: true,
          x: 'Sí, y conviene: $e^{C}$ es un número fijo, así que no aporta nada arrastrar la exponencial toda la cuenta.' },
        { t: 'mc', p: '$-\\dfrac{1}{2}e^{-2y}=\\dfrac{1}{3}e^{3x}+C$. ¿Cuál es el primer paso para despejar $y$?',
          o: ['Multiplicar los dos miembros por $-2$', 'Aplicar logaritmo', 'Derivar', 'Pasar $C$ restando'], r: 0,
          x: 'Primero te sacás el $-\\frac{1}{2}$ que multiplica a la exponencial. Recién cuando quede $e^{-2y}$ solo conviene aplicar el logaritmo.' },
        { t: 'mc', p: '¿Cuál de estas igualdades es FALSA?', fijo: true,
          o: ['$\\ln(a+b)=\\ln a+\\ln b$', '$\\ln(a\\cdot b)=\\ln a+\\ln b$', '$\\ln\\left(\\dfrac{a}{b}\\right)=\\ln a-\\ln b$', '$\\ln(a^{m})=m\\ln a$'], r: 0,
          x: 'El logaritmo de una **suma** no se parte. Sólo se parten productos, cocientes y potencias. Es el error más común de la materia.' },
        { t: 'in', p: '¿Cuánto vale $e^{\\ln 12}$?', r: ['12'], ph: 'Un número',
          x: 'La exponencial y el logaritmo natural se cancelan: $e^{\\ln a}=a$.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u2l3',
      titulo: 'Condición inicial',
      objetivo: 'Pasar de la solución general a la particular.',
      teoria: [
        { p: 'Una **condición inicial** es un dato del tipo $y(0)=1$: "cuando $x$ vale $0$, $y$ vale $1$". Sirve para calcular el valor exacto de la constante.' },
        { num: ['Resolver y despejar hasta tener la solución general', 'Reemplazar el par de valores que da la condición', 'Despejar la constante', 'Escribirla de nuevo en la solución general'] },
        { ej: ['$dx+e^{3x}dy=0$ con $y(0)=1$  — de la clase del 06/08', [
          'Solución general (ya la calculamos): $\;y=\\dfrac{1}{3}e^{-3x}+C$',
          'La condición dice $x=0$, $y=1$. Reemplazo:',
          '$\;1=\\dfrac{1}{3}e^{-3\\cdot 0}+C = \\dfrac{1}{3}e^{0}+C=\\dfrac{1}{3}+C$',
          'Despejo: $\;C=1-\\dfrac{1}{3}=\\dfrac{2}{3}$',
          'Solución particular: $\;y=\\dfrac{1}{3}e^{-3x}+\\dfrac{2}{3}$',
        ]] },
        { truco: 'Casi siempre la condición es en $x=0$, y eso es buenísimo: $e^{0}=1$ y cualquier término con $x$ se va. Reemplazá y fijate cuánto se simplifica antes de ponerte a hacer cuentas.' },
        { ej: ['$\\dfrac{dy}{dx}=\\dfrac{x^{2}}{y^{2}}$ con $y(0)=2$  — de la clase del 30/07', [
          'Separo: $\;y^{2}dy=x^{2}dx$',
          'Integro: $\;\\dfrac{y^{3}}{3}=\\dfrac{x^{3}}{3}+C$',
          'Multiplico por 3: $\;y^{3}=x^{3}+3C$. Renombro $3C=K$: $\;y^{3}=x^{3}+K$',
          'Solución general: $\;y=\\sqrt[3]{x^{3}+K}$',
          'Reemplazo $x=0$, $y=2$: $\;2=\\sqrt[3]{K}$, entonces $K=8$',
          'Solución particular: $\;y=\\sqrt[3]{x^{3}+8}$',
        ]] },
        { ojo: 'Cuando hay una raíz o una potencia, despejá la constante **elevando o sacando raíz a los dos lados**. Un error de signo o de índice acá te arruina todo el ejercicio, aunque la parte de integrar esté perfecta.' },
      ],
      formulas: [
        ['Condición inicial', 'y(x_0)=y_0 \;\\Rightarrow\; \\text{reemplazar y despejar } C'],
        ['Valor útil', 'e^{0}=1'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Qué significa la condición inicial $y(0)=2$?',
          o: ['Que cuando $x=0$, la función vale $2$', 'Que la derivada en $0$ vale $2$', 'Que la constante vale $2$', 'Que la solución empieza en $2$ y crece'], r: 0,
          x: 'Es un punto por el que pasa la curva: el par $(0,\\,2)$.' },
        { t: 'mc', p: '¿En qué momento se usa la condición inicial?', fijo: true,
          o: ['Al final, sobre la solución general ya despejada', 'Al principio, antes de separar', 'Justo después de integrar, antes de despejar', 'Nunca, es un dato de control'], r: 0,
          x: 'Primero se resuelve todo, después se reemplaza. Si la metés antes, arrastrás números por toda la cuenta sin necesidad.' },
        { t: 'in', p: 'La solución general es $y=\\dfrac{1}{3}e^{-3x}+C$ y la condición es $y(0)=1$. ¿Cuánto vale $C$?', r: ['2/3'], ph: 'Una fracción', teclas: ['/'],
          x: 'Con $x=0$: $1=\\frac{1}{3}e^{0}+C=\\frac{1}{3}+C$. Entonces $C=1-\\frac{1}{3}=\\frac{2}{3}$.' },
        { t: 'mc', p: '¿Cuál es entonces la solución particular?',
          o: ['$y=\\dfrac{1}{3}e^{-3x}+\\dfrac{2}{3}$', '$y=\\dfrac{2}{3}e^{-3x}+\\dfrac{1}{3}$', '$y=\\dfrac{1}{3}e^{-3x}$', '$y=e^{-3x}+\\dfrac{2}{3}$'], r: 0,
          x: 'Se reemplaza el valor de $C$ en la general, sin tocar nada más.' },
        { t: 'in', p: '¿Cuánto vale $e^{-3\\cdot 0}$?', r: ['1'], ph: 'Un número',
          x: 'Cualquier base elevada a $0$ da $1$. Por eso las condiciones en $x=0$ simplifican tanto.' },
        { t: 'in', p: 'De $y^{3}=x^{3}+K$ con $y(0)=2$, ¿cuánto vale $K$?', r: ['8'], ph: 'Un número',
          x: 'Reemplazo: $2^{3}=0^{3}+K$, o sea $8=K$.' },
        { t: 'mc', p: 'De $y=e^{\\frac{1}{3}x^{3}+C}$ con $y(0)=2$, ¿cuánto vale $e^{C}$?',
          o: ['$2$', '$\\ln 2$', '$0$', '$e^{2}$'], r: 0,
          x: 'Con $x=0$: $2=e^{0+C}=e^{C}$. Conviene dejarlo así, sin pasar a $C=\\ln 2$: la solución queda $y=2e^{x^{3}/3}$.' },
        { t: 'ord', p: 'Ordená los pasos con condición inicial',
          o: ['Separar variables', 'Integrar los dos miembros', 'Despejar $y$ (solución general)', 'Reemplazar la condición inicial', 'Despejar la constante y escribir la solución particular'],
          x: 'La condición es siempre el anteúltimo paso, nunca antes de tener la general.' },
        { t: 'vf', p: 'Si la ecuación no trae condición inicial, la respuesta se deja con la constante $C$.', r: true,
          x: 'Sí: esa es la solución general, y es una respuesta completa. Sin un dato extra no hay forma de fijar la constante.' },
        { t: 'mc', p: 'La solución general de $\\dfrac{dy}{dx}=x^{2}y$ es $y=e^{\\frac{1}{3}x^{3}+C}$. Con $y(0)=2$, la particular es',
          o: ['$y=2\\,e^{\\frac{1}{3}x^{3}}$', '$y=e^{\\frac{1}{3}x^{3}+2}$', '$y=e^{\\frac{1}{3}x^{3}}+2$', '$y=2+\\dfrac{1}{3}x^{3}$'], r: 0,
          x: 'Como $e^{C}=2$, partís el exponente: $y=e^{x^{3}/3}\\cdot e^{C}=2e^{x^{3}/3}$.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u2l4',
      titulo: 'Separables con trigonométricas',
      objetivo: 'Resolver los casos que piden un reemplazo trigonométrico antes de separar.',
      teoria: [
        { p: 'Algunos ejercicios del cuadernillo no separan **hasta que usás una identidad trigonométrica**. El aviso está en la propia guía: "recordar reemplazo trigonométrico".' },
        { h: 'Las identidades que hacen falta' },
        { tabla: [['Identidad', 'Para qué sirve'], [
          ['$\\sen(2x)=2\\,\\sen x\\cos x$', 'Partir un ángulo doble'],
          ['$\\cos(2x)=\\cos^{2}x-\\sen^{2}x$', 'Ídem'],
          ['$\\sen^{2}x+\\cos^{2}x=1$', 'Cambiar senos por cosenos'],
          ['$\\tg x=\\dfrac{\\sen x}{\\cos x}$', 'Convertir a senos y cosenos'],
        ]] },
        { ej: ['$\\dfrac{dy}{dx}=\\sen(2x)\\cdot y$ (con la idea del ejercicio 7)', [
          'A simple vista ya separa: $\;\\dfrac{dy}{y}=\\sen(2x)\\,dx$',
          'Integro la izquierda: $\;\\ln|y|$',
          'La derecha, con sustitución $u=2x$: $\;-\\dfrac{1}{2}\\cos(2x)$',
          'Queda $\;\\ln|y|=-\\dfrac{1}{2}\\cos(2x)+C$',
          'Y despejo: $\;y=K\\,e^{-\\frac{1}{2}\\cos(2x)}$',
        ]] },
        { truco: 'Cuando aparece $\\sen(2x)$ **multiplicando**, en general conviene dejarlo así y usar sustitución. La identidad $2\\sen x\\cos x$ sirve cuando el $\\sen(2x)$ está **dividiendo** o mezclado con $\\sen x$ o $\\cos x$ sueltos: ahí simplifica.' },
        { h: 'Integrales trigonométricas que vas a necesitar' },
        { tabla: [['Integral', 'Resultado'], [
          ['$\\int \\sen(kx)\\,dx$', '$-\\dfrac{1}{k}\\cos(kx)+C$'],
          ['$\\int \\cos(kx)\\,dx$', '$\\dfrac{1}{k}\\sen(kx)+C$'],
          ['$\\int \\tg x\\,dx$', '$-\\ln|\\cos x|+C$'],
          ['$\\int \\dfrac{dx}{\\cos^{2}x}$', '$\\tg x+C$'],
        ]] },
        { ojo: 'El signo menos de $\\int\\sen$ se pierde todo el tiempo. Si tu resultado da distinto al del profesor sólo en un signo, empezá revisando ahí.' },
      ],
      formulas: [
        ['Ángulo doble', '\\sen(2x)=2\\,\\sen x\\,\\cos x'],
        ['Pitágoras', '\\sen^{2}x+\\cos^{2}x=1'],
        ['Integral del seno', '\\int \\sen(kx)\\,dx=-\\frac{1}{k}\\cos(kx)+C'],
        ['Integral del coseno', '\\int \\cos(kx)\\,dx=\\frac{1}{k}\\sen(kx)+C'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿A qué equivale $\\sen(2x)$?',
          o: ['$2\\,\\sen x\\cos x$', '$2\\,\\sen x$', '$\\sen^{2}x$', '$\\sen x+\\sen x$'], r: 0,
          x: 'Es la identidad del ángulo doble. Sirve para simplificar cuando conviven $\\sen(2x)$ y $\\sen x$ o $\\cos x$ sueltos.' },
        { t: 'mc', p: 'Resolvé $\\int \\sen(2x)\\,dx$',
          o: ['$-\\dfrac{1}{2}\\cos(2x)+C$', '$\\dfrac{1}{2}\\cos(2x)+C$', '$-2\\cos(2x)+C$', '$-\\cos(2x)+C$'], r: 0,
          x: 'Dos cosas: la primitiva del seno lleva menos, y hay que dividir por el $2$ del argumento.' },
        { t: 'mc', p: 'Resolvé $\\int \\cos(5x)\\,dx$',
          o: ['$\\dfrac{1}{5}\\sen(5x)+C$', '$-\\dfrac{1}{5}\\sen(5x)+C$', '$5\\,\\sen(5x)+C$', '$\\sen(5x)+C$'], r: 0,
          x: 'La del coseno no lleva menos. Sólo hay que dividir por el $5$.' },
        { t: 'hue', p: 'Separá $\\dfrac{dy}{dx}=\\sen(2x)\\cdot y$', tpl: '$\\dfrac{dy}{$ ___ $} = \\sen(2x)\\,dx$', r: [['y']],
          x: 'La $y$ pasa dividiendo al lado izquierdo, junto con $dy$.' },
        { t: 'mc', p: 'Resolvé $\\dfrac{dy}{dx}=\\sen(2x)\\cdot y$',
          o: ['$y=K\\,e^{-\\frac{1}{2}\\cos(2x)}$', '$y=K\\,e^{\\frac{1}{2}\\cos(2x)}$', '$y=-\\dfrac{1}{2}\\cos(2x)+C$', '$y=K\\,\\sen(2x)$'], r: 0,
          x: 'Queda $\\ln|y|=-\\frac{1}{2}\\cos(2x)+C$ y después exponencial a los dos lados.' },
        { t: 'par', p: 'Emparejá cada integral con su resultado',
          o: [['$\\int \\sen x\\,dx$', '$-\\cos x+C$'], ['$\\int \\cos x\\,dx$', '$\\sen x+C$'], ['$\\int \\tg x\\,dx$', '$-\\ln|\\cos x|+C$'], ['$\\int \\dfrac{dx}{\\cos^{2}x}$', '$\\tg x+C$']],
          x: 'Las dos primeras son de tabla; la tercera sale por sustitución con $u=\\cos x$.' },
        { t: 'vf', p: '$\\sen^{2}x+\\cos^{2}x=1$', r: true,
          x: 'La identidad pitagórica. Sirve para cambiar todo a senos o todo a cosenos cuando la ecuación no separa.' },
        { t: 'mc', p: '$\\tg x$ escrito con senos y cosenos es',
          o: ['$\\dfrac{\\sen x}{\\cos x}$', '$\\dfrac{\\cos x}{\\sen x}$', '$\\sen x\\cdot\\cos x$', '$\\sen x-\\cos x$'], r: 0,
          x: 'Convertir la tangente a este cociente suele ser lo que destraba la separación de variables.' },
        { t: 'in', p: 'En $\\int \\sen(7x)\\,dx = k\\cos(7x)+C$, ¿cuánto vale $k$?', r: ['-1/7'], ph: 'Ojo con el signo', teclas: ['-', '/'],
          x: 'El menos de la primitiva del seno más el $\\frac{1}{7}$ de dividir por el argumento.' },
      ],
    },
  ],
});
