/* Unidad 3 — Ecuaciones diferenciales lineales de primer orden + Bernoulli
   Guía 1 del cuadernillo (pág. 7) + clases del 30/07 y 06/08. */
(window.__UNIDADES = window.__UNIDADES || []).push({
  id: 'u3',
  n: 3,
  titulo: 'Lineales y Bernoulli',
  glifo: 'μ',
  resumen: 'Forma estándar, factor de integración y la sustitución que salva a Bernoulli.',
  lecciones: [

    /* ------------------------------------------------------------------ */
    {
      id: 'u3l1',
      titulo: 'Forma estándar y factor de integración',
      objetivo: 'Reconocer una lineal y construir el factor que la resuelve.',
      teoria: [
        { def: ['Forma estándar', 'Una ecuación es **lineal de primer orden** si se puede escribir como $$\\frac{dy}{dx}+P(x)\\,y = Q(x)$$ con $P$ y $Q$ funciones continuas de $x$ solamente.'] },
        { ojo: 'El coeficiente de $\\dfrac{dy}{dx}$ **debe ser 1**. Si la ecuación viene como $x\\dfrac{dy}{dx}-4y=x^{6}e^{x}$, lo primero es dividir todo por $x$.' },
        { h: '¿Por qué no alcanza con separar?' },
        { p: 'Porque en $\\dfrac{dy}{dx}+P(x)y=Q(x)$ la $y$ aparece de dos maneras distintas y no hay forma de juntarla de un solo lado. El truco es **multiplicar toda la ecuación por una función especial** que convierta el lado izquierdo en la derivada de un producto.' },
        { def: ['Factor de integración', '$$I(x)=e^{\\int P(x)\\,dx}$$ Se calcula con el $P(x)$ de la forma estándar, y **sin sumarle constante**.'] },
        { p: 'La magia es que, al multiplicar por $I(x)$, el lado izquierdo se convierte exactamente en $\\big(I(x)\\cdot y\\big)\'$. Y como integrar una derivada devuelve la función original, el problema se derrumba.' },
        { mat: '\\int \\big(I(x)\\cdot y\\big)\'\\,dx = I(x)\\cdot y' },
        { h: 'El método' },
        { num: [
          'Llevar a la **forma estándar** (coeficiente 1 en $\\frac{dy}{dx}$)',
          'Identificar $P(x)$ y calcular $I(x)=e^{\\int P\\,dx}$',
          'Multiplicar **toda** la ecuación por $I(x)$',
          'Reconocer que la izquierda es $\\big(I\\cdot y\\big)\'$ e integrar los dos lados',
          'Despejar $y$',
        ] },
        { ej: ['$\\dfrac{dy}{dx}-3y=6$  — ejercicio 10 de la página 7', [
          'Ya está en forma estándar, con $P(x)=-3$ y $Q(x)=6$',
          'Factor: $\;I=e^{\\int -3\\,dx}=e^{-3x}$',
          'Multiplico todo: $\;\\left(\\dfrac{dy}{dx}-3y\\right)e^{-3x}=6e^{-3x}$',
          'La izquierda es $\\left(e^{-3x}\\,y\\right)\'$, así que integro los dos lados:',
          '$\;e^{-3x}y=\\displaystyle\\int 6e^{-3x}dx = 6\\cdot\\left(-\\dfrac{1}{3}\\right)e^{-3x}+C=-2e^{-3x}+C$',
          'Despejo: $\;y=\\dfrac{-2e^{-3x}+C}{e^{-3x}}=-2+C\\,e^{3x}$',
        ]] },
        { truco: 'Al calcular $I(x)$ **no** se pone $+C$. Si lo pusieras, el $e^{C}$ sería un factor constante que se cancela al dividir al final: no cambia nada y ensucia la cuenta.' },
      ],
      formulas: [
        ['Forma estándar', '\\frac{dy}{dx}+P(x)\\,y=Q(x)'],
        ['Factor de integración', 'I(x)=e^{\\int P(x)\\,dx}'],
        ['Lo que se logra', '\\big(I(x)\\,y\\big)\' = I(x)\\,Q(x)'],
        ['Fórmula cerrada', 'y=\\frac{1}{I(x)}\\left[\\int I(x)\\,Q(x)\\,dx + C\\right]'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Cuál es la forma estándar de una ecuación lineal de primer orden?',
          o: ['$\\dfrac{dy}{dx}+P(x)\\,y=Q(x)$', '$\\dfrac{dy}{dx}=g(x)h(y)$', '$M\\,dx+N\\,dy=0$', '$ay\'\'+by\'+cy=0$'], r: 0,
          x: 'La derivada sola con coeficiente 1, la $y$ multiplicada por una función de $x$, y del otro lado otra función de $x$.' },
        { t: 'mc', p: '¿Cuál es el factor de integración?',
          o: ['$I(x)=e^{\\int P(x)dx}$', '$I(x)=e^{\\int Q(x)dx}$', '$I(x)=\\int P(x)dx$', '$I(x)=e^{P(x)}$'], r: 0,
          x: 'Se usa $P(x)$, el que acompaña a la $y$. Y va todo el exponente dentro de una integral.' },
        { t: 'mc', p: 'Llevá $x\\dfrac{dy}{dx}-4y=x^{6}e^{x}$ a la forma estándar',
          o: ['$\\dfrac{dy}{dx}-\\dfrac{4}{x}y=x^{5}e^{x}$', '$\\dfrac{dy}{dx}-4y=x^{6}e^{x}$', '$\\dfrac{dy}{dx}-4xy=x^{7}e^{x}$', '$\\dfrac{dy}{dx}-\\dfrac{4}{x}y=x^{6}e^{x}$'], r: 0,
          x: 'Dividís **todos** los términos por $x$. Ojo con el de la derecha: $\\frac{x^{6}e^{x}}{x}=x^{5}e^{x}$, no $x^{6}e^{x}$.' },
        { t: 'in', p: 'En $\\dfrac{dy}{dx}-3y=6$, ¿cuánto vale $P(x)$?', r: ['-3'], ph: 'Un número', teclas: ['-'],
          x: 'Es el coeficiente que acompaña a la $y$, **con su signo**. Acá es $-3$.' },
        { t: 'mc', p: 'Con $P(x)=-3$, ¿cuál es el factor de integración?',
          o: ['$e^{-3x}$', '$e^{3x}$', '$-3e^{x}$', '$e^{-3}$'], r: 0,
          x: '$I=e^{\\int -3dx}=e^{-3x}$. La integral de una constante es esa constante por $x$.' },
        { t: 'mc', p: 'Después de multiplicar por $e^{-3x}$, ¿en qué se convierte el lado izquierdo?',
          o: ['$\\left(e^{-3x}\\,y\\right)\'$', '$e^{-3x}\\,y\'$', '$\\left(e^{-3x}\\right)\'y$', '$e^{-3x}+y\'$'], r: 0,
          x: 'Ese es el punto de todo el método: el factor está elegido justamente para que la izquierda sea la derivada del producto $I\\cdot y$.' },
        { t: 'mc', p: 'Resolvé $\\dfrac{dy}{dx}-3y=6$',
          o: ['$y=-2+C\\,e^{3x}$', '$y=2+C\\,e^{3x}$', '$y=-2e^{-3x}+C$', '$y=6x+C$'], r: 0,
          x: '$e^{-3x}y=-2e^{-3x}+C$, y al dividir por $e^{-3x}$ el primer término da $-2$ y el segundo $Ce^{3x}$.' },
        { t: 'ord', p: 'Ordená el método del factor de integración',
          o: ['Llevar a la forma estándar', 'Identificar $P(x)$ y calcular $I(x)=e^{\\int P\\,dx}$', 'Multiplicar toda la ecuación por $I(x)$', 'Integrar los dos miembros', 'Despejar $y$'],
          x: 'Si te salteás la forma estándar, el $P(x)$ que identificás está mal y todo lo demás también.' },
        { t: 'vf', p: 'Al calcular el factor de integración hay que agregarle $+C$ a la integral.', r: false,
          x: 'No hace falta: ese $e^{C}$ sería una constante que multiplica toda la ecuación y se cancela al despejar. Se toma la primitiva más simple.' },
        { t: 'mc', p: 'Resolvé $\\dfrac{dy}{dx}-3y=0$',
          o: ['$y=C\\,e^{3x}$', '$y=C\\,e^{-3x}$', '$y=3x+C$', '$y=0$'], r: 0,
          x: 'Con $Q=0$: $e^{-3x}y=\\int 0\\,dx=C$, entonces $y=Ce^{3x}$. También sale por separables en dos renglones.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u3l2',
      titulo: 'Cuando P(x) es una fracción',
      objetivo: 'Calcular factores del tipo $e^{-4\\ln|x|}=x^{-4}$ sin perderse.',
      teoria: [
        { p: 'El caso más frecuente del cuadernillo es $P(x)=\\dfrac{k}{x}$. Ahí el factor de integración da un **logaritmo en el exponente**, y hay que saber simplificarlo.' },
        { ej: ['Calcular $I$ cuando $P(x)=-\\dfrac{4}{x}$  — el ejercicio 9 de la página 7', [
          '$\;I=e^{\\int -\\frac{4}{x}dx}$',
          'Saco la constante: $\;=e^{-4\\int\\frac{1}{x}dx}=e^{-4\\ln|x|}$',
          'Bajo el $-4$ como exponente ($m\\ln b=\\ln b^{m}$): $\;=e^{\\ln|x|^{-4}}$',
          'Y $e^{\\ln a}=a$: $\;I=x^{-4}$',
        ]] },
        { truco: 'Regla rápida: si $P(x)=\\dfrac{k}{x}$, entonces $I=x^{k}$. Con $k=-4$ da $x^{-4}$; con $k=2$ da $x^{2}$. Comprobalo con la cadena de arriba una vez y después usalo directo.' },
        { ej: ['Resolver $x\\dfrac{dy}{dx}-4y=x^{6}e^{x}$ completo', [
          'Forma estándar (divido por $x$): $\;\\dfrac{dy}{dx}-\\dfrac{4}{x}y=x^{5}e^{x}$',
          'Factor: $\;I=x^{-4}$',
          'Multiplico todo: $\;\\left(\\dfrac{dy}{dx}-\\dfrac{4}{x}y\\right)x^{-4}=x^{5}e^{x}\\cdot x^{-4}$',
          'A la derecha, $x^{5}\\cdot x^{-4}=x^{5-4}=x$. Queda $\;\\left(x^{-4}y\\right)\'=x\\,e^{x}$',
          'Integro. La derecha sale **por partes**: $\;\\displaystyle\\int x e^{x}dx=e^{x}(x-1)$',
          '$\;x^{-4}y=e^{x}(x-1)+C$',
          'Despejo (paso $x^{-4}$ dividiendo, o sea multiplico por $x^{4}$):',
          '$\;y=\\big[e^{x}(x-1)+C\\big]\\cdot x^{4}$',
        ]] },
        { ojo: 'Al multiplicar el lado derecho por $I$, aplicá bien las propiedades de potencias: $\\dfrac{a^{m}}{a^{n}}=a^{m-n}$ y $a^{m}\\cdot a^{n}=a^{m+n}$. Ahí se pierden muchos ejercicios que estaban bien planteados.' },
        { p: 'Fijate que este ejercicio junta todo: forma estándar, propiedades de logaritmos, propiedades de potencias e integración por partes. Por eso es el ejemplo que la profe desarrolla completo en el pizarrón.' },
      ],
      formulas: [
        ['Atajo', 'P(x)=\\frac{k}{x} \;\\Rightarrow\; I(x)=x^{k}'],
        ['Cadena completa', 'e^{k\\ln|x|}=e^{\\ln|x|^{k}}=x^{k}'],
        ['Potencias', 'a^{m}\\cdot a^{n}=a^{m+n} \\qquad \\frac{a^{m}}{a^{n}}=a^{m-n}'],
        ['Por partes útil', '\\int x\\,e^{x}dx=e^{x}(x-1)+C'],
      ],
      ejercicios: [
        { t: 'mc', p: 'Si $P(x)=-\\dfrac{4}{x}$, ¿cuánto vale $\\displaystyle\\int P(x)\\,dx$?',
          o: ['$-4\\ln|x|$', '$-\\dfrac{4}{x^{2}}$', '$-4x$', '$\\ln|{-}4x|$'], r: 0,
          x: 'La constante $-4$ sale afuera y queda $\\int\\frac{1}{x}dx=\\ln|x|$.' },
        { t: 'mc', p: '¿A qué es igual $e^{-4\\ln|x|}$?',
          o: ['$x^{-4}$', '$-4x$', '$e^{-4}\\cdot x$', '$\\ln|x|^{-4}$'], r: 0,
          x: 'Bajás el $-4$ como exponente del argumento ($m\\ln b=\\ln b^{m}$) y después cancelás con $e^{\\ln a}=a$.' },
        { t: 'in', p: 'Si $P(x)=\\dfrac{3}{x}$, el factor de integración es $x^{k}$. ¿Cuánto vale $k$?', r: ['3'], ph: 'Un número',
          x: 'El atajo: el numerador de $P$ pasa a ser el exponente. $I=x^{3}$.' },
        { t: 'mc', p: '¿Cuánto vale $x^{5}\\cdot x^{-4}$?', o: ['$x$', '$x^{9}$', '$x^{-20}$', '$x^{20}$'], r: 0,
          x: 'Se suman los exponentes: $5+(-4)=1$.' },
        { t: 'mc', p: '$\\left(x^{-4}y\\right)\'=x\\,e^{x}$. Al integrar los dos lados queda',
          o: ['$x^{-4}y=e^{x}(x-1)+C$', '$x^{-4}y=xe^{x}+C$', '$x^{-4}y=\\dfrac{x^{2}}{2}e^{x}+C$', '$y=e^{x}(x-1)+C$'], r: 0,
          x: 'La izquierda vuelve a $x^{-4}y$ porque integrar una derivada la deshace. La derecha es $\\int xe^{x}dx$, que sale por partes.' },
        { t: 'mc', p: 'Despejá $y$ de $x^{-4}y=e^{x}(x-1)+C$',
          o: ['$y=\\big[e^{x}(x-1)+C\\big]x^{4}$', '$y=\\dfrac{e^{x}(x-1)+C}{x^{4}}$', '$y=e^{x}(x-1)x^{-4}+C$', '$y=e^{x}(x-1)+Cx^{4}$'], r: 0,
          x: 'Dividir por $x^{-4}$ es multiplicar por $x^{4}$, y hay que multiplicar **todo** el paréntesis, constante incluida.' },
        { t: 'mc', p: 'Para $y\'+\\dfrac{1}{x}y=\\dfrac{1}{x^{2}}$, ¿cuál es el factor de integración?',
          o: ['$I=x$', '$I=\\dfrac{1}{x}$', '$I=\\ln|x|$', '$I=e^{x}$'], r: 0,
          x: 'Con $P=\\frac{1}{x}$, el atajo da $I=x^{1}=x$.' },
        { t: 'mc', p: 'Siguiendo el anterior: multiplicando por $I=x$ queda $(xy)\'=\\dfrac{1}{x}$. Entonces',
          o: ['$y=\\dfrac{\\ln|x|+C}{x}$', '$y=x\\ln|x|+C$', '$y=\\ln|x|+C$', '$y=\\dfrac{1}{x}+C$'], r: 0,
          x: '$xy=\\int\\frac{1}{x}dx=\\ln|x|+C$, y después dividís todo por $x$.' },
        { t: 'hue', p: 'Completá la cadena', tpl: '$e^{2\\ln|x|}=e^{\\ln|x|^{2}}=x^{$ ___ $}$', r: [['2']],
          x: 'El coeficiente del logaritmo termina siendo el exponente de $x$.' },
        { t: 'vf', p: 'Al multiplicar por el factor de integración hay que multiplicar también el lado derecho.', r: true,
          x: 'Sí: se multiplica la **ecuación entera**. Olvidarse del lado derecho es el error más frecuente en este método.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u3l3',
      titulo: 'Lineales completas',
      objetivo: 'Resolver de punta a punta, con condición inicial incluida.',
      teoria: [
        { p: 'Nada nuevo acá: se trata de encadenar todo sin equivocarse. Los ejercicios 9, 10 y 11 de la página 7 son de este tipo, y en el parcial suelen venir con condición inicial.' },
        { ej: ['$y\'+\\dfrac{1}{x}y=\\dfrac{1}{x^{2}}$', [
          'Ya está en forma estándar: $P=\\dfrac{1}{x}$, $Q=\\dfrac{1}{x^{2}}$',
          'Factor: $\;I=e^{\\int\\frac{1}{x}dx}=e^{\\ln|x|}=x$',
          'Multiplico: $\;(x\\,y)\'=x\\cdot\\dfrac{1}{x^{2}}=\\dfrac{1}{x}$',
          'Integro: $\;x\\,y=\\ln|x|+C$',
          'Despejo: $\;y=\\dfrac{\\ln|x|+C}{x}$',
        ]] },
        { h: 'La fórmula cerrada' },
        { p: 'Si preferís, todo el método se resume en una sola línea. Pero conviene entender de dónde sale antes de usarla de memoria:' },
        { mat: 'y=\\frac{1}{I(x)}\\left[\\int I(x)\\,Q(x)\\,dx+C\\right]' },
        { h: 'Con condición inicial' },
        { p: 'Igual que en separables: se resuelve todo, se despeja $y$ y **recién al final** se reemplaza la condición.' },
        { ej: ['$x^{2}y\'+xy=1$ con $y(1)=2$', [
          'Forma estándar (divido por $x^{2}$): $\;y\'+\\dfrac{1}{x}y=\\dfrac{1}{x^{2}}$',
          'Ya lo resolvimos arriba: $\;y=\\dfrac{\\ln|x|+C}{x}$',
          'Reemplazo $x=1$, $y=2$: $\;2=\\dfrac{\\ln 1+C}{1}$',
          'Como $\\ln 1=0$: $\;2=C$',
          'Solución particular: $\;y=\\dfrac{\\ln|x|+2}{x}$',
        ]] },
        { truco: '$\\ln 1 = 0$ y $e^{0}=1$. Cuando la condición viene en $x=1$ o en $x=0$, casi todo se evapora. Reemplazá primero y después hacé las cuentas.' },
        { ojo: 'Si al final tenés dudas, **verificá**: derivá tu $y$, metela en la ecuación original y fijate que dé. Cuesta dos minutos y te confirma el ejercicio entero.' },
      ],
      formulas: [
        ['Fórmula cerrada', 'y=\\frac{1}{I(x)}\\left[\\int I(x)Q(x)\\,dx+C\\right]'],
        ['Valores útiles', '\\ln 1 = 0 \\qquad e^{0}=1'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Cuál es el factor de integración de $y\'+\\dfrac{1}{x}y=\\dfrac{1}{x^{2}}$?',
          o: ['$x$', '$\\dfrac{1}{x}$', '$x^{2}$', '$\\ln|x|$'], r: 0,
          x: '$I=e^{\\int(1/x)dx}=e^{\\ln|x|}=x$.' },
        { t: 'mc', p: 'Resolvé $y\'+\\dfrac{1}{x}y=\\dfrac{1}{x^{2}}$',
          o: ['$y=\\dfrac{\\ln|x|+C}{x}$', '$y=x\\ln|x|+C$', '$y=\\dfrac{1}{x}+C$', '$y=\\ln|x|+Cx$'], r: 0,
          x: '$(xy)\'=\\frac{1}{x}$, así que $xy=\\ln|x|+C$ y después dividís por $x$.' },
        { t: 'in', p: 'Con $y=\\dfrac{\\ln|x|+C}{x}$ y la condición $y(1)=2$, ¿cuánto vale $C$?', r: ['2'], ph: 'Un número',
          x: 'Reemplazo $x=1$: $2=\\frac{\\ln 1 + C}{1}$. Como $\\ln 1=0$, queda $C=2$.' },
        { t: 'in', p: '¿Cuánto vale $\\ln 1$?', r: ['0'], ph: 'Un número',
          x: 'El logaritmo de 1 en cualquier base es 0, porque cualquier número elevado a 0 da 1.' },
        { t: 'mc', p: 'Llevá $x^{2}y\'+xy=1$ a la forma estándar',
          o: ['$y\'+\\dfrac{1}{x}y=\\dfrac{1}{x^{2}}$', '$y\'+xy=1$', '$y\'+\\dfrac{1}{x^{2}}y=\\dfrac{1}{x^{2}}$', '$y\'+y=\\dfrac{1}{x}$'], r: 0,
          x: 'Dividís los tres términos por $x^{2}$: $\\frac{x}{x^{2}}=\\frac{1}{x}$ y $\\frac{1}{x^{2}}$ queda igual.' },
        { t: 'mc', p: 'La fórmula cerrada de la lineal es',
          o: ['$y=\\dfrac{1}{I}\\left[\\int I\\,Q\\,dx+C\\right]$', '$y=I\\left[\\int I\\,Q\\,dx+C\\right]$', '$y=\\dfrac{1}{I}\\int I\\,P\\,dx+C$', '$y=\\int I\\,Q\\,dx$'], r: 0,
          x: 'El factor divide afuera y adentro va $I\\cdot Q$ integrado. Se usa $Q$, no $P$: $P$ ya se gastó en construir $I$.' },
        { t: 'ord', p: 'Ordená un ejercicio de lineal con condición inicial',
          o: ['Dividir para llegar a la forma estándar', 'Calcular $I(x)=e^{\\int P\\,dx}$', 'Multiplicar por $I$ e integrar los dos lados', 'Despejar $y$', 'Reemplazar la condición inicial y hallar $C$'],
          x: 'La condición inicial siempre al final, sobre la $y$ ya despejada.' },
        { t: 'vf', p: 'La ecuación $\\dfrac{dy}{dx}-3y=6$ también se puede resolver por variables separables.', r: true,
          x: 'Sí: $\\frac{dy}{3y+6}=dx$ separa perfecto. Da el mismo resultado, $y=-2+Ce^{3x}$. Cuando $P$ y $Q$ son constantes suele convenir separables.' },
        { t: 'mc', p: 'Resolvé $y\'+2y=0$ con $y(0)=5$',
          o: ['$y=5e^{-2x}$', '$y=5e^{2x}$', '$y=e^{-2x}+5$', '$y=-2x+5$'], r: 0,
          x: 'Solución general $y=Ce^{-2x}$. Con $x=0$: $5=C\\cdot 1$, entonces $C=5$.' },
        { t: 'mc', p: 'Verificás tu resultado $y$ de una lineal',
          o: ['Derivando $y$ y reemplazando en la ecuación original', 'Integrando $y$ otra vez', 'Comparando con el factor de integración', 'Reemplazando $x=0$'], r: 0,
          x: 'Como siempre: si al meter $y$ e $y\'$ en la ecuación los dos lados dan lo mismo, está bien.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u3l4',
      titulo: 'Ecuación de Bernoulli',
      objetivo: 'Convertir una ecuación no lineal en una lineal con un cambio de variable.',
      teoria: [
        { def: ['Forma de Bernoulli', '$$\\frac{dy}{dx}+P(x)\\,y=Q(x)\\,y^{n}$$ La diferencia con una lineal común es ese $y^{n}$ del lado derecho.'] },
        { p: 'Si $n=0$ o $n=1$ la ecuación **ya es lineal** (o separable) y no hay nada que hacer. El caso interesante es cualquier otro $n$.' },
        { def: ['La sustitución', 'Se toma $$u=y^{\\,1-n}$$ y la ecuación se transforma en una **lineal en $u$**, que ya sabés resolver.'] },
        { h: 'El método' },
        { num: [
          'Llevar a la forma de Bernoulli e identificar $n$',
          'Definir $u=y^{1-n}$ y calcular $\\dfrac{du}{dx}$',
          'Reemplazar hasta que quede una lineal en $u$',
          'Resolverla con factor de integración',
          'Volver a $y$ deshaciendo la sustitución',
        ] },
        { ej: ['$x\\,y\'+y=-x\\,y^{2}$  — el ejercicio del cuadernillo', [
          'Divido por $x$ para la forma estándar: $\;y\'+\\dfrac{1}{x}y=-y^{2}$',
          'Acá $n=2$, así que $u=y^{1-2}=y^{-1}=\\dfrac{1}{y}$',
          'Derivo: $\;\\dfrac{du}{dx}=-y^{-2}\\dfrac{dy}{dx}$',
          'Divido la ecuación por $y^{2}$: $\;y^{-2}y\'+\\dfrac{1}{x}y^{-1}=-1$',
          'Reemplazo: el primer término es $-\\dfrac{du}{dx}$ y el segundo $\\dfrac{1}{x}u$:',
          '$\;-\\dfrac{du}{dx}+\\dfrac{1}{x}u=-1$, o sea $\;\\dfrac{du}{dx}-\\dfrac{1}{x}u=1$',
          'Es lineal en $u$: factor $I=x^{-1}$, y se resuelve como en la lección anterior',
        ]] },
        { truco: 'La clave mecánica es **dividir toda la ecuación por $y^{n}$**. Después de eso, los términos que quedan son exactamente los que necesita la sustitución.' },
        { ojo: 'No te olvides del último paso: la respuesta tiene que estar en términos de $y$, no de $u$. Si $u=y^{-1}$, entonces $y=\\dfrac{1}{u}$.' },
      ],
      formulas: [
        ['Bernoulli', '\\frac{dy}{dx}+P(x)y=Q(x)\\,y^{n}'],
        ['Sustitución', 'u=y^{\\,1-n}'],
        ['Lineal resultante', '\\frac{du}{dx}+(1-n)P(x)\\,u=(1-n)Q(x)'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Cuál es la forma de una ecuación de Bernoulli?',
          o: ['$y\'+P(x)y=Q(x)y^{n}$', '$y\'+P(x)y=Q(x)$', '$y\'=g(x)h(y)$', '$M\\,dx+N\\,dy=0$'], r: 0,
          x: 'Es una lineal, pero con una potencia de $y$ multiplicando del lado derecho.' },
        { t: 'mc', p: '¿Qué sustitución la convierte en lineal?',
          o: ['$u=y^{\\,1-n}$', '$u=y^{n}$', '$u=y\\cdot x$', '$u=\\ln y$'], r: 0,
          x: 'El exponente es $1-n$. Con $n=2$ da $u=y^{-1}$; con $n=3$ da $u=y^{-2}$.' },
        { t: 'in', p: 'En $y\'+\\dfrac{1}{x}y=-y^{2}$, ¿cuánto vale $n$?', r: ['2'], ph: 'Un número',
          x: 'Es el exponente de la $y$ del lado derecho.' },
        { t: 'mc', p: 'Con $n=2$, ¿cuál es la sustitución?',
          o: ['$u=y^{-1}$', '$u=y^{2}$', '$u=y^{3}$', '$u=y^{1/2}$'], r: 0,
          x: '$u=y^{1-n}=y^{1-2}=y^{-1}$, que también se escribe $u=\\frac{1}{y}$.' },
        { t: 'mc', p: 'Si $u=y^{-1}$, ¿cuánto vale $\\dfrac{du}{dx}$?',
          o: ['$-y^{-2}\\dfrac{dy}{dx}$', '$y^{-2}\\dfrac{dy}{dx}$', '$-\\dfrac{1}{y}$', '$\\dfrac{dy}{dx}$'], r: 0,
          x: 'Regla de la cadena: bajás el $-1$, restás uno al exponente y multiplicás por $\\frac{dy}{dx}$.' },
        { t: 'mc', p: '¿Cuál es el primer paso mecánico para resolver una Bernoulli?',
          o: ['Dividir toda la ecuación por $y^{n}$', 'Dividir por $y$', 'Calcular el factor de integración', 'Separar variables'], r: 0,
          x: 'Dividir por $y^{n}$ deja la ecuación con los términos $y^{-n}y\'$ y $y^{1-n}$, que son justo los que aparecen en $u$ y $\\frac{du}{dx}$.' },
        { t: 'vf', p: 'Si $n=1$, la ecuación de Bernoulli ya es lineal.', r: true,
          x: 'Con $n=1$ el término $Q(x)y$ se puede pasar a la izquierda y juntar con $P(x)y$. No hace falta sustituir nada.' },
        { t: 'ord', p: 'Ordená el método de Bernoulli',
          o: ['Llevar a la forma $y\'+Py=Qy^{n}$ e identificar $n$', 'Dividir toda la ecuación por $y^{n}$', 'Sustituir $u=y^{1-n}$ y su derivada', 'Resolver la lineal en $u$ con factor de integración', 'Volver a $y$'],
          x: 'El último paso es el que más se olvida: la respuesta va en $y$.' },
        { t: 'mc', p: 'Si resolviste y te quedó $u=\\dfrac{1}{x}\\ln|x|+Cx$, y $u=y^{-1}$, entonces',
          o: ['$y=\\dfrac{1}{u}$', '$y=u$', '$y=-u$', '$y=u^{2}$'], r: 0,
          x: '$u=y^{-1}=\\frac{1}{y}$, así que dando vuelta la fracción $y=\\frac{1}{u}$.' },
        { t: 'in', p: 'Para $y\'+2y=y^{3}$, ¿cuál es el exponente de la sustitución $u=y^{k}$?', r: ['-2'], ph: 'Puede ser negativo', teclas: ['-'],
          x: '$k=1-n=1-3=-2$, o sea $u=y^{-2}$.' },
      ],
    },
  ],
});
