/* Unidad 4 — Ecuaciones diferenciales homogéneas de primer orden
   Guía 1 del cuadernillo (pág. 9) + clases del 06/08, 13/08 y 20/08. */
(window.__UNIDADES = window.__UNIDADES || []).push({
  id: 'u4',
  n: 4,
  titulo: 'Homogéneas',
  glifo: 'u',
  resumen: 'Cuando todo tiene el mismo grado, la sustitución y = u·x convierte el problema en separable.',
  lecciones: [

    /* ------------------------------------------------------------------ */
    {
      id: 'u4l1',
      titulo: 'Reconocerlas',
      objetivo: 'Decidir si una ecuación es homogénea mirando el grado de los términos.',
      teoria: [
        { def: ['Forma', 'Son de la forma $$M(x,y)\\,dx + N(x,y)\\,dy = 0$$ donde $M$ y $N$ son del **mismo grado**.'] },
        { def: ['Grado de un término', 'La **suma** de los exponentes de $x$ e $y$. En $x^{2}$ el grado es 2; en $xy$ también es 2 ($x^{1}y^{1}$); en $y^{2}$ igual.'] },
        { ej: ['$(y^{2}-x^{2})\\,dx-2xy\\,dy=0$', [
          '$M=y^{2}-x^{2}$: los dos términos son de grado 2',
          '$N=-2xy$: también grado 2 ($x^{1}y^{1}$)',
          'Mismo grado → **es homogénea** ✓',
        ]] },
        { ej: ['$(x+y)\\,dx+x\\,dy=0$', [
          '$M=x+y$: grado 1',
          '$N=x$: grado 1',
          'Mismo grado → **es homogénea** ✓',
        ]] },
        { ojo: 'No confundas con la otra "homogénea". En **segundo orden** (unidad 5), homogénea significa que el lado derecho es cero. Son dos usos distintos de la misma palabra.' },
        { h: 'La prueba formal' },
        { p: 'Si querés estar seguro, hay un test: reemplazá $x$ por $tx$ e $y$ por $ty$. Si toda la función queda multiplicada por $t^{k}$ con el mismo $k$ en $M$ y en $N$, es homogénea.' },
        { ej: ['Test en $M=y^{2}-x^{2}$', [
          '$M(tx,ty)=(ty)^{2}-(tx)^{2}=t^{2}y^{2}-t^{2}x^{2}$',
          'Factor común: $=t^{2}\\left(y^{2}-x^{2}\\right)=t^{2}\\,M(x,y)$',
          'Salió $t^{2}$: grado 2 confirmado',
        ]] },
        { truco: 'En la práctica no hace falta el test formal: alcanza con sumar los exponentes término por término y ver si todos dan lo mismo.' },
        { p: 'Cuidado con un detalle: a veces la ecuación no viene escrita como $M\\,dx+N\\,dy=0$ sino como $(x^{2}+2y^{2})\\dfrac{dx}{dy}=xy$. Hay que **acomodarla primero**, pasando los diferenciales, antes de decidir.' },
      ],
      formulas: [
        ['Forma homogénea', 'M(x,y)\\,dx+N(x,y)\\,dy=0 \\quad (\\text{mismo grado})'],
        ['Test formal', 'M(tx,ty)=t^{k}M(x,y)'],
        ['Sustitución', 'y=u\\,x'],
      ],
      ejercicios: [
        { t: 'in', p: '¿Cuál es el grado del término $xy$?', r: ['2'], ph: 'Un número',
          x: 'Se suman los exponentes: $x^{1}y^{1}$ da $1+1=2$.' },
        { t: 'in', p: '¿Y el de $x^{2}y$?', r: ['3'], ph: 'Un número',
          x: '$2+1=3$.' },
        { t: 'vf', p: '$(y^{2}-x^{2})dx-2xy\\,dy=0$ es homogénea.', r: true,
          x: 'Todos los términos son de grado 2: $y^{2}$, $x^{2}$ y $xy$. Mismo grado en $M$ y en $N$.' },
        { t: 'vf', p: '$(x^{2}+y)dx+x\\,dy=0$ es homogénea.', r: false,
          x: 'No: en $M$ conviven $x^{2}$ (grado 2) con $y$ (grado 1). Para ser homogénea, **todos** los términos tienen que tener el mismo grado.' },
        { t: 'mc', p: '¿Cuál de estas es homogénea?', fijo: true,
          o: ['$(x+y)dx+x\\,dy=0$', '$(x^{2}+y)dx+dy=0$', '$y\'+2y=x$', '$y\'=e^{x}+y^{2}$'], r: 0,
          x: 'En la primera, $x$, $y$ y $x$ son todos de grado 1. La segunda mezcla grados, la tercera es lineal y la cuarta no tiene forma $M\\,dx+N\\,dy$.' },
        { t: 'mc', p: 'En $(x^{2}+2y^{2})dx=xy\\,dy$, ¿qué grado tienen los términos?',
          o: ['Todos grado 2', 'Todos grado 1', 'Grados mezclados', 'Todos grado 3'], r: 0,
          x: '$x^{2}$, $y^{2}$ y $xy$: los tres de grado 2. Es homogénea.' },
        { t: 'mc', p: 'Al aplicar el test $M(tx,ty)$ a $M=y^{2}-x^{2}$ obtenés',
          o: ['$t^{2}\\left(y^{2}-x^{2}\\right)$', '$t\\left(y^{2}-x^{2}\\right)$', '$y^{2}-x^{2}$', '$t^{4}\\left(y^{2}-x^{2}\\right)$'], r: 0,
          x: '$(ty)^{2}-(tx)^{2}=t^{2}y^{2}-t^{2}x^{2}$, y sacando factor común queda $t^{2}M$.' },
        { t: 'mc', p: 'Antes de decidir si $(x^{2}+2y^{2})\\dfrac{dx}{dy}=xy$ es homogénea, ¿qué conviene hacer?',
          o: ['Acomodarla a la forma $M\\,dx+N\\,dy=0$', 'Calcular el factor de integración', 'Separar variables', 'Derivar los dos lados'], r: 0,
          x: 'Hay que pasar los diferenciales para ver quién es $M$ y quién es $N$: $(x^{2}+2y^{2})dx - xy\\,dy=0$.' },
        { t: 'vf', p: 'En primer orden, "homogénea" quiere decir que el lado derecho vale cero.', r: false,
          x: 'Eso es en segundo orden. En primer orden significa que $M$ y $N$ tienen el mismo grado.' },
        { t: 'par', p: 'Emparejá cada expresión con su grado',
          o: [['$x^{3}$', 'Grado 3'], ['$x^{2}y$', 'Grado 3'], ['$xy$', 'Grado 2'], ['$y$', 'Grado 1']],
          x: 'Siempre la suma de los exponentes de $x$ e $y$.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u4l2',
      titulo: 'La sustitución y = u·x',
      objetivo: 'Cambiar de variable y llegar a una separable.',
      teoria: [
        { p: 'La idea es introducir una variable nueva $u$ que mida **la proporción entre $y$ y $x$**. Al hacerlo, las $x$ se van simplificando y lo que queda separa.' },
        { def: ['Sustitución', '$$y=u\\cdot x \\qquad\\Longrightarrow\\qquad dy = du\\cdot x + u\\cdot dx$$'] },
        { ojo: 'Ese $dy$ sale de la **derivada del producto**: si $y=u\\cdot x$ y las dos dependen de $x$, entonces $dy=x\\,du+u\\,dx$. Olvidarse de uno de los dos términos es el error número uno de esta unidad.' },
        { h: 'El método completo' },
        { num: [
          'Llevar a la forma estándar $M\\,dx+N\\,dy=0$',
          'Sustituir $y=u\\,x$ y $dy=du\\,x+u\\,dx$',
          'Distribuir y **sacar factor común** para juntar los $dx$ por un lado y los $du$ por el otro',
          'Separar e integrar los dos miembros',
          'Despejar $u$',
          'Reemplazar $u=\\dfrac{y}{x}$ y despejar $y$',
        ] },
        { ej: ['$(x+y)\\,dx+x\\,dy=0$  — el ejemplo de la clase del 06/08', [
          'Sustituyo: $\;(x+ux)\\,dx+x\\,(x\\,du+u\\,dx)=0$',
          'Distribuyo: $\;x\\,dx+ux\\,dx+x^{2}du+xu\\,dx=0$',
          'Junto los $dx$: $\;x\\,dx(1+2u)+x^{2}du=0$',
          'Paso: $\;x\\,dx(1+2u)=-x^{2}du$',
          'Separo: $\;\\dfrac{x}{-x^{2}}dx=\\dfrac{du}{1+2u}$, o sea $\;-\\dfrac{1}{x}dx=\\dfrac{du}{1+2u}$',
          'Integro: $\;-\\ln|x|+c=\\dfrac{1}{2}\\ln|1+2u|$',
        ]] },
        { truco: 'Después de distribuir, buscá siempre el **factor común**: en el ejemplo, $x\\,dx$ aparecía en dos términos ($ux\\,dx$ y $xu\\,dx$ son lo mismo) y por eso apareció el $1+2u$.' },
        { p: 'Fijate lo que pasó: después de simplificar, **todas las $x$ quedaron de un lado y todas las $u$ del otro**. Eso es exactamente lo que buscábamos: una separable.' },
      ],
      formulas: [
        ['Sustitución', 'y=u\\,x'],
        ['Diferencial (derivada del producto)', 'dy=x\\,du+u\\,dx'],
        ['Vuelta atrás', 'u=\\frac{y}{x}'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Cuál es la sustitución que se usa en las homogéneas?',
          o: ['$y=u\\,x$', '$u=y^{1-n}$', '$u=x+y$', '$y=u+x$'], r: 0,
          x: '$u$ representa el cociente $\\frac{y}{x}$, que es lo único de lo que realmente depende una ecuación homogénea.' },
        { t: 'mc', p: 'Si $y=u\\,x$, ¿cuánto vale $dy$?',
          o: ['$x\\,du+u\\,dx$', '$u\\,dx$', '$x\\,du$', '$du\\cdot dx$'], r: 0,
          x: 'Derivada del producto: derivo el primero por el segundo más el primero por la derivada del segundo.' },
        { t: 'mc', p: 'Sustituí en $(x+y)dx+x\\,dy=0$',
          o: ['$(x+ux)dx+x(x\\,du+u\\,dx)=0$', '$(x+u)dx+x\\,du=0$', '$(x+ux)dx+ux\\,dx=0$', '$(x+ux)dx+x^{2}du=0$'], r: 0,
          x: 'Se reemplazan **las dos cosas**: la $y$ por $ux$ y el $dy$ por $x\\,du+u\\,dx$.' },
        { t: 'mc', p: 'Al distribuir queda $x\\,dx+ux\\,dx+x^{2}du+xu\\,dx=0$. Sacando factor común,',
          o: ['$x\\,dx(1+2u)+x^{2}du=0$', '$x\\,dx(1+u)+x^{2}du=0$', '$x\\,dx(1+2u)=0$', '$x\\,dx(2u)+x^{2}du=0$'], r: 0,
          x: '$ux\\,dx$ y $xu\\,dx$ son el mismo término, así que sumados dan $2ux\\,dx$. Junto con $x\\,dx$ sale $x\\,dx(1+2u)$.' },
        { t: 'mc', p: 'Separá $x\\,dx(1+2u)=-x^{2}du$',
          o: ['$-\\dfrac{1}{x}dx=\\dfrac{du}{1+2u}$', '$\\dfrac{1}{x}dx=\\dfrac{du}{1+2u}$', '$x\\,dx=\\dfrac{du}{1+2u}$', '$-x\\,dx=(1+2u)\\,du$'], r: 0,
          x: 'Dividís los dos lados por $-x^{2}$ y por $(1+2u)$. A la izquierda $\\frac{x}{-x^{2}}=-\\frac{1}{x}$.' },
        { t: 'mc', p: '¿Cuánto da $\\displaystyle\\int\\dfrac{du}{1+2u}$?',
          o: ['$\\dfrac{1}{2}\\ln|1+2u|+C$', '$\\ln|1+2u|+C$', '$2\\ln|1+2u|+C$', '$\\dfrac{1}{1+2u}+C$'], r: 0,
          x: 'Sustitución $t=1+2u$, $dt=2\\,du$: queda $\\frac{1}{2}\\int\\frac{dt}{t}$.' },
        { t: 'ord', p: 'Ordená el método de las homogéneas',
          o: ['Llevar a la forma $M\\,dx+N\\,dy=0$', 'Sustituir $y=ux$ y $dy=x\\,du+u\\,dx$', 'Distribuir y sacar factor común', 'Separar variables e integrar', 'Despejar $u$ y reemplazar $u=y/x$'],
          x: 'Los pasos 3 y 4 son donde se define todo: si el factor común sale bien, la separación es automática.' },
        { t: 'vf', p: 'Después de sustituir $y=ux$, las $x$ se simplifican y queda una ecuación separable en $x$ y $u$.', r: true,
          x: 'Ese es justamente el propósito de la sustitución. Si no te simplifican, revisá si la ecuación era realmente homogénea.' },
        { t: 'hue', p: 'Completá la sustitución', tpl: '$y=u\\,x$, entonces $dy=$ ___ $\\,du+u\\,dx$', r: [['x']],
          x: 'Derivada del producto: el $x$ acompaña al $du$ y el $u$ al $dx$.' },
        { t: 'mc', p: 'En $(y^{2}-x^{2})dx-2xy\\,dy=0$, al sustituir, el término $-2xy\\,dy$ se convierte en',
          o: ['$-2x(ux)(x\\,du+u\\,dx)$', '$-2x(ux)\\,du$', '$-2ux^{2}\\,dx$', '$-2xy(x\\,du)$'], r: 0,
          x: 'Reemplazás la $y$ por $ux$ **y** el $dy$ por $x\\,du+u\\,dx$. Las dos cosas a la vez.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u4l3',
      titulo: 'Volver a la y',
      objetivo: 'Terminar el ejercicio: despejar u y deshacer la sustitución.',
      teoria: [
        { p: 'El final de una homogénea siempre tiene la misma pinta: te quedó una igualdad con logaritmos, hay que despejar $u$ con exponenciales, y después reemplazar $u=\\dfrac{y}{x}$.' },
        { ej: ['Terminar $-\\ln|x|+c=\\dfrac{1}{2}\\ln|1+2u|$', [
          'Multiplico todo por 2: $\;-2\\ln|x|+2c=\\ln|1+2u|$',
          'Exponencial a los dos lados: $\;e^{-2\\ln|x|+2c}=1+2u$',
          'Despejo $u$: $\;u=\\dfrac{e^{-2\\ln|x|+2c}-1}{2}$',
          'Simplifico el exponente: $\;e^{-2\\ln|x|}\\cdot e^{2c}=x^{-2}\\cdot e^{2c}$',
          'Reemplazo $u=\\dfrac{y}{x}$ y despejo: $\;y=x\\cdot\\dfrac{x^{-2}e^{2c}-1}{2}$',
        ]] },
        { truco: 'Al final, $e^{2c}$ es una constante nueva: llamala $K$ y listo. La respuesta queda $y=\\dfrac{x}{2}\\left(\\dfrac{K}{x^{2}}-1\\right)$, mucho más presentable.' },
        { ej: ['$(y^{2}-x^{2})dx-2xy\\,dy=0$  — el ejercicio 13, clase del 13/08', [
          'Sustituyo y distribuyo hasta llegar a: $\;-x^{2}dx\\left(u^{2}+1\\right)=2ux^{3}du$',
          'Separo: $\;-\\dfrac{1}{x}dx=\\dfrac{2u}{u^{2}+1}du$',
          'Integro. A la derecha el numerador es la derivada del denominador:',
          '$\;-\\ln|x|+c=\\ln\\left|u^{2}+1\\right|$',
          'Exponencial: $\;e^{-\\ln|x|+c}=u^{2}+1$, o sea $\;\\dfrac{K}{x}=u^{2}+1$',
          'Despejo: $\;u=\\sqrt{\\dfrac{K}{x}-1}$',
          'Vuelvo: $\;\\dfrac{y}{x}=\\sqrt{\\dfrac{K}{x}-1}$, entonces $\;y=x\\sqrt{\\dfrac{K}{x}-1}$',
        ]] },
        { ojo: 'La integral $\\displaystyle\\int\\dfrac{2u}{u^{2}+1}du=\\ln|u^{2}+1|$ aparece casi siempre en esta unidad: el $2u$ de arriba es exactamente la derivada de $u^{2}+1$.' },
        { h: 'Con condición inicial' },
        { p: 'Si el ejercicio da una condición del tipo $y(1)=2$, se reemplaza **al final**, en la solución ya escrita en términos de $x$ e $y$, nunca en la de $u$.' },
      ],
      formulas: [
        ['Deshacer la sustitución', 'u=\\frac{y}{x} \;\\Rightarrow\; y = u\\,x'],
        ['Integral típica', '\\int \\frac{2u}{u^{2}+1}du=\\ln|u^{2}+1|+C'],
        ['La otra típica', '\\int \\frac{du}{1+2u}=\\frac{1}{2}\\ln|1+2u|+C'],
        ['Constante final', 'e^{2c}=K'],
      ],
      ejercicios: [
        { t: 'mc', p: 'Terminaste con $-\\ln|x|+c=\\ln|u^{2}+1|$. ¿Cuál es el paso siguiente?',
          o: ['Aplicar exponencial a los dos miembros', 'Derivar', 'Reemplazar $u=y/x$ ya mismo', 'Integrar otra vez'], r: 0,
          x: 'Primero hay que sacarse los logaritmos de encima para poder despejar $u$. Recién después se deshace la sustitución.' },
        { t: 'mc', p: '¿A qué equivale $e^{-2\\ln|x|+2c}$?',
          o: ['$x^{-2}\\cdot e^{2c}$', '$-2x\\cdot e^{2c}$', '$x^{2}\\cdot e^{2c}$', '$e^{-2}\\cdot x\\cdot e^{2c}$'], r: 0,
          x: 'Partís el exponente ($e^{m+n}=e^{m}e^{n}$) y después $e^{-2\\ln|x|}=e^{\\ln|x|^{-2}}=x^{-2}$.' },
        { t: 'mc', p: 'Si $u=\\dfrac{e^{-2\\ln|x|+2c}-1}{2}$ y $u=\\dfrac{y}{x}$, entonces',
          o: ['$y=x\\cdot\\dfrac{x^{-2}e^{2c}-1}{2}$', '$y=\\dfrac{x^{-2}e^{2c}-1}{2x}$', '$y=\\dfrac{x^{-2}e^{2c}-1}{2}$', '$y=x+u$'], r: 0,
          x: 'De $\\frac{y}{x}=u$ sale $y=u\\cdot x$: multiplicás toda la expresión de $u$ por $x$.' },
        { t: 'mc', p: '¿Cuánto da $\\displaystyle\\int\\dfrac{2u}{u^{2}+1}du$?',
          o: ['$\\ln|u^{2}+1|+C$', '$\\dfrac{1}{2}\\ln|u^{2}+1|+C$', '$2\\arctan u+C$', '$\\dfrac{u^{2}}{u^{2}+1}+C$'], r: 0,
          x: 'El numerador $2u$ es exactamente la derivada del denominador, así que da logaritmo directo, sin coeficiente.' },
        { t: 'mc', p: 'De $\\dfrac{K}{x}=u^{2}+1$, despejá $u$',
          o: ['$u=\\sqrt{\\dfrac{K}{x}-1}$', '$u=\\dfrac{K}{x}-1$', '$u=\\sqrt{\\dfrac{K}{x}}-1$', '$u=\\dfrac{K}{x^{2}}$'], r: 0,
          x: 'Pasás el $1$ restando y después sacás raíz cuadrada a **todo** el miembro.' },
        { t: 'mc', p: 'Con $u=\\sqrt{\\dfrac{K}{x}-1}$, la solución en $y$ es',
          o: ['$y=x\\sqrt{\\dfrac{K}{x}-1}$', '$y=\\sqrt{\\dfrac{K}{x}-1}$', '$y=\\dfrac{1}{x}\\sqrt{\\dfrac{K}{x}-1}$', '$y=\\dfrac{K}{x}-1$'], r: 0,
          x: '$y=u\\cdot x$, así que la raíz entera queda multiplicada por $x$.' },
        { t: 'vf', p: 'La condición inicial se reemplaza en la solución escrita en términos de $u$.', r: false,
          x: 'No: primero volvés a $x$ e $y$, y recién ahí reemplazás. La condición habla de $y$, no de $u$.' },
        { t: 'in', p: 'Si al final te queda $e^{2c}$, lo renombrás como una constante nueva. ¿Cuántas constantes independientes tiene la solución general de una ecuación de primer orden?', r: ['1', 'una'], ph: 'Un número',
          x: 'Una sola. El orden de la ecuación te dice cuántas constantes tiene la solución general: primer orden, una constante.' },
        { t: 'ord', p: 'Ordená el cierre de una homogénea',
          o: ['Integrar los dos miembros', 'Aplicar exponencial para eliminar los logaritmos', 'Despejar $u$', 'Reemplazar $u=y/x$', 'Despejar $y$'],
          x: 'Siempre el mismo cierre. Si hay condición inicial, va después de todo esto.' },
        { t: 'mc', p: '¿Por qué la sustitución $y=ux$ funciona en las homogéneas?',
          o: ['Porque una ecuación homogénea sólo depende del cociente $y/x$', 'Porque simplifica los logaritmos', 'Porque convierte la ecuación en lineal', 'Porque elimina la constante'], r: 0,
          x: 'Al tener todos los términos el mismo grado, se puede sacar factor común de $x^{k}$ y lo que sobrevive depende sólo de $y/x$. Esa es la razón de fondo.' },
      ],
    },
  ],
});
