/* Unidad 5 — Ecuaciones diferenciales de segundo orden con coeficientes constantes
   Guía 1 del cuadernillo + clases del 06/08 y 13/08. */
(window.__UNIDADES = window.__UNIDADES || []).push({
  id: 'u5',
  n: 5,
  titulo: 'Segundo orden',
  glifo: 'y″',
  resumen: 'Ecuación característica, tres casos de raíces y dos constantes que salen de dos condiciones.',
  lecciones: [

    /* ------------------------------------------------------------------ */
    {
      id: 'u5l1',
      titulo: 'La ecuación característica',
      objetivo: 'Entender de dónde sale el polinomio que resuelve todo.',
      teoria: [
        { def: ['Forma general', '$$P(x)\\,y\'\'+Q(x)\\,y\'+R(x)\\,y=G(x)$$ con $P$, $Q$, $R$ y $G$ funciones continuas.'] },
        { def: ['Homogénea', 'Si $G(x)=0$, la ecuación se llama **homogénea de segundo orden**. Es la que vamos a resolver.'] },
        { ojo: 'Acá "homogénea" significa otra cosa que en primer orden. En primer orden era "todos los términos del mismo grado"; en segundo orden significa **lado derecho igual a cero**.' },
        { p: 'Cuando además $P$, $Q$ y $R$ son **constantes**, la ecuación queda:' },
        { mat: 'a\\,y\'\'+b\\,y\'+c\\,y=0' },
        { h: 'De dónde sale el truco' },
        { p: 'Se prueba con una función que al derivarse se parece a sí misma: la exponencial $y=e^{rx}$, con $r$ constante.' },
        { ej: ['Reemplazar $y=e^{rx}$ en la ecuación', [
          'Las derivadas son $\;y\'=r\\,e^{rx}\;$ y $\;y\'\'=r^{2}e^{rx}$',
          'Reemplazo: $\;a\\,r^{2}e^{rx}+b\\,r\\,e^{rx}+c\\,e^{rx}=0$',
          'Saco factor común: $\;e^{rx}\\left(a\\,r^{2}+b\\,r+c\\right)=0$',
          'La exponencial **nunca** vale cero, así que lo que tiene que anularse es el paréntesis:',
          '$\;a\\,r^{2}+b\\,r+c=0$',
        ]] },
        { def: ['Ecuación característica', 'También llamada auxiliar: $$a\\,r^{2}+b\\,r+c=0$$ Es una ecuación de segundo grado común, que se resuelve con la resolvente.'] },
        { truco: 'Para armarla: reemplazás $y\'\'$ por $r^{2}$, $y\'$ por $r$ e $y$ por $1$. Nada más. $3y\'\'+y\'-y=0$ se convierte en $3r^{2}+r-1=0$.' },
        { p: 'Según **cómo salgan las raíces** de esa ecuación de segundo grado, la solución general tiene tres formas distintas. Eso es toda la unidad.' },
        { tabla: [['Raíces de $ar^{2}+br+c=0$', 'Solución general'], [
          ['Reales distintas $r_1\\neq r_2$', '$y=C_1e^{r_1x}+C_2e^{r_2x}$'],
          ['Reales iguales $r_1=r_2=r$', '$y=C_1e^{rx}+C_2\\,x\\,e^{rx}$'],
          ['Complejas $r=\\alpha\\pm\\beta i$', '$y=e^{\\alpha x}\\left[C_1\\cos(\\beta x)+C_2\\sen(\\beta x)\\right]$'],
        ]] },
        { p: 'Fijate que la solución general de una ecuación de segundo orden tiene **dos constantes**, $C_1$ y $C_2$. Regla general: tantas constantes como el orden.' },
      ],
      formulas: [
        ['Ecuación', 'a\\,y\'\'+b\\,y\'+c\\,y=0'],
        ['Característica', 'a\\,r^{2}+b\\,r+c=0'],
        ['Resolvente', 'r=\\frac{-b\\pm\\sqrt{b^{2}-4ac}}{2a}'],
      ],
      ejercicios: [
        { t: 'mc', p: 'En segundo orden, ¿qué significa que la ecuación sea homogénea?',
          o: ['Que el lado derecho vale cero', 'Que todos los términos tienen el mismo grado', 'Que los coeficientes son constantes', 'Que las raíces son iguales'], r: 0,
          x: 'Distinto de primer orden, donde homogénea quería decir "mismo grado". Es la misma palabra usada para dos cosas.' },
        { t: 'mc', p: '¿Qué función se prueba para llegar a la ecuación característica?',
          o: ['$y=e^{rx}$', '$y=x^{r}$', '$y=u\\,x$', '$y=\\sen(rx)$'], r: 0,
          x: 'La exponencial, porque al derivarse se reproduce a sí misma multiplicada por una constante.' },
        { t: 'mc', p: 'Si $y=e^{rx}$, ¿cuánto vale $y\'\'$?',
          o: ['$r^{2}e^{rx}$', '$r\\,e^{rx}$', '$e^{rx}$', '$r^{2}$'], r: 0,
          x: 'Cada derivada baja un factor $r$. La segunda derivada baja dos: $r^{2}$.' },
        { t: 'mc', p: '¿Por qué de $e^{rx}(ar^{2}+br+c)=0$ se concluye que $ar^{2}+br+c=0$?',
          o: ['Porque $e^{rx}$ nunca vale cero', 'Porque $e^{rx}$ siempre vale 1', 'Porque se simplifica con la derivada', 'Porque $r$ es constante'], r: 0,
          x: 'La exponencial es siempre positiva. Si un producto da cero y un factor nunca es cero, el otro tiene que serlo.' },
        { t: 'mc', p: 'Escribí la ecuación característica de $3y\'\'+y\'-y=0$',
          o: ['$3r^{2}+r-1=0$', '$3r+r^{2}-1=0$', '$3r^{2}+r=0$', '$r^{2}+3r-1=0$'], r: 0,
          x: '$y\'\'\\to r^{2}$, $y\'\\to r$, $y\\to 1$. Los coeficientes se copian tal cual.' },
        { t: 'mc', p: '¿Y la de $4y\'\'+12y\'+9y=0$?',
          o: ['$4r^{2}+12r+9=0$', '$4r+12r^{2}+9=0$', '$r^{2}+12r+9=0$', '$4r^{2}+12r=0$'], r: 0,
          x: 'Misma regla: cada derivada se convierte en la potencia correspondiente de $r$.' },
        { t: 'in', p: '¿Cuántas constantes tiene la solución general de una ecuación de segundo orden?', r: ['2', 'dos'], ph: 'Un número',
          x: 'Dos: $C_1$ y $C_2$. La cantidad de constantes coincide con el orden de la ecuación.' },
        { t: 'par', p: 'Emparejá cada tipo de raíz con su solución general',
          o: [['Reales distintas', '$C_1e^{r_1x}+C_2e^{r_2x}$'], ['Reales iguales', '$C_1e^{rx}+C_2xe^{rx}$'], ['Complejas', '$e^{\\alpha x}\\left[C_1\\cos\\beta x+C_2\\sen\\beta x\\right]$']],
          x: 'Los tres casos de la tabla. Valen la pena de memoria: son literalmente la mitad de la unidad.' },
        { t: 'ord', p: 'Ordená el método para segundo orden',
          o: ['Escribir la ecuación característica', 'Hallar las raíces con la resolvente', 'Ver en cuál de los tres casos estás', 'Escribir la solución general con $C_1$ y $C_2$'],
          x: 'Todo se decide en el paso 2: el discriminante te dice en qué caso caés.' },
        { t: 'vf', p: 'La ecuación característica es una ecuación de segundo grado común.', r: true,
          x: 'Sí, y se resuelve con la resolvente de toda la vida. Lo único diferente es qué hacés después con las raíces.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u5l2',
      titulo: 'Raíces reales',
      objetivo: 'Resolver los casos 1 y 2, cuando el discriminante no es negativo.',
      teoria: [
        { h: 'Caso 1: raíces reales distintas' },
        { p: 'Si el discriminante $b^{2}-4ac$ es **positivo**, la resolvente da dos raíces distintas y la solución es la suma de dos exponenciales:' },
        { mat: 'y=C_1e^{r_1x}+C_2e^{r_2x}' },
        { ej: ['$y\'\'+y\'-6y=0$  — el ejemplo de la clase', [
          'Característica: $\;r^{2}+r-6=0$, con $a=1$, $b=1$, $c=-6$',
          'Resolvente: $\;r=\\dfrac{-1\\pm\\sqrt{1-4\\cdot 1\\cdot(-6)}}{2}=\\dfrac{-1\\pm\\sqrt{25}}{2}=\\dfrac{-1\\pm 5}{2}$',
          '$\;r_1=\\dfrac{-1+5}{2}=2\;$ y $\;r_2=\\dfrac{-1-5}{2}=-3$',
          'Reales y distintas → caso 1:',
          '$\;y=C_1e^{2x}+C_2e^{-3x}$',
        ]] },
        { h: 'Caso 2: raíz real doble' },
        { p: 'Si el discriminante es **cero**, hay una sola raíz. Pero necesitamos dos soluciones independientes, así que la segunda se consigue **multiplicando por $x$**:' },
        { mat: 'y=C_1e^{rx}+C_2\\,x\\,e^{rx}' },
        { ej: ['$4y\'\'+12y\'+9y=0$  — el ejercicio b) de la página 65 de Zill', [
          'Característica: $\;4r^{2}+12r+9=0$',
          'Discriminante: $\;12^{2}-4\\cdot 4\\cdot 9=144-144=0$',
          'Entonces $\;r=\\dfrac{-12}{8}=-\\dfrac{3}{2}\;$ (doble)',
          'Caso 2: $\;y=C_1e^{-\\frac{3}{2}x}+C_2\\,x\\,e^{-\\frac{3}{2}x}$',
        ]] },
        { ojo: 'En el caso 2, la $x$ va **sólo en el segundo término**. Escribir $C_1xe^{rx}+C_2xe^{rx}$ no sirve: serían la misma función dos veces, y no alcanzaría para cumplir dos condiciones iniciales.' },
        { truco: 'Antes de aplicar la resolvente entera, calculá el discriminante solo. Te dice de una en qué caso estás: positivo → caso 1, cero → caso 2, negativo → caso 3.' },
      ],
      formulas: [
        ['Discriminante', '\\Delta = b^{2}-4ac'],
        ['Caso 1 ($\\Delta>0$)', 'y=C_1e^{r_1x}+C_2e^{r_2x}'],
        ['Caso 2 ($\\Delta=0$)', 'y=C_1e^{rx}+C_2\\,x\\,e^{rx}'],
        ['Raíz doble', 'r=\\frac{-b}{2a}'],
      ],
      ejercicios: [
        { t: 'mc', p: 'Si el discriminante $b^{2}-4ac$ es positivo, ¿en qué caso estás?',
          o: ['Caso 1: raíces reales distintas', 'Caso 2: raíz doble', 'Caso 3: raíces complejas', 'Depende del signo de $a$'], r: 0,
          x: 'Un discriminante positivo da una raíz cuadrada real y no nula, así que $\\pm$ produce dos valores distintos.' },
        { t: 'in', p: 'Para $r^{2}+r-6=0$, ¿cuánto vale el discriminante?', r: ['25'], ph: 'Un número',
          x: '$b^{2}-4ac=1^{2}-4\\cdot 1\\cdot(-6)=1+24=25$. Ojo con el doble signo menos.' },
        { t: 'hue', p: 'Las raíces de $r^{2}+r-6=0$ son', tpl: '$r_1=$ ___ y $r_2=$ ___', r: [['2'], ['-3']],
          x: '$r=\\frac{-1\\pm 5}{2}$, así que $r_1=\\frac{4}{2}=2$ y $r_2=\\frac{-6}{2}=-3$.' },
        { t: 'mc', p: 'Resolvé $y\'\'+y\'-6y=0$',
          o: ['$y=C_1e^{2x}+C_2e^{-3x}$', '$y=C_1e^{-2x}+C_2e^{3x}$', '$y=C_1e^{2x}+C_2xe^{2x}$', '$y=e^{2x}\\left[C_1\\cos 3x+C_2\\sen 3x\\right]$'], r: 0,
          x: 'Las raíces $2$ y $-3$ van directo al exponente. La segunda opción tiene los signos cambiados.' },
        { t: 'in', p: 'Para $4r^{2}+12r+9=0$, ¿cuánto vale el discriminante?', r: ['0'], ph: 'Un número',
          x: '$144-4\\cdot 4\\cdot 9=144-144=0$. Discriminante nulo: raíz doble.' },
        { t: 'mc', p: 'Con discriminante cero, la raíz de $4r^{2}+12r+9=0$ es',
          o: ['$r=-\\dfrac{3}{2}$', '$r=\\dfrac{3}{2}$', '$r=-3$', '$r=-\\dfrac{12}{4}$'], r: 0,
          x: 'Con $\\Delta=0$ la resolvente se reduce a $r=\\frac{-b}{2a}=\\frac{-12}{8}=-\\frac{3}{2}$.' },
        { t: 'mc', p: 'Resolvé $4y\'\'+12y\'+9y=0$',
          o: ['$y=C_1e^{-\\frac{3}{2}x}+C_2\\,x\\,e^{-\\frac{3}{2}x}$', '$y=C_1e^{-\\frac{3}{2}x}+C_2e^{-\\frac{3}{2}x}$', '$y=C_1e^{-\\frac{3}{2}x}+C_2e^{\\frac{3}{2}x}$', '$y=C_1x e^{-\\frac{3}{2}x}+C_2xe^{-\\frac{3}{2}x}$'], r: 0,
          x: 'Caso 2: la segunda solución lleva una $x$ multiplicando. La segunda opción sería $(C_1+C_2)e^{rx}$, o sea una sola constante.' },
        { t: 'vf', p: 'En el caso de raíz doble, las dos soluciones son $e^{rx}$ y $x\\,e^{rx}$.', r: true,
          x: 'Sí: la $x$ genera la segunda solución independiente que hace falta para cubrir dos condiciones iniciales.' },
        { t: 'mc', p: 'Resolvé $3y\'\'+y\'-y=0$',
          o: ['$y=C_1e^{\\frac{-1+\\sqrt{13}}{6}x}+C_2e^{\\frac{-1-\\sqrt{13}}{6}x}$', '$y=C_1e^{\\frac{-1+\\sqrt{13}}{2}x}+C_2e^{\\frac{-1-\\sqrt{13}}{2}x}$', '$y=C_1e^{13x}+C_2e^{-13x}$', '$y=e^{-x}\\left[C_1\\cos\\sqrt{13}x+C_2\\sen\\sqrt{13}x\\right]$'], r: 0,
          x: '$3r^{2}+r-1=0$ da $r=\\frac{-1\\pm\\sqrt{1+12}}{6}=\\frac{-1\\pm\\sqrt{13}}{6}$. El denominador es $2a=6$, no $2$.' },
        { t: 'mc', p: 'Si las raíces son $r_1=5$ y $r_2=-1$, la solución general es',
          o: ['$y=C_1e^{5x}+C_2e^{-x}$', '$y=C_1e^{5x}+C_2xe^{-x}$', '$y=e^{5x}\\left[C_1\\cos x+C_2\\sen x\\right]$', '$y=C_1e^{5}+C_2e^{-1}$'], r: 0,
          x: 'Caso 1 puro: cada raíz va al exponente de su exponencial.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u5l3',
      titulo: 'Raíces complejas',
      objetivo: 'Resolver el caso 3 y escribir la solución con senos y cosenos.',
      teoria: [
        { p: 'Si el discriminante da **negativo**, la raíz cuadrada de un número negativo obliga a salir de los reales. Ahí aparece la unidad imaginaria $i$, con $i^{2}=-1$.' },
        { def: ['Raíces complejas conjugadas', 'Quedan de la forma $$r_1=\\alpha+\\beta i \\qquad r_2=\\alpha-\\beta i$$ donde $\\alpha$ es la parte real y $\\beta$ el coeficiente de la imaginaria.'] },
        { mat: 'y=e^{\\alpha x}\\left[C_1\\cos(\\beta x)+C_2\\,\\sen(\\beta x)\\right]' },
        { h: 'Sacar raíces de números negativos' },
        { tabla: [['Expresión', 'Resultado'], [
          ['$\\sqrt{-16}$', '$4i$'], ['$\\sqrt{-49}$', '$7i$'], ['$\\sqrt{-4}$', '$2i$'], ['$\\sqrt{-1}$', '$i$'],
        ]] },
        { p: 'La cuenta es $\\sqrt{-16}=\\sqrt{16}\\cdot\\sqrt{-1}=4i$. Y se comprueba al revés: $(4i)^{2}=16\\,i^{2}=16\\cdot(-1)=-16$ ✓' },
        { ej: ['$y\'\'-6y\'+13y=0$  — el ejercicio c) de la clase del 13/08', [
          'Característica: $\;r^{2}-6r+13=0$',
          'Resolvente: $\;r=\\dfrac{6\\pm\\sqrt{36-4\\cdot 1\\cdot 13}}{2}=\\dfrac{6\\pm\\sqrt{36-52}}{2}=\\dfrac{6\\pm\\sqrt{-16}}{2}$',
          '$\;=\\dfrac{6\\pm 4i}{2}$. Separo las dos fracciones: $\;\\dfrac{6}{2}\\pm\\dfrac{4i}{2}=3\\pm 2i$',
          'Entonces $\;\\alpha=3\;$ y $\;\\beta=2$',
          'Solución general: $\;y=e^{3x}\\left[C_1\\cos(2x)+C_2\\sen(2x)\\right]$',
        ]] },
        { truco: 'Para separar $\\dfrac{6\\pm 4i}{2}$, dividí cada parte por separado. Es el paso donde más se traba la gente, y es apenas partir una fracción en dos.' },
        { ojo: 'No importa cuál raíz llames $r_1$ y cuál $r_2$: la solución es la misma. Eso es porque $\\cos(-\\beta x)=\\cos(\\beta x)$ y $\\sen(-\\beta x)=-\\sen(\\beta x)$, y ese signo se absorbe en la constante $C_2$.' },
        { ej: ['$y\'\'+y=0$  — caso con $\\alpha=0$', [
          'Característica: $\;r^{2}+1=0$, o sea $\;r^{2}=-1$',
          'Raíces: $\;r=\\pm i$, así que $\;\\alpha=0\;$ y $\;\\beta=1$',
          'Como $e^{0\\cdot x}=1$, la exponencial desaparece:',
          '$\;y=C_1\\cos x+C_2\\sen x$',
        ]] },
      ],
      formulas: [
        ['Caso 3 ($\\Delta<0$)', 'y=e^{\\alpha x}\\left[C_1\\cos(\\beta x)+C_2\\sen(\\beta x)\\right]'],
        ['Raíces', 'r=\\alpha\\pm\\beta i'],
        ['Raíz de negativo', '\\sqrt{-k}=\\sqrt{k}\;i'],
        ['Unidad imaginaria', 'i^{2}=-1'],
      ],
      ejercicios: [
        { t: 'in', p: '¿Cuánto vale $\\sqrt{-16}$?', r: ['4i', '4*i'], ph: 'Por ejemplo: 4i',
          x: '$\\sqrt{-16}=\\sqrt{16}\\cdot\\sqrt{-1}=4i$. Verificás elevando al cuadrado: $(4i)^{2}=16i^{2}=-16$ ✓', teclas: ['i'] },
        { t: 'in', p: '¿Y $\\sqrt{-49}$?', r: ['7i', '7*i'], ph: 'Por ejemplo: 7i', teclas: ['i'],
          x: '$\\sqrt{49}=7$, y la parte negativa aporta la $i$.' },
        { t: 'in', p: 'Para $r^{2}-6r+13=0$, ¿cuánto vale el discriminante?', r: ['-16'], ph: 'Puede ser negativo', teclas: ['-'],
          x: '$(-6)^{2}-4\\cdot 1\\cdot 13=36-52=-16$. Negativo: raíces complejas.' },
        { t: 'hue', p: 'Las raíces de $r^{2}-6r+13=0$ son $\\alpha\\pm\\beta i$. Entonces', tpl: '$\\alpha=$ ___ y $\\beta=$ ___', r: [['3'], ['2']],
          x: '$r=\\frac{6\\pm 4i}{2}=\\frac{6}{2}\\pm\\frac{4i}{2}=3\\pm 2i$. La parte real es $3$ y el coeficiente de la imaginaria es $2$.' },
        { t: 'mc', p: 'Resolvé $y\'\'-6y\'+13y=0$',
          o: ['$y=e^{3x}\\left[C_1\\cos(2x)+C_2\\sen(2x)\\right]$', '$y=e^{2x}\\left[C_1\\cos(3x)+C_2\\sen(3x)\\right]$', '$y=C_1e^{3x}+C_2e^{2x}$', '$y=e^{3x}\\left[C_1\\cos(2x)-C_2\\sen(2x)\\right]$'], r: 0,
          x: '$\\alpha=3$ va al exponente y $\\beta=2$ adentro de las funciones trigonométricas. La segunda opción los tiene invertidos.' },
        { t: 'mc', p: 'Resolvé $y\'\'+y=0$',
          o: ['$y=C_1\\cos x+C_2\\sen x$', '$y=C_1e^{x}+C_2e^{-x}$', '$y=e^{x}\\left[C_1\\cos x+C_2\\sen x\\right]$', '$y=C_1\\cos x$'], r: 0,
          x: 'Raíces $\\pm i$: $\\alpha=0$, $\\beta=1$. Como $e^{0}=1$, la exponencial se va.' },
        { t: 'vf', p: 'Si el discriminante es negativo, la solución general lleva senos y cosenos.', r: true,
          x: 'Sí. Las raíces complejas se traducen en oscilaciones, y la parte real $\\alpha$ controla si esa oscilación crece o se amortigua.' },
        { t: 'mc', p: 'Si las raíces son $r=-1\\pm 3i$, la solución general es',
          o: ['$y=e^{-x}\\left[C_1\\cos(3x)+C_2\\sen(3x)\\right]$', '$y=e^{3x}\\left[C_1\\cos x+C_2\\sen x\\right]$', '$y=e^{-x}+C_1\\cos(3x)$', '$y=C_1e^{-x}+C_2e^{3x}$'], r: 0,
          x: '$\\alpha=-1$ al exponente, $\\beta=3$ adentro del seno y el coseno.' },
        { t: 'mc', p: '¿Por qué da igual cuál raíz llamés $r_1$?',
          o: ['Porque $\\cos(-\\beta x)=\\cos(\\beta x)$ y el signo del seno se absorbe en $C_2$', 'Porque las dos raíces son iguales', 'Porque $i^{2}=-1$', 'Porque la exponencial es par'], r: 0,
          x: 'El coseno es par y el seno impar, así que cambiar el signo de $\\beta$ sólo cambia el signo de $C_2$, que es una constante libre.' },
        { t: 'mc', p: '$\\dfrac{6+4i}{2}$ es igual a',
          o: ['$3+2i$', '$3+4i$', '$6+2i$', '$5i$'], r: 0,
          x: 'Se divide cada parte por separado: $\\frac{6}{2}=3$ y $\\frac{4i}{2}=2i$.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u5l4',
      titulo: 'Solución particular',
      objetivo: 'Usar las dos condiciones iniciales para hallar C₁ y C₂.',
      teoria: [
        { p: 'Como la solución general tiene **dos** constantes, hacen falta **dos** condiciones. Lo habitual es que den el valor de la función y el de su derivada en el mismo punto: $y(0)=1$ y $y\'(0)=0$.' },
        { h: 'El método' },
        { num: [
          'Obtener la solución general',
          'Calcular $y\'$ derivando la solución general',
          'Reemplazar la primera condición en $y$ y la segunda en $y\'$',
          'Resolver el **sistema de dos ecuaciones** con incógnitas $C_1$ y $C_2$',
          'Escribir la solución particular',
        ] },
        { ej: ['$y\'\'+y\'-6y=0$ con $y(0)=1$, $y\'(0)=0$  — el ejemplo completo de la clase', [
          'Solución general (ya la tenemos): $\;y=C_1e^{2x}+C_2e^{-3x}$',
          'Derivo: $\;y\'=2C_1e^{2x}-3C_2e^{-3x}$',
          'Primera condición, $y(0)=1$: como $e^{0}=1$, queda $\;1=C_1+C_2$',
          'Segunda condición, $y\'(0)=0$: $\;0=2C_1-3C_2$',
          'Del primero despejo $C_1=1-C_2$ y reemplazo en el segundo:',
          '$\;0=2(1-C_2)-3C_2=2-2C_2-3C_2=2-5C_2$',
          '$\;5C_2=2 \\Rightarrow C_2=\\dfrac{2}{5}$, y entonces $\;C_1=1-\\dfrac{2}{5}=\\dfrac{3}{5}$',
          'Solución particular: $\;y=\\dfrac{3}{5}e^{2x}+\\dfrac{2}{5}e^{-3x}$',
        ]] },
        { truco: 'Con las condiciones en $x=0$ todas las exponenciales valen 1 y el sistema queda con puros números. Por eso casi siempre las dan ahí.' },
        { ojo: 'No te olvides de derivar **antes** de reemplazar la segunda condición. Un error clásico es meter $y\'(0)=0$ en la expresión de $y$ en vez de en la de $y\'$.' },
        { p: 'Cuando la solución general es del caso 3, la derivada sale por **regla del producto** (exponencial por corchete) y da un poco más de trabajo, pero el método es idéntico.' },
      ],
      formulas: [
        ['Dos condiciones', 'y(x_0)=y_0 \\quad\\text{y}\\quad y\'(x_0)=y_1'],
        ['Sistema típico', '\\begin{cases} C_1+C_2=y_0 \\\\ r_1C_1+r_2C_2=y_1 \\end{cases}'],
        ['Derivada caso 1', 'y\'=r_1C_1e^{r_1x}+r_2C_2e^{r_2x}'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Cuántas condiciones iniciales hacen falta en una ecuación de segundo orden?',
          o: ['Dos', 'Una', 'Tres', 'Ninguna'], r: 0,
          x: 'Una por cada constante de la solución general. Como hay $C_1$ y $C_2$, hacen falta dos.' },
        { t: 'mc', p: 'Si $y=C_1e^{2x}+C_2e^{-3x}$, ¿cuánto vale $y\'$?',
          o: ['$2C_1e^{2x}-3C_2e^{-3x}$', '$C_1e^{2x}+C_2e^{-3x}$', '$2C_1e^{2x}+3C_2e^{-3x}$', '$2e^{2x}-3e^{-3x}$'], r: 0,
          x: 'Cada exponencial se multiplica por el coeficiente de su exponente, con signo incluido.' },
        { t: 'mc', p: 'Aplicando $y(0)=1$ a $y=C_1e^{2x}+C_2e^{-3x}$ obtenés',
          o: ['$1=C_1+C_2$', '$1=2C_1-3C_2$', '$1=C_1$', '$0=C_1+C_2$'], r: 0,
          x: 'Con $x=0$ las dos exponenciales valen 1, así que quedan las constantes solas.' },
        { t: 'mc', p: 'Aplicando $y\'(0)=0$ a $y\'=2C_1e^{2x}-3C_2e^{-3x}$ obtenés',
          o: ['$0=2C_1-3C_2$', '$0=C_1+C_2$', '$0=2C_1+3C_2$', '$0=C_1-C_2$'], r: 0,
          x: 'Reemplazás $x=0$ en la **derivada**, no en $y$. Las exponenciales valen 1 y quedan los coeficientes.' },
        { t: 'hue', p: 'Resolvé el sistema $C_1+C_2=1$, $2C_1-3C_2=0$', tpl: '$C_1=$ ___ y $C_2=$ ___', r: [['3/5', '0.6'], ['2/5', '0.4']],
          x: 'De la primera, $C_1=1-C_2$. Reemplazando: $2-5C_2=0$, entonces $C_2=\\frac{2}{5}$ y $C_1=\\frac{3}{5}$.' },
        { t: 'mc', p: '¿Cuál es la solución particular de $y\'\'+y\'-6y=0$ con $y(0)=1$, $y\'(0)=0$?',
          o: ['$y=\\dfrac{3}{5}e^{2x}+\\dfrac{2}{5}e^{-3x}$', '$y=\\dfrac{2}{5}e^{2x}+\\dfrac{3}{5}e^{-3x}$', '$y=e^{2x}+e^{-3x}$', '$y=\\dfrac{3}{5}e^{2x}-\\dfrac{2}{5}e^{-3x}$'], r: 0,
          x: 'Se reemplazan los valores hallados. Verificá: $y(0)=\\frac{3}{5}+\\frac{2}{5}=1$ ✓' },
        { t: 'ord', p: 'Ordená el método con condiciones iniciales',
          o: ['Escribir la ecuación característica y hallar las raíces', 'Escribir la solución general con $C_1$ y $C_2$', 'Derivar la solución general', 'Reemplazar las dos condiciones y armar el sistema', 'Resolver el sistema y escribir la particular'],
          x: 'Derivar va **antes** de reemplazar: si no, no tenés dónde meter la condición sobre $y\'$.' },
        { t: 'vf', p: 'La condición $y\'(0)=0$ se reemplaza en la solución general $y$.', r: false,
          x: 'Se reemplaza en la **derivada** $y\'$. Es el error más común de esta lección.' },
        { t: 'mc', p: 'Para $y=C_1e^{rx}+C_2xe^{rx}$ (caso 2), la derivada del segundo término es',
          o: ['$C_2\\left(e^{rx}+rxe^{rx}\\right)$', '$C_2\\,r\\,x\\,e^{rx}$', '$C_2e^{rx}$', '$C_2\\,r\\,e^{rx}$'], r: 0,
          x: 'Es un producto: derivada del primero ($1$) por el segundo, más el primero por la derivada del segundo ($re^{rx}$).' },
        { t: 'mc', p: 'Si $y(0)=2$ y la general es $y=C_1\\cos x+C_2\\sen x$, ¿cuánto vale $C_1$?',
          o: ['$2$', '$0$', '$-2$', 'No se puede saber'], r: 0,
          x: 'Con $x=0$: $\\cos 0=1$ y $\\sen 0=0$, así que $2=C_1\\cdot 1+C_2\\cdot 0=C_1$.' },
      ],
    },
  ],
});
