/* Unidad 6 — Transformada de Laplace
   Guía Teórica N° 2 y Práctica N° 3 del cuadernillo + clases del 13/08, 20/08 y 10/09. */
(window.__UNIDADES = window.__UNIDADES || []).push({
  id: 'u6',
  n: 6,
  titulo: 'Transformada de Laplace',
  glifo: 'ℒ',
  resumen: 'Convertir una ecuación diferencial en una ecuación algebraica, resolverla y volver.',
  lecciones: [

    /* ------------------------------------------------------------------ */
    {
      id: 'u6l1',
      titulo: 'La definición',
      objetivo: 'Entender qué hace la transformada y calcularla por integral.',
      teoria: [
        { p: 'Ya viste dos transformaciones: derivar e integrar convierten una función en otra. La **transformada de Laplace** hace lo mismo, pero además cambia de variable: entra una función de $t$ y sale una función de $s$.' },
        { def: ['Transformada de Laplace', 'Para $f$ definida en $t\\ge 0$: $$\\mathcal{L}\\{f(t)\\}=\\int_{0}^{\\infty} e^{-st}f(t)\\,dt = F(s)$$'] },
        { tabla: [['Nombre', 'Qué es'], [
          ['$f(t)$', 'Función original'],
          ['$F(s)$', 'Función imagen, o transformada'],
          ['$e^{-st}$', 'Núcleo de la transformada'],
        ]] },
        { p: 'La transformada **existe** si esa integral impropia converge, es decir si el límite existe. Por eso cada fila de la tabla viene con una condición sobre $s$.' },
        { ej: ['Calcular $\\mathcal{L}\\{1\\}$ por definición', [
          'Reemplazo $f(t)=1$: $\;\\mathcal{L}\\{1\\}=\\displaystyle\\int_{0}^{\\infty}e^{-st}\\,dt$',
          'Es impropia, así que la escribo como límite:',
          '$\;=\\lim_{b\\to\\infty}\\displaystyle\\int_{0}^{b}e^{-st}\\,dt$',
          'Integro: $\;=\\lim_{b\\to\\infty}\\left[-\\dfrac{1}{s}e^{-st}\\right]_{0}^{b}=\\lim_{b\\to\\infty}\\left(-\\dfrac{1}{s}e^{-sb}+\\dfrac{1}{s}\\right)$',
          'Si $s>0$, entonces $e^{-sb}\\to 0$ cuando $b\\to\\infty$',
          'Resultado: $\;\\mathcal{L}\\{1\\}=\\dfrac{1}{s}\;$ siempre que $s>0$',
        ]] },
        { ojo: 'Si $s<0$ la integral **diverge** y la transformada no existe. Por eso la condición $s>0$ no es un detalle: es parte del resultado.' },
        { h: 'Condiciones de existencia' },
        { p: 'La transformada existe si $f$ es **continua por tramos** en $[0,\\infty)$ y de **orden exponencial**, es decir que no crece más rápido que una exponencial: $|f(t)|\\le M\\,e^{ct}$.' },
        { def: ['Consecuencia útil', 'Si $F(s)=\\mathcal{L}\\{f(t)\\}$ existe, entonces $$\\lim_{s\\to\\infty}F(s)=0$$ Si una candidata a transformada no tiende a cero, no puede ser una transformada.'] },
        { truco: 'En los parciales, calcular por definición aparece sólo en uno o dos ejercicios (como $\\mathcal{L}\\{t\\}$). Para todo lo demás se usa la tabla, que es lo que viene después.' },
      ],
      formulas: [
        ['Definición', '\\mathcal{L}\\{f(t)\\}=\\int_{0}^{\\infty}e^{-st}f(t)\\,dt=F(s)'],
        ['Primer resultado', '\\mathcal{L}\\{1\\}=\\frac{1}{s}\\quad (s>0)'],
        ['Orden exponencial', '|f(t)|\\le M\\,e^{ct}'],
        ['Test', '\\lim_{s\\to\\infty}F(s)=0'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Cuál es la definición de la transformada de Laplace?',
          o: ['$\\displaystyle\\int_{0}^{\\infty}e^{-st}f(t)\\,dt$', '$\\displaystyle\\int_{0}^{\\infty}e^{st}f(t)\\,dt$', '$\\displaystyle\\int_{-\\infty}^{\\infty}e^{-st}f(t)\\,dt$', '$\\displaystyle\\int_{0}^{\\infty}e^{-st}f(s)\\,ds$'], r: 0,
          x: 'Los tres detalles que importan: el exponente es **negativo**, la integral arranca en $0$, y se integra respecto de $t$.' },
        { t: 'mc', p: 'La transformada convierte una función de $t$ en',
          o: ['Una función de $s$', 'Un número', 'Otra función de $t$', 'Una derivada'], r: 0,
          x: 'Al integrar respecto de $t$ entre límites fijos, la $t$ desaparece y queda sólo la $s$.' },
        { t: 'mc', p: '¿Cómo se llama $e^{-st}$ dentro de la definición?',
          o: ['Núcleo de la transformada', 'Función imagen', 'Factor de integración', 'Función original'], r: 0,
          x: 'Es el núcleo. La función imagen es $F(s)$ y la original es $f(t)$.' },
        { t: 'mc', p: 'Al calcular $\\mathcal{L}\\{1\\}$ por definición, ¿por qué hay que escribirla como límite?',
          o: ['Porque es una integral impropia (el límite superior es infinito)', 'Porque la función no es continua', 'Porque $s$ puede ser negativo', 'Porque hay que derivar primero'], r: 0,
          x: 'Todo integral con un extremo infinito se define como el límite de una integral con extremo finito.' },
        { t: 'in', p: '¿Cuánto vale $\\mathcal{L}\\{1\\}$?', r: ['1/s'], ph: 'En función de s', teclas: ['/', 's'],
          x: '$\\mathcal{L}\\{1\\}=\\frac{1}{s}$, válido para $s>0$.' },
        { t: 'mc', p: '¿Bajo qué condición converge la integral de $\\mathcal{L}\\{1\\}$?',
          o: ['$s>0$', '$s<0$', '$s=0$', 'Siempre converge'], r: 0,
          x: 'Hace falta que $e^{-sb}\\to 0$ cuando $b\\to\\infty$, y eso pasa sólo si el exponente es negativo, o sea $s>0$.' },
        { t: 'vf', p: 'Si $f$ es continua por tramos y de orden exponencial, su transformada existe.', r: true,
          x: 'Son las condiciones **suficientes** de existencia que da el teorema del cuadernillo.' },
        { t: 'mc', p: '¿Qué le pasa a $F(s)$ cuando $s\\to\\infty$?',
          o: ['Tiende a cero', 'Tiende a infinito', 'Tiende a uno', 'Queda constante'], r: 0,
          x: 'Toda transformada tiende a cero. Sirve como control: si te dio algo que no tiende a cero, revisá la cuenta.' },
        { t: 'mc', p: '¿Cuál de estas NO puede ser una transformada de Laplace?', fijo: true,
          o: ['$F(s)=s^{2}$', '$F(s)=\\dfrac{1}{s}$', '$F(s)=\\dfrac{1}{s-3}$', '$F(s)=\\dfrac{s}{s^{2}+4}$'], r: 0,
          x: '$s^{2}$ tiende a infinito, no a cero. Las otras tres tienden a cero y de hecho están todas en la tabla.' },
        { t: 'mc', p: '¿Qué significa que $f$ sea de orden exponencial?',
          o: ['Que existe $M$ y $c$ tales que $|f(t)|\\le M e^{ct}$', 'Que $f$ es una exponencial', 'Que $f$ crece más rápido que cualquier exponencial', 'Que $f$ es continua'], r: 0,
          x: 'Que no crezca más rápido que alguna exponencial. Si creciera más rápido, el $e^{-st}$ no alcanzaría para que la integral converja.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u6l2',
      titulo: 'La tabla',
      objetivo: 'Tener a mano las transformadas básicas y usar la linealidad.',
      teoria: [
        { p: 'Nadie calcula por definición en la práctica. Se usa esta tabla, que es la que tenés que llevar al parcial (o saber de memoria).' },
        { tabla: [['$f(t)$', '$\\mathcal{L}\\{f(t)\\}=F(s)$'], [
          ['$1$', '$\\dfrac{1}{s}$'],
          ['$t$', '$\\dfrac{1}{s^{2}}$'],
          ['$t^{n}$', '$\\dfrac{n!}{s^{n+1}}$'],
          ['$e^{at}$', '$\\dfrac{1}{s-a}$'],
          ['$\\sen(kt)$', '$\\dfrac{k}{s^{2}+k^{2}}$'],
          ['$\\cos(kt)$', '$\\dfrac{s}{s^{2}+k^{2}}$'],
          ['$\\senh(kt)$', '$\\dfrac{k}{s^{2}-k^{2}}$'],
          ['$\\cosh(kt)$', '$\\dfrac{s}{s^{2}-k^{2}}$'],
        ]] },
        { ojo: 'La diferencia entre las trigonométricas y las hiperbólicas es **un solo signo** en el denominador: $s^{2}+k^{2}$ para seno y coseno, $s^{2}-k^{2}$ para las hiperbólicas. Es la confusión más cara de la unidad.' },
        { truco: 'Para distinguir seno de coseno: el **seno** lleva $k$ arriba (la misma letra que está adentro), el **coseno** lleva $s$ arriba. "Coseno con ese."' },
        { h: 'Linealidad' },
        { p: 'La transformada es lineal, igual que la derivada y la integral:' },
        { mat: '\\mathcal{L}\\{a\\,f(t)+b\\,g(t)\\}=a\\,\\mathcal{L}\\{f(t)\\}+b\\,\\mathcal{L}\\{g(t)\\}' },
        { ej: ['Transformar $f(t)=1+e^{-t}$', [
          'Por linealidad, transformo cada término por separado:',
          '$\;\\mathcal{L}\\{1\\}=\\dfrac{1}{s}$',
          '$\;\\mathcal{L}\\{e^{-t}\\}=\\dfrac{1}{s-(-1)}=\\dfrac{1}{s+1}$',
          'Resultado: $\;\\dfrac{1}{s}+\\dfrac{1}{s+1}$',
        ]] },
        { ej: ['Transformar $13\\,\\sen(2t)$  — del ejercicio de la clase del 10/09', [
          'La constante sale afuera: $\;13\\,\\mathcal{L}\\{\\sen(2t)\\}$',
          'De la tabla con $k=2$: $\;\\mathcal{L}\\{\\sen(2t)\\}=\\dfrac{2}{s^{2}+2^{2}}=\\dfrac{2}{s^{2}+4}$',
          'Resultado: $\;\\dfrac{26}{s^{2}+4}$',
        ]] },
        { ojo: 'En $\\mathcal{L}\\{e^{at}\\}=\\dfrac{1}{s-a}$ el signo se **invierte**. Si $f(t)=e^{-3t}$, entonces $a=-3$ y la transformada es $\\dfrac{1}{s+3}$.' },
        { h: 'Una propiedad extra' },
        { p: 'La traslación combina exponencial con potencia, y aparece cuando hay raíces repetidas:' },
        { mat: '\\mathcal{L}\\{t^{m}e^{at}\\}=\\frac{m!}{(s-a)^{m+1}}' },
      ],
      formulas: [
        ['Constante', '\\mathcal{L}\\{1\\}=\\frac{1}{s}'],
        ['Potencia', '\\mathcal{L}\\{t^{n}\\}=\\frac{n!}{s^{n+1}}'],
        ['Exponencial', '\\mathcal{L}\\{e^{at}\\}=\\frac{1}{s-a}'],
        ['Seno', '\\mathcal{L}\\{\\sen kt\\}=\\frac{k}{s^{2}+k^{2}}'],
        ['Coseno', '\\mathcal{L}\\{\\cos kt\\}=\\frac{s}{s^{2}+k^{2}}'],
        ['Hiperbólicas', '\\mathcal{L}\\{\\senh kt\\}=\\frac{k}{s^{2}-k^{2}} \\quad \\mathcal{L}\\{\\cosh kt\\}=\\frac{s}{s^{2}-k^{2}}'],
        ['Traslación', '\\mathcal{L}\\{t^{m}e^{at}\\}=\\frac{m!}{(s-a)^{m+1}}'],
      ],
      ejercicios: [
        { t: 'par', p: 'Emparejá cada función con su transformada',
          o: [['$1$', '$\\dfrac{1}{s}$'], ['$t$', '$\\dfrac{1}{s^{2}}$'], ['$e^{at}$', '$\\dfrac{1}{s-a}$'], ['$\\cos(kt)$', '$\\dfrac{s}{s^{2}+k^{2}}$']],
          x: 'Las cuatro filas que más se usan. El coseno es el que lleva $s$ en el numerador.' },
        { t: 'mc', p: '$\\mathcal{L}\\{\\sen(2t)\\}$ es igual a',
          o: ['$\\dfrac{2}{s^{2}+4}$', '$\\dfrac{s}{s^{2}+4}$', '$\\dfrac{2}{s^{2}-4}$', '$\\dfrac{2}{s^{2}+2}$'], r: 0,
          x: 'Con $k=2$: arriba va $k=2$ y abajo $s^{2}+k^{2}=s^{2}+4$. Ojo que se eleva el $k$ al cuadrado.' },
        { t: 'mc', p: '$\\mathcal{L}\\{e^{-3t}\\}$ es igual a',
          o: ['$\\dfrac{1}{s+3}$', '$\\dfrac{1}{s-3}$', '$\\dfrac{-3}{s}$', '$\\dfrac{1}{s+3^{2}}$'], r: 0,
          x: 'La fórmula es $\\frac{1}{s-a}$ con $a=-3$: $\\frac{1}{s-(-3)}=\\frac{1}{s+3}$. El signo se da vuelta.' },
        { t: 'mc', p: '$\\mathcal{L}\\{t^{3}\\}$ es igual a',
          o: ['$\\dfrac{6}{s^{4}}$', '$\\dfrac{3}{s^{4}}$', '$\\dfrac{3!}{s^{3}}$', '$\\dfrac{1}{s^{3}}$'], r: 0,
          x: '$\\frac{n!}{s^{n+1}}$ con $n=3$: arriba $3!=6$ y abajo $s^{4}$.' },
        { t: 'in', p: '¿Cuánto vale $4!$?', r: ['24'], ph: 'Un número',
          x: '$4\\cdot 3\\cdot 2\\cdot 1=24$. Así que $\\mathcal{L}\\{t^{4}\\}=\\frac{24}{s^{5}}$.' },
        { t: 'mc', p: '$\\mathcal{L}\\{1+e^{-t}\\}$ es igual a',
          o: ['$\\dfrac{1}{s}+\\dfrac{1}{s+1}$', '$\\dfrac{1}{s}+\\dfrac{1}{s-1}$', '$\\dfrac{1}{s(s+1)}$', '$\\dfrac{2}{s+1}$'], r: 0,
          x: 'Por linealidad se transforma término a término. Y $e^{-t}$ tiene $a=-1$, así que da $\\frac{1}{s+1}$.' },
        { t: 'mc', p: '¿Cuál es la diferencia entre $\\mathcal{L}\\{\\sen kt\\}$ y $\\mathcal{L}\\{\\senh kt\\}$?',
          o: ['El signo del denominador: $s^{2}+k^{2}$ contra $s^{2}-k^{2}$', 'El numerador', 'Ninguna, son iguales', 'El exponente'], r: 0,
          x: 'Las trigonométricas llevan suma, las hiperbólicas resta. Es lo único que cambia y es lo que más se confunde.' },
        { t: 'in', p: '$\\mathcal{L}\\{13\\,\\sen(2t)\\}=\\dfrac{k}{s^{2}+4}$. ¿Cuánto vale $k$?', r: ['26'], ph: 'Un número',
          x: 'La constante $13$ sale por linealidad y multiplica al $2$ del numerador: $13\\cdot 2=26$.' },
        { t: 'mc', p: '$\\mathcal{L}\\{t^{2}e^{4t}\\}$ es igual a',
          o: ['$\\dfrac{2}{(s-4)^{3}}$', '$\\dfrac{2}{s^{3}}\\cdot\\dfrac{1}{s-4}$', '$\\dfrac{2!}{(s+4)^{3}}$', '$\\dfrac{1}{(s-4)^{2}}$'], r: 0,
          x: 'Propiedad de traslación: $\\frac{m!}{(s-a)^{m+1}}$ con $m=2$ y $a=4$. Arriba $2!=2$ y abajo $(s-4)^{3}$.' },
        { t: 'vf', p: 'La transformada de Laplace es lineal.', r: true,
          x: 'Sí: $\\mathcal{L}\\{af+bg\\}=a\\mathcal{L}\\{f\\}+b\\mathcal{L}\\{g\\}$, siempre que las dos converjan. Por eso se puede transformar término a término.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u6l3',
      titulo: 'Transformada inversa',
      objetivo: 'Volver de F(s) a f(t), acomodando la expresión para que entre en la tabla.',
      teoria: [
        { def: ['Transformada inversa', 'Si $\\mathcal{L}\\{f(t)\\}=F(s)$, entonces $$f(t)=\\mathcal{L}^{-1}\\{F(s)\\}$$ Es leer la tabla de derecha a izquierda.'] },
        { tabla: [['$F(s)$', '$\\mathcal{L}^{-1}\\{F(s)\\}$'], [
          ['$\\dfrac{1}{s}$', '$1$'],
          ['$\\dfrac{n!}{s^{n+1}}$', '$t^{n}$'],
          ['$\\dfrac{1}{s-a}$', '$e^{at}$'],
          ['$\\dfrac{k}{s^{2}+k^{2}}$', '$\\sen(kt)$'],
          ['$\\dfrac{s}{s^{2}+k^{2}}$', '$\\cos(kt)$'],
          ['$\\dfrac{k}{s^{2}-k^{2}}$', '$\\senh(kt)$'],
          ['$\\dfrac{s}{s^{2}-k^{2}}$', '$\\cosh(kt)$'],
        ]] },
        { h: 'Acomodar el numerador' },
        { p: 'El problema típico es que la expresión **casi** entra en la tabla pero le falta un número arriba. La solución es multiplicar y dividir por lo que haga falta.' },
        { ej: ['$\\mathcal{L}^{-1}\\left\\{\\dfrac{6}{s^{2}+4}\\right\\}$', [
          'La tabla del seno con $k=2$ pide un $2$ arriba, y hay un $6$',
          'Saco factor: $\;\\dfrac{6}{s^{2}+4}=3\\cdot\\dfrac{2}{s^{2}+4}$',
          'Ahora sí es tabla: $\;\\mathcal{L}^{-1}=3\\,\\sen(2t)$',
        ]] },
        { truco: 'Para el seno: mirá el $k^{2}$ del denominador, sacale raíz para obtener $k$, y arreglá el numerador para que quede ese $k$ exacto. El resto queda como constante multiplicando.' },
        { h: 'Fracciones parciales' },
        { p: 'Cuando $F(s)$ es un cociente de polinomios en $s$ que no está en la tabla, hay que **descomponerlo en fracciones simples** — exactamente el método de la unidad 0, pero con $s$ en vez de $x$.' },
        { ej: ['$\\mathcal{L}^{-1}\\left\\{\\dfrac{50+6s^{2}}{(s^{2}+4)(s+3)}\\right\\}$  — del ejercicio de la clase del 10/09', [
          'El denominador tiene un factor lineal y uno cuadrático irreducible → caso 3:',
          '$\;\\dfrac{50+6s^{2}}{(s^{2}+4)(s+3)}=\\dfrac{A}{s+3}+\\dfrac{Bs+C}{s^{2}+4}$',
          'Multiplico: $\;50+6s^{2}=A(s^{2}+4)+(s+3)(Bs+C)$',
          'Igualo coeficientes: $\;s^{2}: 6=A+B\;$, $\;s^{1}: 0=C+3B\;$, $\;s^{0}: 50=4A+3C$',
          'Resolviendo el sistema: $\;A=8$, $\;B=-2$, $\;C=6$',
          'Queda: $\;\\dfrac{8}{s+3}+\\dfrac{-2s+6}{s^{2}+4}$',
          'Antitransformo cada pedazo: $\;8e^{-3t}-2\\cos(2t)+3\\,\\sen(2t)$',
        ]] },
        { ojo: 'En el último paso, $\\dfrac{6}{s^{2}+4}$ se escribe como $3\\cdot\\dfrac{2}{s^{2}+4}$ para que entre en la fila del seno. Ese ajuste del numerador es el que más se olvida.' },
      ],
      formulas: [
        ['Inversa', 'f(t)=\\mathcal{L}^{-1}\\{F(s)\\}'],
        ['Exponencial', '\\mathcal{L}^{-1}\\left\\{\\frac{1}{s-a}\\right\\}=e^{at}'],
        ['Seno', '\\mathcal{L}^{-1}\\left\\{\\frac{k}{s^{2}+k^{2}}\\right\\}=\\sen(kt)'],
        ['Coseno', '\\mathcal{L}^{-1}\\left\\{\\frac{s}{s^{2}+k^{2}}\\right\\}=\\cos(kt)'],
      ],
      ejercicios: [
        { t: 'mc', p: '$\\mathcal{L}^{-1}\\left\\{\\dfrac{1}{s+3}\\right\\}$ es igual a',
          o: ['$e^{-3t}$', '$e^{3t}$', '$3e^{-t}$', '$\\dfrac{1}{3}e^{-3t}$'], r: 0,
          x: 'La tabla dice $\\frac{1}{s-a}\\to e^{at}$. Acá $s+3=s-(-3)$, así que $a=-3$.' },
        { t: 'mc', p: '$\\mathcal{L}^{-1}\\left\\{\\dfrac{s}{s^{2}+4}\\right\\}$ es igual a',
          o: ['$\\cos(2t)$', '$\\sen(2t)$', '$\\cosh(2t)$', '$2\\cos(2t)$'], r: 0,
          x: 'Numerador $s$ → coseno. Y $k^{2}=4$ da $k=2$.' },
        { t: 'mc', p: '$\\mathcal{L}^{-1}\\left\\{\\dfrac{6}{s^{2}+4}\\right\\}$ es igual a',
          o: ['$3\\,\\sen(2t)$', '$6\\,\\sen(2t)$', '$\\sen(6t)$', '$6\\cos(2t)$'], r: 0,
          x: 'La fila del seno necesita $k=2$ arriba. Escribís $\\frac{6}{s^{2}+4}=3\\cdot\\frac{2}{s^{2}+4}$ y el $3$ queda multiplicando.' },
        { t: 'mc', p: '$\\mathcal{L}^{-1}\\left\\{\\dfrac{2}{s^{3}}\\right\\}$ es igual a',
          o: ['$t^{2}$', '$2t^{2}$', '$t^{3}$', '$\\dfrac{t^{2}}{2}$'], r: 0,
          x: 'La fila es $\\frac{n!}{s^{n+1}}\\to t^{n}$. Con $s^{3}$ tenemos $n+1=3$, o sea $n=2$, y arriba hace falta $2!=2$, que es justo lo que hay.' },
        { t: 'in', p: 'Para antitransformar $\\dfrac{5}{s^{2}+9}$ necesitás sacar factor: $\\dfrac{5}{s^{2}+9}=k\\cdot\\dfrac{3}{s^{2}+9}$. ¿Cuánto vale $k$?', r: ['5/3'], ph: 'Una fracción', teclas: ['/'],
          x: '$k^{2}=9$ da $k=3$, así que arriba hace falta un $3$. Como hay un $5$: $5=\\frac{5}{3}\\cdot 3$. El resultado es $\\frac{5}{3}\\sen(3t)$.' },
        { t: 'mc', p: '¿Qué descomposición corresponde para $\\dfrac{50+6s^{2}}{(s^{2}+4)(s+3)}$?',
          o: ['$\\dfrac{A}{s+3}+\\dfrac{Bs+C}{s^{2}+4}$', '$\\dfrac{A}{s+3}+\\dfrac{B}{s^{2}+4}$', '$\\dfrac{A}{s+3}+\\dfrac{B}{s+2}+\\dfrac{C}{s-2}$', '$\\dfrac{As+B}{s+3}+\\dfrac{C}{s^{2}+4}$'], r: 0,
          x: '$s^{2}+4$ no tiene raíces reales, así que arriba va un numerador lineal. Es el caso 3 de la unidad 0.' },
        { t: 'hue', p: 'De $50+6s^{2}=A(s^{2}+4)+(s+3)(Bs+C)$, igualando coeficientes:', tpl: '$A=$ ___ , $B=$ ___ , $C=$ ___',
          r: [['8'], ['-2'], ['6']],
          x: 'El sistema es $6=A+B$, $0=C+3B$, $50=4A+3C$. Da $A=8$, $B=-2$, $C=6$. Verificá: $8-2=6$ ✓, $6+3(-2)=0$ ✓, $32+18=50$ ✓' },
        { t: 'mc', p: 'Antitransformá $\\dfrac{8}{s+3}+\\dfrac{-2s+6}{s^{2}+4}$',
          o: ['$8e^{-3t}-2\\cos(2t)+3\\,\\sen(2t)$', '$8e^{3t}-2\\cos(2t)+6\\,\\sen(2t)$', '$8e^{-3t}-2\\,\\sen(2t)+3\\cos(2t)$', '$8e^{-3t}-2\\cos(2t)+6\\,\\sen(2t)$'], r: 0,
          x: 'El $-2s$ da coseno; el $6$ se escribe $3\\cdot 2$ para entrar en la fila del seno. La última opción se olvida ese ajuste.' },
        { t: 'ord', p: 'Ordená el método para antitransformar un cociente',
          o: ['Factorizar el denominador', 'Decidir el caso y proponer la descomposición', 'Hallar las constantes', 'Ajustar los numeradores para que entren en la tabla', 'Antitransformar cada pedazo'],
          x: 'El paso 4 es el que distingue un ejercicio bien hecho de uno casi bien hecho.' },
        { t: 'vf', p: 'La descomposición en fracciones parciales de Laplace es el mismo método que el de la unidad de integrales.', r: true,
          x: 'Exactamente el mismo, con $s$ en vez de $x$. Por eso conviene tener aceitados los tres casos.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u6l4',
      titulo: 'Transformada de derivadas',
      objetivo: 'Transformar y\' e y\'\' metiendo las condiciones iniciales en la cuenta.',
      teoria: [
        { p: 'Acá está la razón de ser de todo esto. La transformada convierte **derivadas en multiplicaciones**, y de paso se come las condiciones iniciales.' },
        { mat: '\\mathcal{L}\\{y\'\\} = s\\,F(s) - f(0)' },
        { mat: '\\mathcal{L}\\{y\'\'\\} = s^{2}F(s) - s\\,f(0) - f\'(0)' },
        { p: 'Donde $F(s)=\\mathcal{L}\\{y\\}$. Fijate el patrón: cada derivada agrega una potencia de $s$ y resta un valor inicial.' },
        { def: ['Lo importante', 'Las condiciones iniciales **entran solas** en la ecuación transformada. No hay que resolver primero la general y después armar un sistema, como en la unidad 5.'] },
        { truco: 'Para acordarse de $\\mathcal{L}\\{y\'\'\\}$: los coeficientes de $s$ van bajando. $s^{2}F(s)$, después $s\\cdot f(0)$, después $f\'(0)$ sin $s$. Y todos los términos después del primero van **restando**.' },
        { h: 'Un ejemplo de aplicación directa' },
        { ej: ['Transformar $\\dfrac{dy}{dt}+3y=13\\,\\sen(2t)$ con $y(0)=6$', [
          'Aplico $\\mathcal{L}$ a los dos miembros y uso linealidad:',
          '$\;\\mathcal{L}\\{y\'\\}+3\\,\\mathcal{L}\\{y\\}=13\\,\\mathcal{L}\\{\\sen(2t)\\}$',
          'Uso la propiedad de la derivada y la tabla:',
          '$\;\\big[s\\,F(s)-y(0)\\big]+3F(s)=13\\cdot\\dfrac{2}{s^{2}+4}$',
          'Reemplazo la condición inicial $y(0)=6$:',
          '$\;s\\,F(s)-6+3F(s)=\\dfrac{26}{s^{2}+4}$',
          'Y ya está: quedó una ecuación **algebraica** en $F(s)$',
        ]] },
        { ojo: 'Al transformar $y\'\'$ **no** te olvides del término $-s\\,f(0)$. Si las condiciones son cero desaparece, pero cuando no lo son es el error más frecuente.' },
        { h: 'El caso con condiciones nulas' },
        { p: 'Si $y(0)=0$ e $y\'(0)=0$, las fórmulas se simplifican muchísimo:' },
        { mat: '\\mathcal{L}\\{y\'\\}=s\\,F(s) \\qquad \\mathcal{L}\\{y\'\'\\}=s^{2}F(s)' },
      ],
      formulas: [
        ['Primera derivada', '\\mathcal{L}\\{y\'\\}=s\\,F(s)-f(0)'],
        ['Segunda derivada', '\\mathcal{L}\\{y\'\'\\}=s^{2}F(s)-s\\,f(0)-f\'(0)'],
        ['Notación', 'F(s)=\\mathcal{L}\\{y(t)\\}'],
      ],
      ejercicios: [
        { t: 'mc', p: '$\\mathcal{L}\\{y\'\\}$ es igual a',
          o: ['$s\\,F(s)-f(0)$', '$s\\,F(s)+f(0)$', '$F(s)-f(0)$', '$s\\,F(s)$'], r: 0,
          x: 'Una potencia de $s$ multiplicando, menos el valor inicial de la función.' },
        { t: 'mc', p: '$\\mathcal{L}\\{y\'\'\\}$ es igual a',
          o: ['$s^{2}F(s)-s\\,f(0)-f\'(0)$', '$s^{2}F(s)-f(0)-f\'(0)$', '$s^{2}F(s)-s\\,f\'(0)-f(0)$', '$s^{2}F(s)$'], r: 0,
          x: 'El $s$ acompaña a $f(0)$, no a $f\'(0)$. La tercera opción los tiene cambiados.' },
        { t: 'mc', p: 'Si $y(0)=0$ e $y\'(0)=0$, ¿cuánto vale $\\mathcal{L}\\{y\'\'\\}$?',
          o: ['$s^{2}F(s)$', '$s^{2}F(s)-s$', '$0$', '$F(s)$'], r: 0,
          x: 'Los dos términos con condiciones iniciales se anulan y queda sólo $s^{2}F(s)$.' },
        { t: 'mc', p: 'Transformando $y\'+3y=13\\,\\sen(2t)$ con $y(0)=6$, queda',
          o: ['$sF(s)-6+3F(s)=\\dfrac{26}{s^{2}+4}$', '$sF(s)+6+3F(s)=\\dfrac{26}{s^{2}+4}$', '$sF(s)-6+3F(s)=\\dfrac{13}{s^{2}+4}$', '$s^{2}F(s)-6+3F(s)=\\dfrac{26}{s^{2}+4}$'], r: 0,
          x: 'Tres cosas: la condición inicial va **restando**, la constante 13 multiplica al 2 del seno, y es primera derivada (una sola potencia de $s$).' },
        { t: 'in', p: 'Si $y(0)=6$, en $\\mathcal{L}\\{y\'\\}=sF(s)-f(0)$, ¿qué número reemplaza a $f(0)$?', r: ['6'], ph: 'Un número',
          x: '$f(0)$ es justamente $y(0)$, o sea $6$.' },
        { t: 'vf', p: 'Con Laplace, las condiciones iniciales se usan al final, después de hallar la solución general.', r: false,
          x: 'Al revés: entran al principio, en el momento de transformar. Esa es una de las grandes ventajas del método.' },
        { t: 'mc', p: '¿Por qué la transformada sirve para resolver ecuaciones diferenciales?',
          o: ['Porque convierte derivadas en multiplicaciones por $s$', 'Porque elimina las constantes', 'Porque simplifica los logaritmos', 'Porque hace la ecuación homogénea'], r: 0,
          x: 'Al pasar al dominio de $s$, derivar se vuelve multiplicar. La ecuación diferencial se convierte en una ecuación algebraica común.' },
        { t: 'mc', p: 'Transformá $y\'\'+4y\'+4y=0$ con $y(0)=0$, $y\'(0)=0$',
          o: ['$F(s)\\left[s^{2}+4s+4\\right]=0$', '$F(s)\\left[s^{2}+4s\\right]=0$', '$s^{2}F(s)+4sF(s)=4$', '$F(s)\\left[s^{2}+4s+4\\right]=1$'], r: 0,
          x: 'Con condiciones nulas queda $s^{2}F+4sF+4F=0$, y sacando factor común $F(s)$ aparece el mismo polinomio característico de la unidad 5.' },
        { t: 'hue', p: 'Completá la propiedad', tpl: '$\\mathcal{L}\\{y\'\'\\}=s^{2}F(s)-s\\,f(0)-$ ___', r: [["f'(0)", 'f´(0)', "y'(0)"]],
          x: 'El último término es la derivada evaluada en cero, sin ningún $s$ delante.' },
        { t: 'mc', p: 'En la ecuación transformada, la incógnita pasa a ser',
          o: ['$F(s)$', '$y(t)$', '$s$', '$f(0)$'], r: 0,
          x: 'Se despeja $F(s)$ como si fuera una $x$ cualquiera, y recién después se antitransforma para recuperar $y(t)$.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u6l5',
      titulo: 'Resolver una EDO con Laplace',
      objetivo: 'Encadenar todo: transformar, despejar, descomponer y antitransformar.',
      teoria: [
        { p: 'Este es el ejercicio completo, el que cae en el parcial. Son siempre los mismos cuatro movimientos.' },
        { num: [
          '**Transformar** los dos miembros, metiendo las condiciones iniciales',
          '**Despejar $F(s)$** (sacar factor común y pasar dividiendo)',
          '**Descomponer** en fracciones parciales si hace falta',
          '**Antitransformar** cada pedazo con la tabla',
        ] },
        { ej: ['$\\dfrac{dy}{dt}+3y=13\\,\\sen(2t)$ con $y(0)=6$  — el ejercicio completo de la clase del 10/09', [
          '**1) Transformo:** $\;s\\,F(s)-6+3F(s)=\\dfrac{26}{s^{2}+4}$',
          '**2) Despejo.** Saco factor común: $\;F(s)\\left[s+3\\right]=\\dfrac{26}{s^{2}+4}+6$',
          'Sumo las fracciones: $\;F(s)\\left[s+3\\right]=\\dfrac{26+6(s^{2}+4)}{s^{2}+4}=\\dfrac{6s^{2}+50}{s^{2}+4}$',
          'Paso dividiendo: $\;F(s)=\\dfrac{6s^{2}+50}{(s^{2}+4)(s+3)}$',
          '**3) Descompongo:** $\;\\dfrac{A}{s+3}+\\dfrac{Bs+C}{s^{2}+4}\;$ con $\;A=8$, $B=-2$, $C=6$',
          '**4) Antitransformo:**',
          '$\;y(t)=8e^{-3t}-2\\cos(2t)+3\\,\\sen(2t)$',
        ]] },
        { truco: 'En el paso 2, cuando haya que sumar una fracción con un número suelto, poné el número sobre el mismo denominador. Es puro común denominador, pero es donde más se equivoca la gente por apuro.' },
        { h: 'Un caso de segundo orden' },
        { ej: ['$y\'\'+4y\'+4y=1+e^{-t}$ con $y(0)=0$, $y\'(0)=0$  — de la clase del 20/08', [
          'Transformo (condiciones nulas, así que no hay términos extra):',
          '$\;s^{2}F(s)+4sF(s)+4F(s)=\\dfrac{1}{s}+\\dfrac{1}{s+1}$',
          'Factor común y suma de fracciones:',
          '$\;F(s)\\left[s^{2}+4s+4\\right]=\\dfrac{(s+1)+s}{s(s+1)}=\\dfrac{2s+1}{s(s+1)}$',
          'El polinomio factoriza: $\;s^{2}+4s+4=(s+2)^{2}$',
          '$\;F(s)=\\dfrac{2s+1}{s(s+1)(s+2)^{2}}$',
          'Ahí aparecen los tres casos juntos: raíces simples ($s$, $s+1$) y una doble ($(s+2)^{2}$):',
          '$\;\\dfrac{A}{s}+\\dfrac{B}{s+1}+\\dfrac{C}{s+2}+\\dfrac{D}{(s+2)^{2}}$',
        ]] },
        { ojo: 'Cuando el denominador tiene un factor al cuadrado, van **dos** fracciones: una con $(s+2)$ y otra con $(s+2)^{2}$. Poner sólo una es el error que más cuesta puntos.' },
        { p: 'Comparado con el método de la unidad 5, Laplace tiene una ventaja enorme: sirve igual cuando el lado derecho **no es cero**. La ecuación característica sólo resuelve homogéneas; Laplace resuelve las dos.' },
      ],
      formulas: [
        ['El esquema', 'y(t) \\xrightarrow{\;\\mathcal{L}\;} F(s) \\xrightarrow{\;\\text{álgebra}\;} F(s) \\xrightarrow{\;\\mathcal{L}^{-1}\;} y(t)'],
        ['Raíz doble en $s$', '\\frac{P(s)}{(s+a)^{2}}=\\frac{C}{s+a}+\\frac{D}{(s+a)^{2}}'],
        ['Traslación para antitransformar', '\\mathcal{L}^{-1}\\left\\{\\frac{1}{(s-a)^{2}}\\right\\}=t\\,e^{at}'],
      ],
      ejercicios: [
        { t: 'ord', p: 'Ordená el método de Laplace para resolver una EDO',
          o: ['Transformar los dos miembros usando las condiciones iniciales', 'Sacar factor común $F(s)$ y despejarla', 'Descomponer en fracciones parciales', 'Ajustar los numeradores para la tabla', 'Antitransformar y escribir $y(t)$'],
          x: 'Siempre los mismos pasos. Lo que cambia de un ejercicio a otro es sólo la descomposición.' },
        { t: 'mc', p: 'De $sF(s)-6+3F(s)=\\dfrac{26}{s^{2}+4}$, sacando factor común queda',
          o: ['$F(s)\\left[s+3\\right]=\\dfrac{26}{s^{2}+4}+6$', '$F(s)\\left[s+3\\right]=\\dfrac{26}{s^{2}+4}-6$', '$F(s)\\left[s-3\\right]=\\dfrac{26}{s^{2}+4}+6$', '$F(s)\\left[s+3\\right]=\\dfrac{26}{s^{2}+4}$'], r: 0,
          x: 'El $-6$ pasa al otro lado **sumando**. Y el factor común de $sF(s)+3F(s)$ es $F(s)(s+3)$.' },
        { t: 'mc', p: '$\\dfrac{26}{s^{2}+4}+6$ escrito como una sola fracción es',
          o: ['$\\dfrac{6s^{2}+50}{s^{2}+4}$', '$\\dfrac{32}{s^{2}+4}$', '$\\dfrac{26+6}{s^{2}+4}$', '$\\dfrac{6s^{2}+26}{s^{2}+4}$'], r: 0,
          x: 'Común denominador: $6=\\frac{6(s^{2}+4)}{s^{2}+4}=\\frac{6s^{2}+24}{s^{2}+4}$. Sumando: $\\frac{26+6s^{2}+24}{s^{2}+4}=\\frac{6s^{2}+50}{s^{2}+4}$.' },
        { t: 'mc', p: 'Entonces $F(s)$ es igual a',
          o: ['$\\dfrac{6s^{2}+50}{(s^{2}+4)(s+3)}$', '$\\dfrac{6s^{2}+50}{s^{2}+4}$', '$\\dfrac{(6s^{2}+50)(s+3)}{s^{2}+4}$', '$\\dfrac{6s^{2}+50}{s+3}$'], r: 0,
          x: 'El corchete $[s+3]$ pasa dividiendo, así que se suma al denominador.' },
        { t: 'mc', p: '¿Cuál es la solución de $y\'+3y=13\\,\\sen(2t)$ con $y(0)=6$?',
          o: ['$y=8e^{-3t}-2\\cos(2t)+3\\,\\sen(2t)$', '$y=8e^{3t}-2\\cos(2t)+3\\,\\sen(2t)$', '$y=6e^{-3t}-2\\cos(2t)+3\\,\\sen(2t)$', '$y=8e^{-3t}+2\\cos(2t)-3\\,\\sen(2t)$'], r: 0,
          x: 'Verificá la condición inicial: $y(0)=8-2\\cdot 1+3\\cdot 0=6$ ✓ Es la mejor forma de controlar el resultado.' },
        { t: 'mc', p: 'Transformando $y\'\'+4y\'+4y=1+e^{-t}$ con condiciones nulas queda',
          o: ['$F(s)\\left[s^{2}+4s+4\\right]=\\dfrac{1}{s}+\\dfrac{1}{s+1}$', '$F(s)\\left[s^{2}+4s+4\\right]=\\dfrac{1}{s}+\\dfrac{1}{s-1}$', '$F(s)\\left[s^{2}+4s\\right]=\\dfrac{1}{s}+\\dfrac{1}{s+1}$', '$F(s)\\left[s+4\\right]=\\dfrac{2s+1}{s(s+1)}$'], r: 0,
          x: 'Con condiciones nulas no aparecen términos sueltos, y el corchete es el polinomio característico.' },
        { t: 'mc', p: '$\\dfrac{1}{s}+\\dfrac{1}{s+1}$ como una sola fracción es',
          o: ['$\\dfrac{2s+1}{s(s+1)}$', '$\\dfrac{2}{s(s+1)}$', '$\\dfrac{1}{s(s+1)}$', '$\\dfrac{2s}{s(s+1)}$'], r: 0,
          x: 'Común denominador $s(s+1)$: arriba queda $(s+1)+s=2s+1$.' },
        { t: 'mc', p: '¿Qué descomposición corresponde para $\\dfrac{2s+1}{s(s+1)(s+2)^{2}}$?',
          o: ['$\\dfrac{A}{s}+\\dfrac{B}{s+1}+\\dfrac{C}{s+2}+\\dfrac{D}{(s+2)^{2}}$', '$\\dfrac{A}{s}+\\dfrac{B}{s+1}+\\dfrac{C}{(s+2)^{2}}$', '$\\dfrac{A}{s}+\\dfrac{B}{s+1}+\\dfrac{Cs+D}{(s+2)^{2}}$', '$\\dfrac{A}{s(s+1)}+\\dfrac{B}{(s+2)^{2}}$'], r: 0,
          x: 'El factor al cuadrado pide dos fracciones: una con exponente 1 y otra con exponente 2.' },
        { t: 'vf', p: 'Laplace también sirve cuando el lado derecho de la ecuación no es cero.', r: true,
          x: 'Esa es su gran ventaja sobre la ecuación característica, que sólo resuelve las homogéneas.' },
        { t: 'mc', p: '¿Cómo verificás rápido que tu solución con Laplace está bien?',
          o: ['Reemplazando $t=0$ y viendo si da la condición inicial', 'Volviendo a transformar', 'Derivando dos veces', 'Comparando con la tabla'], r: 0,
          x: 'Es un control de treinta segundos que detecta la mayoría de los errores de signo y de constantes.' },
      ],
    },
    /* ------------------------------------------------------------------ */
    {
      id: 'u6l6',
      titulo: 'Traslación y tabla completa',
      objetivo: 'Usar la propiedad que corre la s y cerrar la tabla del machete.',
      teoria: [
        { p: 'Falta una propiedad que aparece en el machete de la cátedra y que resuelve sola un montón de ejercicios: la **traslación**.' },
        { def: ['Propiedad de traslación', 'Multiplicar por una exponencial en $t$ equivale a **correr la $s$**: $$\\mathcal{L}\\{e^{at}f(t)\\}=F(s-a)$$ donde $F(s)=\\mathcal{L}\\{f(t)\\}$.'] },
        { p: 'Es decir: buscás la transformada de $f$ como siempre y después reemplazás cada $s$ por $(s-a)$. Nada más.' },
        { ej: ['Deducir $\\mathcal{L}\\{t^{3}e^{t}\\}$', [
          'Primero la transformada de $t^{3}$ sola: $\;\\mathcal{L}\\{t^{3}\\}=\\dfrac{3!}{s^{4}}=\\dfrac{6}{s^{4}}$',
          'Ahora corro la $s$ por $a=1$: cada $s$ pasa a ser $(s-1)$',
          '$\;\\mathcal{L}\\{t^{3}e^{t}\\}=\\dfrac{6}{(s-1)^{4}}$',
        ]] },
        { h: 'Las tres filas que salen de acá' },
        { tabla: [['$f(t)$', '$F(s)$'], [
          ['$t^{n}e^{at}$', '$\\dfrac{n!}{(s-a)^{n+1}}$'],
          ['$e^{at}\\cos(bt)$', '$\\dfrac{s-a}{(s-a)^{2}+b^{2}}$'],
          ['$e^{at}\\sen(bt)$', '$\\dfrac{b}{(s-a)^{2}+b^{2}}$'],
        ]] },
        { truco: 'Fijate el patrón: son las filas de siempre con $s$ cambiada por $(s-a)$. Si te acordás de la tabla básica y de la traslación, no necesitás memorizar estas tres.' },
        { h: 'Al revés: completar cuadrados' },
        { p: 'La traslación se reconoce en el denominador: si ves $(s-a)^{2}+b^{2}$, hay una exponencial escondida. Cuando el denominador viene desarrollado, hay que **completar cuadrados** para que aparezca.' },
        { ej: ['$\\mathcal{L}^{-1}\\left\\{\\dfrac{1}{s^{2}-6s+13}\\right\\}$', [
          'Completo cuadrados: $\;s^{2}-6s+13=(s^{2}-6s+9)+4=(s-3)^{2}+2^{2}$',
          'Reconozco la fila del seno trasladada, con $a=3$ y $b=2$',
          'Le falta el $b=2$ arriba, así que lo acomodo: $\;\\dfrac{1}{2}\\cdot\\dfrac{2}{(s-3)^{2}+2^{2}}$',
          'Antitransformo: $\;\\dfrac{1}{2}e^{3t}\\sen(2t)$',
        ]] },
        { ojo: 'Ese $s^{2}-6s+13$ es el mismo polinomio que en la unidad 5 daba raíces $3\\pm 2i$. No es casualidad: la parte real de la raíz es el $a$ de la exponencial y la parte imaginaria es el $b$ del seno.' },
        { h: 'Lo que falta de la tabla' },
        { p: 'Para tener el machete completo, dos filas más:' },
        { mat: '\\mathcal{L}\\{f\'\'\'(t)\\}=s^{3}F(s)-s^{2}f(0)-s\\,f\'(0)-f\'\'(0)' },
        { p: 'La regla se extiende: cada derivada suma una potencia de $s$ y resta un valor inicial, con las potencias bajando de a una.' },
        { def: ['Delta de Dirac', 'El impulso unitario en $t=k$ tiene transformada $$\\mathcal{L}\\{\\delta(t-k)\\}=e^{-ks}$$ y al revés, $\\mathcal{L}^{-1}\\{e^{-ks}\\}=\\delta(t-k)$.'] },
        { p: 'Y dos triviales que conviene tener a mano: $\\mathcal{L}\\{k\\}=\\dfrac{k}{s}$ para cualquier constante, y $\\mathcal{L}\\{0\\}=0$.' },
      ],
      formulas: [
        ['Traslación', '\\mathcal{L}\\{e^{at}f(t)\\}=F(s-a)'],
        ['Potencia por exponencial', '\\mathcal{L}\\{t^{n}e^{at}\\}=\\frac{n!}{(s-a)^{n+1}}'],
        ['Coseno trasladado', '\\mathcal{L}\\{e^{at}\\cos bt\\}=\\frac{s-a}{(s-a)^{2}+b^{2}}'],
        ['Seno trasladado', '\\mathcal{L}\\{e^{at}\\sen bt\\}=\\frac{b}{(s-a)^{2}+b^{2}}'],
        ['Tercera derivada', '\\mathcal{L}\\{f\'\'\'\\}=s^{3}F(s)-s^{2}f(0)-s\\,f\'(0)-f\'\'(0)'],
        ['Delta de Dirac', '\\mathcal{L}\\{\\delta(t-k)\\}=e^{-ks}'],
        ['Constante', '\\mathcal{L}\\{k\\}=\\frac{k}{s}'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Qué dice la propiedad de traslación?',
          o: ['$\\mathcal{L}\\{e^{at}f(t)\\}=F(s-a)$', '$\\mathcal{L}\\{e^{at}f(t)\\}=F(s)+a$', '$\\mathcal{L}\\{e^{at}f(t)\\}=e^{a}F(s)$', '$\\mathcal{L}\\{e^{at}f(t)\\}=F(s+a)$'], r: 0,
          x: 'Multiplicar por $e^{at}$ en el mundo de $t$ es correr la variable a $(s-a)$ en el mundo de $s$. Ojo con el signo: es **menos** $a$.' },
        { t: 'mc', p: '$\\mathcal{L}\\{t^{3}e^{t}\\}$ es igual a',
          o: ['$\\dfrac{6}{(s-1)^{4}}$', '$\\dfrac{6}{s^{4}}$', '$\\dfrac{6}{(s+1)^{4}}$', '$\\dfrac{3}{(s-1)^{4}}$'], r: 0,
          x: '$\\mathcal{L}\\{t^{3}\\}=\\frac{3!}{s^{4}}=\\frac{6}{s^{4}}$, y con $a=1$ cada $s$ pasa a $(s-1)$.' },
        { t: 'in', p: 'En $\\mathcal{L}\\{t^{n}e^{at}\\}=\\dfrac{n!}{(s-a)^{n+1}}$, si $n=4$, ¿cuánto vale el numerador?', r: ['24'], ph: 'Un número',
          x: '$4!=4\\cdot 3\\cdot 2\\cdot 1=24$.' },
        { t: 'mc', p: '$\\mathcal{L}\\{e^{2t}\\cos(3t)\\}$ es igual a',
          o: ['$\\dfrac{s-2}{(s-2)^{2}+9}$', '$\\dfrac{3}{(s-2)^{2}+9}$', '$\\dfrac{s}{(s-2)^{2}+9}$', '$\\dfrac{s-2}{s^{2}+9}$'], r: 0,
          x: 'Es la fila del coseno con **todas** las $s$ corridas: arriba queda $s-2$, no $s$ pelada.' },
        { t: 'mc', p: '$\\mathcal{L}\\{e^{-t}\\sen(4t)\\}$ es igual a',
          o: ['$\\dfrac{4}{(s+1)^{2}+16}$', '$\\dfrac{4}{(s-1)^{2}+16}$', '$\\dfrac{s+1}{(s+1)^{2}+16}$', '$\\dfrac{4}{s^{2}+16}$'], r: 0,
          x: 'Con $a=-1$, la traslación da $(s-(-1))=(s+1)$. Y arriba va el $b=4$ porque es seno.' },
        { t: 'hue', p: 'Completá cuadrados', tpl: '$s^{2}-6s+13=(s-$ ___ $)^{2}+$ ___', r: [['3'], ['4', '2^2', '2²']],
          x: 'La mitad de $6$ es $3$, y $3^{2}=9$. Como hay $13$, sobra $13-9=4$. Queda $(s-3)^{2}+4$, o sea $(s-3)^{2}+2^{2}$.' },
        { t: 'mc', p: '$\\mathcal{L}^{-1}\\left\\{\\dfrac{1}{s^{2}-6s+13}\\right\\}$ es igual a',
          o: ['$\\dfrac{1}{2}e^{3t}\\sen(2t)$', '$e^{3t}\\sen(2t)$', '$\\dfrac{1}{2}e^{3t}\\cos(2t)$', '$e^{-3t}\\sen(2t)$'], r: 0,
          x: 'Completando cuadrados es $\\frac{1}{(s-3)^{2}+2^{2}}$: seno trasladado con $a=3$, $b=2$. Falta el $2$ arriba, y eso deja el $\\frac{1}{2}$.' },
        { t: 'mc', p: '$\\mathcal{L}\\{f\'\'\'(t)\\}$ es igual a',
          o: ['$s^{3}F(s)-s^{2}f(0)-s\\,f\'(0)-f\'\'(0)$', '$s^{3}F(s)-f(0)-f\'(0)-f\'\'(0)$', '$s^{3}F(s)-s^{2}f\'\'(0)-s\\,f\'(0)-f(0)$', '$s^{3}F(s)$'], r: 0,
          x: 'Las potencias de $s$ bajan de a una mientras el orden de la derivada inicial sube. La tercera opción los tiene al revés.' },
        { t: 'mc', p: '$\\mathcal{L}\\{\\delta(t-k)\\}$ es igual a',
          o: ['$e^{-ks}$', '$e^{ks}$', '$\\dfrac{1}{s-k}$', '$k$'], r: 0,
          x: 'El impulso unitario transforma en una exponencial pura de exponente negativo.' },
        { t: 'in', p: '$\\mathcal{L}\\{7\\}$ es igual a $\\dfrac{k}{s}$. ¿Cuánto vale $k$?', r: ['7'], ph: 'Un número',
          x: 'Por linealidad, la constante sale afuera: $7\\cdot\\mathcal{L}\\{1\\}=\\frac{7}{s}$.' },
        { t: 'vf', p: 'Si en un denominador aparece $(s-a)^{2}+b^{2}$, hay una exponencial multiplicando en la respuesta.', r: true,
          x: 'Sí: ese patrón es la marca de la traslación. La $a$ te da el $e^{at}$ y la $b$ el ángulo del seno o coseno.' },
      ],
    },
  ],
});
