/* Unidad 7 — Series de Fourier
   Guía Teórica N° 3 del cuadernillo (pág. 15) + clase del 27/08. */
(window.__UNIDADES = window.__UNIDADES || []).push({
  id: 'u7',
  n: 7,
  titulo: 'Series de Fourier',
  glifo: '∑',
  resumen: 'Escribir una función periódica como suma infinita de senos y cosenos.',
  lecciones: [

    /* ------------------------------------------------------------------ */
    {
      id: 'u7l1',
      titulo: 'La serie',
      objetivo: 'Entender qué se está armando y reconocer cada pieza.',
      teoria: [
        { p: 'La idea de Fourier es brutal y simple: **cualquier función periódica razonable se puede escribir como una suma infinita de senos y cosenos**. Es la base de todo el procesamiento de señales, de la compresión de audio y de imagen.' },
        { def: ['Serie de Fourier', 'Sea $f(x)$ definida en un intervalo $(-P,\\,P)$ y con período $2P$. Su serie de Fourier es $$f(x)=\\frac{a_0}{2}+\\sum_{m=1}^{\\infty}\\left[a_m\\cos\\left(\\frac{m\\pi x}{P}\\right)+b_m\\,\\sen\\left(\\frac{m\\pi x}{P}\\right)\\right]$$'] },
        { tabla: [['Pieza', 'Qué representa'], [
          ['$\\dfrac{a_0}{2}$', 'El valor promedio de la función en un período'],
          ['$a_m$', 'Cuánto aporta el coseno de frecuencia $m$'],
          ['$b_m$', 'Cuánto aporta el seno de frecuencia $m$'],
          ['$P$', 'La mitad del período'],
          ['$m$', 'El número de armónico: $1, 2, 3, \\ldots$'],
        ]] },
        { ojo: 'Cuidado con $P$: es la **mitad** del período, no el período. Si la función está definida en $(-5,\\,5)$, entonces $P=5$ y el período es $10$. Algunos libros usan $L$ en lugar de $P$: es lo mismo.' },
        { truco: 'El término $\\dfrac{a_0}{2}$ va **dividido por dos**. Es el error de escritura más frecuente: se calcula $a_0$ con la misma fórmula que los demás, pero en la serie entra a la mitad.' },
        { h: 'Los coeficientes' },
        { p: 'Los tres se calculan integrando la función sobre un período completo:' },
        { mat: 'a_0=\\frac{1}{P}\\int_{-P}^{P}f(x)\\,dx' },
        { mat: 'a_m=\\frac{1}{P}\\int_{-P}^{P}f(x)\\cos\\left(\\frac{m\\pi x}{P}\\right)dx' },
        { mat: 'b_m=\\frac{1}{P}\\int_{-P}^{P}f(x)\\,\\sen\\left(\\frac{m\\pi x}{P}\\right)dx' },
        { p: 'Fijate que $a_0$ es simplemente $a_m$ con $m=0$: como $\\cos(0)=1$, el coseno desaparece y queda la integral de $f$ sola.' },
        { def: ['Armónicos', 'Cada valor de $m$ da un armónico. $m=1$ es el fundamental, $m=2$ el segundo armónico, y así. Cuantos más términos sumás, mejor se aproxima la función original.'] },
      ],
      formulas: [
        ['Serie', 'f(x)=\\frac{a_0}{2}+\\sum_{m=1}^{\\infty}\\left[a_m\\cos\\frac{m\\pi x}{P}+b_m\\sen\\frac{m\\pi x}{P}\\right]'],
        ['Coeficiente $a_0$', 'a_0=\\frac{1}{P}\\int_{-P}^{P}f(x)\\,dx'],
        ['Coeficiente $a_m$', 'a_m=\\frac{1}{P}\\int_{-P}^{P}f(x)\\cos\\frac{m\\pi x}{P}\\,dx'],
        ['Coeficiente $b_m$', 'b_m=\\frac{1}{P}\\int_{-P}^{P}f(x)\\sen\\frac{m\\pi x}{P}\\,dx'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Qué hace una serie de Fourier?',
          o: ['Escribe una función periódica como suma infinita de senos y cosenos', 'Calcula la derivada de una función periódica', 'Resuelve una ecuación diferencial', 'Transforma una función de $t$ en una de $s$'], r: 0,
          x: 'Descompone la función en sus componentes de frecuencia. Lo último que describís es la transformada de Laplace.' },
        { t: 'mc', p: 'Si $f$ está definida en $(-5,\\,5)$, ¿cuánto vale $P$?',
          o: ['$5$', '$10$', '$2{,}5$', '$-5$'], r: 0,
          x: '$P$ es el semiperíodo: el extremo del intervalo. El período completo es $2P=10$.' },
        { t: 'in', p: 'Si el período de $f$ es $2P=8$, ¿cuánto vale $P$?', r: ['4'], ph: 'Un número',
          x: '$P$ es la mitad del período: $P=4$.' },
        { t: 'mc', p: 'En la serie, el primer término es',
          o: ['$\\dfrac{a_0}{2}$', '$a_0$', '$2a_0$', '$a_1$'], r: 0,
          x: 'Va dividido por dos. Se calcula $a_0$ con la fórmula general y después se lo parte al medio al escribir la serie.' },
        { t: 'mc', p: '¿Cuál es la fórmula de $a_m$?',
          o: ['$\\dfrac{1}{P}\\displaystyle\\int_{-P}^{P}f(x)\\cos\\dfrac{m\\pi x}{P}dx$', '$\\dfrac{1}{P}\\displaystyle\\int_{-P}^{P}f(x)\\sen\\dfrac{m\\pi x}{P}dx$', '$\\dfrac{1}{2P}\\displaystyle\\int_{-P}^{P}f(x)dx$', '$\\displaystyle\\int_{0}^{P}f(x)\\cos(mx)dx$'], r: 0,
          x: 'El coeficiente de los **cosenos** se calcula integrando contra un coseno. La segunda opción es la de $b_m$.' },
        { t: 'par', p: 'Emparejá cada coeficiente con lo que mide',
          o: [['$a_0/2$', 'El promedio de la función'], ['$a_m$', 'El aporte de los cosenos'], ['$b_m$', 'El aporte de los senos'], ['$P$', 'La mitad del período']],
          x: 'Tener claro qué es cada cosa evita mezclar fórmulas durante el cálculo.' },
        { t: 'mc', p: '¿Por qué $a_0$ se calcula sin coseno?',
          o: ['Porque $\\cos(0)=1$ y desaparece del integrando', 'Porque $a_0$ no tiene coseno por definición', 'Porque se integra en otro intervalo', 'Porque el coseno se cancela con el seno'], r: 0,
          x: 'Es $a_m$ evaluado en $m=0$: el argumento del coseno se anula y $\\cos 0=1$, así que queda la integral de $f$ sola.' },
        { t: 'in', p: 'En el armónico $m=3$, ¿cuál es el argumento del seno si $P=5$?', r: ['3pix/5', '3*pi*x/5', '(3pix)/5'], ph: 'Escribí 3pix/5', teclas: ['pi', 'x', '/'],
          x: 'El argumento general es $\\frac{m\\pi x}{P}$. Con $m=3$ y $P=5$: $\\frac{3\\pi x}{5}$.' },
        { t: 'vf', p: 'Cuantos más términos de la serie sumás, mejor se aproxima la función original.', r: true,
          x: 'Sí. Con un puñado de armónicos ya se reconoce la forma de la función; la serie completa la reproduce.' },
        { t: 'mc', p: '$m$ en la serie de Fourier representa',
          o: ['El número de armónico', 'El período', 'La amplitud', 'La variable independiente'], r: 0,
          x: 'Es el índice de la sumatoria: $m=1$ es el fundamental, y los siguientes son los armónicos superiores.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u7l2',
      titulo: 'Funciones pares e impares',
      objetivo: 'Ahorrarse la mitad de las integrales mirando la simetría.',
      teoria: [
        { p: 'Antes de ponerse a integrar conviene mirar si la función tiene simetría. Si la tiene, **la mitad de los coeficientes son cero** y te ahorrás la mitad del trabajo.' },
        { def: ['Función par', '$f(-x)=f(x)$. El gráfico es simétrico respecto del eje $y$. Ejemplos: $y=x^{2}$, $y=\\cos x$, $y=|x|$.'] },
        { def: ['Función impar', '$f(-x)=-f(x)$. El gráfico es simétrico respecto del origen. Ejemplos: $y=x^{3}$, $y=\\sen x$, $y=x$.'] },
        { tabla: [['Si $f$ es...', 'Entonces', 'La serie queda'], [
          ['**Par**', '$b_m=0$', 'Sólo cosenos'],
          ['**Impar**', '$a_0=0$ y $a_m=0$', 'Sólo senos'],
          ['Ninguna de las dos', 'Hay que calcular todo', 'Senos y cosenos'],
        ]] },
        { p: 'La razón es de simetría: el seno es impar y el coseno es par. Al integrar en un intervalo simétrico $(-P,P)$, el producto de una función par por una impar da impar, y **la integral de una función impar en un intervalo simétrico es cero**.' },
        { truco: 'Regla nemotécnica: **par va con coseno, impar va con seno**. El coseno es par y el seno es impar, así que cada uno "sobrevive" con su igual.' },
        { ej: ['¿Es $f(x)=x^{3}$ par o impar?', [
          'Calculo $f(-x)=(-x)^{3}=-x^{3}$',
          'Y $-f(x)=-x^{3}$',
          'Son iguales, entonces $f(-x)=-f(x)$: es **impar**',
          'Su serie de Fourier va a tener **sólo senos**',
        ]] },
        { ej: ['¿Es $f(x)=x^{2}$ par o impar?', [
          '$f(-x)=(-x)^{2}=x^{2}=f(x)$',
          'Es **par**, así que su serie va a tener sólo cosenos (y el término constante)',
        ]] },
        { ojo: 'Muchas funciones **no son ni pares ni impares**. El ejemplo de la clase, $f(x)=0$ en $(-5,0)$ y $f(x)=3$ en $[0,5)$, no tiene ninguna simetría: hay que calcular los tres coeficientes.' },
        { h: 'La simplificación práctica' },
        { p: 'Cuando $f$ es par, además se puede integrar de $0$ a $P$ y duplicar, porque el integrando también resulta par:' },
        { mat: 'a_m=\\frac{2}{P}\\int_{0}^{P}f(x)\\cos\\left(\\frac{m\\pi x}{P}\\right)dx' },
      ],
      formulas: [
        ['Par', 'f(-x)=f(x) \;\\Rightarrow\; b_m=0'],
        ['Impar', 'f(-x)=-f(x) \;\\Rightarrow\; a_0=a_m=0'],
        ['Integral de impar', '\\int_{-P}^{P}(\\text{impar})\\,dx=0'],
        ['Valores útiles', '\\cos(m\\pi)=(-1)^{m} \\qquad \\sen(m\\pi)=0'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Cuándo una función es par?',
          o: ['Si $f(-x)=f(x)$', 'Si $f(-x)=-f(x)$', 'Si $f(0)=0$', 'Si el período es par'], r: 0,
          x: 'Simetría respecto del eje $y$: evaluar en $-x$ da lo mismo.' },
        { t: 'mc', p: '¿Cuándo es impar?',
          o: ['Si $f(-x)=-f(x)$', 'Si $f(-x)=f(x)$', 'Si $f$ es negativa', 'Si el exponente es impar'], r: 0,
          x: 'Simetría respecto del origen: evaluar en $-x$ da el opuesto.' },
        { t: 'mc', p: 'Si $f$ es **impar**, ¿qué coeficientes se anulan?',
          o: ['$a_0$ y $a_m$ (los cosenos)', '$b_m$ (los senos)', 'Todos', 'Ninguno'], r: 0,
          x: 'Impar va con seno. Los cosenos, que son pares, no aportan nada.' },
        { t: 'mc', p: 'Si $f$ es **par**, ¿qué coeficientes se anulan?',
          o: ['$b_m$ (los senos)', '$a_m$ (los cosenos)', '$a_0$', 'Ninguno'], r: 0,
          x: 'Par va con coseno, así que los senos desaparecen.' },
        { t: 'par', p: 'Clasificá cada función',
          o: [['$y=x^{3}$', 'Impar'], ['$y=x^{2}$', 'Par'], ['$y=\\sen x$', 'Impar'], ['$y=\\cos x$', 'Par']],
          x: 'Las potencias impares y el seno son impares; las potencias pares y el coseno son pares.' },
        { t: 'vf', p: '$f(x)=x^{3}$ es impar, así que su serie de Fourier tiene sólo senos.', r: true,
          x: '$(-x)^{3}=-x^{3}$, entonces es impar y los $a_m$ se anulan todos.' },
        { t: 'mc', p: '¿Cuánto vale $\\displaystyle\\int_{-P}^{P}f(x)\\,dx$ si $f$ es impar?',
          o: ['$0$', '$2\\displaystyle\\int_{0}^{P}f(x)dx$', 'No se puede saber', '$P$'], r: 0,
          x: 'Lo que aporta la mitad izquierda se cancela exactamente con lo que aporta la derecha.' },
        { t: 'in', p: '¿Cuánto vale $\\sen(m\\pi)$ para cualquier $m$ entero?', r: ['0'], ph: 'Un número',
          x: 'El seno se anula en todos los múltiplos de $\\pi$. Este valor hace desaparecer un montón de términos al calcular coeficientes.' },
        { t: 'mc', p: '$\\cos(m\\pi)$ es igual a',
          o: ['$(-1)^{m}$', '$0$', '$1$', '$m$'], r: 0,
          x: 'Vale $-1$ para $m$ impar y $1$ para $m$ par. Es lo que genera el patrón "sólo los impares sobreviven".' },
        { t: 'vf', p: 'La función que vale $0$ en $(-5,0)$ y $3$ en $[0,5)$ es par.', r: false,
          x: 'No es par ni impar: no hay ninguna simetría. Hay que calcular los tres coeficientes a mano.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u7l3',
      titulo: 'Calcular los coeficientes',
      objetivo: 'Integrar y encontrar a₀, aₘ y bₘ de una función a trozos.',
      teoria: [
        { p: 'Vamos con el ejemplo completo de la clase, que es el que hay que saber hacer de memoria.' },
        { def: ['El problema', 'Desarrollar la serie de Fourier de $$f(x)=\\begin{cases} 0 & \\text{si } -5<x<0 \\\\ 3 & \\text{si } 0\\le x<5 \\end{cases}$$'] },
        { p: 'El intervalo es $(-5,\\,5)$, así que $P=5$. Y como $f$ vale cero en la mitad izquierda, **todas las integrales se reducen al tramo de $0$ a $5$**.' },
        { ej: ['Calcular $a_0$', [
          '$\;a_0=\\dfrac{1}{5}\\displaystyle\\int_{-5}^{5}f(x)\\,dx$',
          'La primera mitad aporta cero, así que sólo queda el tramo donde $f=3$:',
          '$\;=\\dfrac{1}{5}\\displaystyle\\int_{0}^{5}3\\,dx=\\dfrac{1}{5}\\left[3x\\right]_{0}^{5}=\\dfrac{1}{5}\\cdot 15=3$',
          'Entonces $\;a_0=3\;$ y el primer término de la serie es $\;\\dfrac{a_0}{2}=\\dfrac{3}{2}$',
        ]] },
        { ej: ['Calcular $a_m$', [
          '$\;a_m=\\dfrac{1}{5}\\displaystyle\\int_{0}^{5}3\\cos\\left(\\dfrac{m\\pi x}{5}\\right)dx$',
          'La primitiva del coseno: $\;\\dfrac{3}{5}\\cdot\\dfrac{5}{m\\pi}\\left[\\sen\\left(\\dfrac{m\\pi x}{5}\\right)\\right]_{0}^{5}$',
          'Evalúo: $\;\\dfrac{3}{m\\pi}\\left[\\sen(m\\pi)-\\sen(0)\\right]$',
          'Y como $\\sen(m\\pi)=0$ para todo $m$ entero:',
          '$\;a_m=0$',
        ]] },
        { ej: ['Calcular $b_m$', [
          '$\;b_m=\\dfrac{1}{5}\\displaystyle\\int_{0}^{5}3\\,\\sen\\left(\\dfrac{m\\pi x}{5}\\right)dx$',
          'Primitiva del seno (lleva menos): $\;\\dfrac{3}{5}\\cdot\\left(-\\dfrac{5}{m\\pi}\\right)\\left[\\cos\\left(\\dfrac{m\\pi x}{5}\\right)\\right]_{0}^{5}$',
          '$\;=-\\dfrac{3}{m\\pi}\\left[\\cos(m\\pi)-\\cos(0)\\right]=-\\dfrac{3}{m\\pi}\\left[(-1)^{m}-1\\right]$',
          'Si $m$ es **par**: $(-1)^{m}=1$, entonces el corchete es $0$ y $\;b_m=0$',
          'Si $m$ es **impar**: $(-1)^{m}=-1$, el corchete es $-2$ y $\;b_m=\\dfrac{6}{m\\pi}$',
        ]] },
        { truco: 'Ese patrón —"los pares se anulan, los impares dan algo"— es típico de Fourier, y viene siempre de $\\cos(m\\pi)=(-1)^{m}$. Cuando lo veas, es señal de que vas bien.' },
        { ojo: 'Al integrar $\\cos\\left(\\frac{m\\pi x}{P}\\right)$, el factor que sale de la sustitución es $\\frac{P}{m\\pi}$, no $\\frac{m\\pi}{P}$. Se invierte. Es el error de cálculo más común de la unidad.' },
      ],
      formulas: [
        ['Resultado del ejemplo', 'a_0=3,\\quad a_m=0,\\quad b_m=\\begin{cases}0 & m \\text{ par}\\\\ \\frac{6}{m\\pi} & m \\text{ impar}\\end{cases}'],
        ['Primitivas', '\\int\\cos\\frac{m\\pi x}{P}dx=\\frac{P}{m\\pi}\\sen\\frac{m\\pi x}{P}'],
        ['', '\\int\\sen\\frac{m\\pi x}{P}dx=-\\frac{P}{m\\pi}\\cos\\frac{m\\pi x}{P}'],
      ],
      ejercicios: [
        { t: 'in', p: 'Para $f$ definida en $(-5,5)$, ¿cuánto vale $P$?', r: ['5'], ph: 'Un número',
          x: '$P$ es el extremo del intervalo simétrico, o la mitad del período.' },
        { t: 'mc', p: 'Si $f(x)=0$ en $(-5,0)$, ¿qué pasa con esa parte de la integral?',
          o: ['Aporta cero, así que sólo se integra de $0$ a $5$', 'Hay que integrarla igual', 'Se duplica el resultado', 'La integral no existe'], r: 0,
          x: 'Integrar la función nula da cero. Todo el trabajo se concentra en el tramo donde $f$ no es cero.' },
        { t: 'in', p: '¿Cuánto vale $a_0=\\dfrac{1}{5}\\displaystyle\\int_{0}^{5}3\\,dx$?', r: ['3'], ph: 'Un número',
          x: '$\\int_0^5 3\\,dx = 3\\cdot 5=15$, y $\\frac{15}{5}=3$.' },
        { t: 'mc', p: 'Entonces el primer término de la serie es',
          o: ['$\\dfrac{3}{2}$', '$3$', '$6$', '$\\dfrac{1}{3}$'], r: 0,
          x: 'En la serie entra $\\frac{a_0}{2}$, o sea $\\frac{3}{2}$.' },
        { t: 'mc', p: '¿Por qué $a_m=0$ en este ejemplo?',
          o: ['Porque aparece $\\sen(m\\pi)$, que vale cero', 'Porque la función es impar', 'Porque $a_0$ ya valía 3', 'Porque el coseno es par'], r: 0,
          x: 'Al evaluar la primitiva en los límites queda $\\sen(m\\pi)-\\sen(0)$, y los dos términos son cero.' },
        { t: 'mc', p: 'Al calcular $b_m$ queda $-\\dfrac{3}{m\\pi}\\left[(-1)^{m}-1\\right]$. Si $m$ es par, ¿cuánto vale?',
          o: ['$0$', '$\\dfrac{6}{m\\pi}$', '$-\\dfrac{6}{m\\pi}$', '$\\dfrac{3}{m\\pi}$'], r: 0,
          x: 'Con $m$ par, $(-1)^{m}=1$, así que el corchete es $1-1=0$.' },
        { t: 'mc', p: '¿Y si $m$ es impar?',
          o: ['$\\dfrac{6}{m\\pi}$', '$0$', '$-\\dfrac{6}{m\\pi}$', '$\\dfrac{3}{m\\pi}$'], r: 0,
          x: 'Con $m$ impar, $(-1)^{m}=-1$: el corchete es $-2$ y queda $-\\frac{3}{m\\pi}\\cdot(-2)=\\frac{6}{m\\pi}$.' },
        { t: 'in', p: 'Con la fórmula $b_m=\\dfrac{6}{m\\pi}$, ¿cuánto vale $b_1$?', r: ['6/pi', '6/π'], ph: 'Escribí 6/pi', teclas: ['/', 'pi'],
          x: 'Con $m=1$: $b_1=\\frac{6}{1\\cdot\\pi}=\\frac{6}{\\pi}$.' },
        { t: 'mc', p: '¿Cuánto vale $b_3$?',
          o: ['$\\dfrac{2}{\\pi}$', '$\\dfrac{6}{\\pi}$', '$\\dfrac{3}{\\pi}$', '$0$'], r: 0,
          x: '$b_3=\\frac{6}{3\\pi}=\\frac{2}{\\pi}$. Se simplifica el $6$ con el $3$.' },
        { t: 'mc', p: 'Al integrar $\\cos\\left(\\dfrac{m\\pi x}{5}\\right)$, el factor que aparece es',
          o: ['$\\dfrac{5}{m\\pi}$', '$\\dfrac{m\\pi}{5}$', '$\\dfrac{1}{5}$', '$m\\pi$'], r: 0,
          x: 'Se divide por la derivada del argumento, así que la fracción se **invierte**.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u7l4',
      titulo: 'Escribir el desarrollo',
      objetivo: 'Armar la serie final y escribir los primeros términos.',
      teoria: [
        { p: 'Con los coeficientes calculados, sólo falta reemplazarlos en la serie y, si el ejercicio lo pide, escribir los primeros términos.' },
        { ej: ['Armar la serie del ejemplo', [
          'Tenemos $a_0=3$, $a_m=0$, y $b_m=\\dfrac{6}{m\\pi}$ sólo para $m$ impar',
          'Reemplazo en la serie general:',
          '$\;f(x)=\\dfrac{3}{2}+\\displaystyle\\sum_{m=1}^{\\infty}\\left[0\\cdot\\cos\\left(\\dfrac{m\\pi x}{5}\\right)+b_m\\,\\sen\\left(\\dfrac{m\\pi x}{5}\\right)\\right]$',
          'Los cosenos se van todos:',
          '$\;f(x)=\\dfrac{3}{2}+\\displaystyle\\sum_{m=1}^{\\infty}b_m\\,\\sen\\left(\\dfrac{m\\pi x}{5}\\right)$',
        ]] },
        { h: 'Los primeros términos' },
        { p: 'Ahora le doy valores a $m$ desde 1 en adelante. Los pares dan cero, así que sólo escribo los impares:' },
        { tabla: [['$m$', '$b_m$', 'Término'], [
          ['1', '$\\dfrac{6}{\\pi}$', '$\\dfrac{6}{\\pi}\\sen\\left(\\dfrac{\\pi x}{5}\\right)$'],
          ['2', '$0$', '—'],
          ['3', '$\\dfrac{6}{3\\pi}=\\dfrac{2}{\\pi}$', '$\\dfrac{2}{\\pi}\\sen\\left(\\dfrac{3\\pi x}{5}\\right)$'],
          ['4', '$0$', '—'],
          ['5', '$\\dfrac{6}{5\\pi}$', '$\\dfrac{6}{5\\pi}\\sen(\\pi x)$'],
        ]] },
        { p: 'El desarrollo queda:' },
        { mat: 'f(x)=\\frac{3}{2}+\\frac{6}{\\pi}\\sen\\left(\\frac{\\pi x}{5}\\right)+\\frac{2}{\\pi}\\sen\\left(\\frac{3\\pi x}{5}\\right)+\\frac{6}{5\\pi}\\sen\\left(\\frac{5\\pi x}{5}\\right)+\\cdots' },
        { truco: 'Fijate que $\\dfrac{6}{3\\pi}$ se simplifica a $\\dfrac{2}{\\pi}$. Simplificar cada coeficiente antes de escribirlo hace que el resultado se vea prolijo y se controle mejor.' },
        { ojo: 'No te olvides de los puntos suspensivos al final. La serie es **infinita**: escribir tres términos y cerrar con un igual sin puntos es incorrecto.' },
        { h: 'Interpretación' },
        { p: 'Ese $\\dfrac{3}{2}$ del principio es el promedio de la función: vale $0$ la mitad del tiempo y $3$ la otra mitad. Los senos se encargan de armar el escalón. Cada armónico que sumás afina un poco más la esquina del salto.' },
      ],
      formulas: [
        ['Desarrollo obtenido', 'f(x)=\\frac{3}{2}+\\frac{6}{\\pi}\\sen\\frac{\\pi x}{5}+\\frac{2}{\\pi}\\sen\\frac{3\\pi x}{5}+\\cdots'],
        ['Sólo impares', 'b_m=\\frac{6}{m\\pi} \\quad (m=1,3,5,\\ldots)'],
      ],
      ejercicios: [
        { t: 'mc', p: 'Con $a_m=0$, ¿cómo queda la serie?',
          o: ['$\\dfrac{a_0}{2}+\\displaystyle\\sum b_m\\,\\sen\\dfrac{m\\pi x}{P}$', '$\\displaystyle\\sum a_m\\cos\\dfrac{m\\pi x}{P}$', '$\\dfrac{a_0}{2}$', '$\\displaystyle\\sum b_m\\cos\\dfrac{m\\pi x}{P}$'], r: 0,
          x: 'Desaparecen todos los cosenos, pero **queda el término constante** $\\frac{a_0}{2}$, que no depende de $a_m$.' },
        { t: 'in', p: 'En el desarrollo, ¿cuál es el primer término (el constante)?', r: ['3/2', '1.5'], ph: 'Una fracción', teclas: ['/'],
          x: '$\\frac{a_0}{2}=\\frac{3}{2}$.' },
        { t: 'mc', p: 'El término correspondiente a $m=1$ es',
          o: ['$\\dfrac{6}{\\pi}\\sen\\left(\\dfrac{\\pi x}{5}\\right)$', '$\\dfrac{6}{\\pi}\\cos\\left(\\dfrac{\\pi x}{5}\\right)$', '$\\dfrac{6}{\\pi}\\sen\\left(\\dfrac{x}{5}\\right)$', '$\\dfrac{3}{\\pi}\\sen\\left(\\dfrac{\\pi x}{5}\\right)$'], r: 0,
          x: 'Con $m=1$ y $P=5$: coeficiente $\\frac{6}{\\pi}$ y argumento $\\frac{\\pi x}{5}$.' },
        { t: 'mc', p: '¿Y el de $m=2$?',
          o: ['No hay: vale cero', '$\\dfrac{3}{\\pi}\\sen\\left(\\dfrac{2\\pi x}{5}\\right)$', '$\\dfrac{6}{2\\pi}\\sen\\left(\\dfrac{2\\pi x}{5}\\right)$', '$\\dfrac{2}{\\pi}\\sen\\left(\\dfrac{2\\pi x}{5}\\right)$'], r: 0,
          x: 'Los $m$ pares dan $b_m=0$, así que ese término desaparece del desarrollo.' },
        { t: 'mc', p: 'El término de $m=3$ simplificado es',
          o: ['$\\dfrac{2}{\\pi}\\sen\\left(\\dfrac{3\\pi x}{5}\\right)$', '$\\dfrac{6}{3\\pi}\\sen\\left(\\dfrac{\\pi x}{5}\\right)$', '$\\dfrac{6}{\\pi}\\sen\\left(\\dfrac{3\\pi x}{5}\\right)$', '$\\dfrac{3}{\\pi}\\sen\\left(\\dfrac{3\\pi x}{5}\\right)$'], r: 0,
          x: '$\\frac{6}{3\\pi}=\\frac{2}{\\pi}$, y el argumento lleva el $m=3$: $\\frac{3\\pi x}{5}$.' },
        { t: 'ord', p: 'Ordená el método completo de Fourier',
          o: ['Identificar $P$ a partir del intervalo', 'Ver si la función es par o impar', 'Calcular $a_0$, $a_m$ y $b_m$ integrando', 'Reemplazar los coeficientes en la serie', 'Darle valores a $m$ y escribir los primeros términos'],
          x: 'El paso 2 puede ahorrarte la mitad de las integrales, así que conviene no saltearlo.' },
        { t: 'vf', p: 'La serie de Fourier tiene infinitos términos.', r: true,
          x: 'Sí. Cuando el ejercicio pide "escribir los primeros términos", se escriben algunos y se cierra con puntos suspensivos.' },
        { t: 'mc', p: '¿Qué representa el término constante $\\dfrac{a_0}{2}$?',
          o: ['El valor promedio de la función en un período', 'El primer armónico', 'La amplitud máxima', 'El período'], r: 0,
          x: 'En el ejemplo, la función vale $0$ la mitad del tiempo y $3$ la otra mitad: el promedio es $1{,}5=\\frac{3}{2}$ ✓' },
        { t: 'mc', p: 'Si una función es par, su desarrollo tiene',
          o: ['Término constante y cosenos', 'Sólo senos', 'Sólo el término constante', 'Senos y cosenos'], r: 0,
          x: 'Los $b_m$ se anulan, así que quedan $\\frac{a_0}{2}$ y los cosenos.' },
        { t: 'in', p: 'Con $b_m=\\dfrac{6}{m\\pi}$, ¿cuánto vale $b_5$?', r: ['6/(5pi)', '6/5pi', '6/(5π)'], ph: 'Escribí 6/(5pi)', teclas: ['/', '(', ')', 'pi'],
          x: '$b_5=\\frac{6}{5\\pi}$, que ya está en su forma más simple.' },
      ],
    },
  ],
});
