/* Unidad 8 — Números complejos y funciones de variable compleja
   Guía 10 (revisión) y Guía Teórica N° 4 (pág. 20) + clases del 03/09 y 10/09. */
(window.__UNIDADES = window.__UNIDADES || []).push({
  id: 'u8',
  n: 8,
  titulo: 'Variable compleja',
  glifo: 'ℂ',
  resumen: 'Repaso de complejos, forma trigonométrica, funciones f(z)=u+iv y límites.',
  lecciones: [

    /* ------------------------------------------------------------------ */
    {
      id: 'u8l1',
      titulo: 'Repaso de complejos',
      objetivo: 'Operar en forma binómica, sobre todo dividir.',
      teoria: [
        { def: ['Número complejo', 'Se escribe $z=a+bi$, donde $a=\\mathrm{Re}(z)$ es la **parte real**, $b=\\mathrm{Im}(z)$ la **parte imaginaria**, e $i$ cumple $i^{2}=-1$.'] },
        { p: 'También se anota como par ordenado: $z=(a,\\,b)$, que es el punto del plano complejo.' },
        { h: 'Potencias de i' },
        { tabla: [['Potencia', 'Valor'], [
          ['$i^{0}$', '$1$'], ['$i^{1}$', '$i$'], ['$i^{2}$', '$-1$'], ['$i^{3}$', '$-i$'], ['$i^{4}$', '$1$'],
        ]] },
        { truco: 'Las potencias de $i$ se repiten cada 4. Para calcular $i^{n}$, dividí $n$ por 4 y quedate con el resto: $i^{27}$ tiene resto 3, así que $i^{27}=-i$.' },
        { def: ['Conjugado', 'Si $z=a+bi$, su conjugado es $\\bar{z}=a-bi$. Como par ordenado: $z=(a,b)$ y $\\bar{z}=(a,-b)$.'] },
        { h: 'Dividir complejos' },
        { p: 'No se puede dejar una $i$ en el denominador. El truco es **multiplicar arriba y abajo por el conjugado del denominador**: eso lo vuelve real.' },
        { mat: '\\frac{a+bi}{c+di}\\cdot\\frac{c-di}{c-di}' },
        { ej: ['Calcular $\\dfrac{-2+4i}{2i}$  — del ejercicio de la clase del 03/09', [
          'El conjugado de $2i$ (o sea de $0+2i$) es $-2i$. Multiplico arriba y abajo:',
          'Numerador: $\;(-2+4i)(-2i)=4i-8i^{2}=4i-8(-1)=8+4i$',
          'Denominador: $\;(2i)(-2i)=-4i^{2}=-4(-1)=4$',
          'Queda: $\;\\dfrac{8+4i}{4}=\\dfrac{8}{4}+\\dfrac{4i}{4}=2+i$',
        ]] },
        { ojo: 'El paso donde todos se equivocan es $i^{2}=-1$. Cada vez que aparezca un $i^{2}$, reemplazalo enseguida por $-1$ y respetá los signos.' },
        { h: 'Raíces de números negativos' },
        { p: 'Ya lo usaste en las ecuaciones de segundo orden: $\\sqrt{-16}=4i$, porque $(4i)^{2}=16i^{2}=-16$.' },
        { def: ['Ecuaciones en $\\mathbb{C}$', 'La resolvente sigue valiendo, incluso con coeficientes complejos. Lo único distinto es que ahora la raíz de un número negativo **sí** tiene solución.'] },
      ],
      formulas: [
        ['Forma binómica', 'z=a+bi \\qquad i^{2}=-1'],
        ['Conjugado', '\\bar{z}=a-bi'],
        ['División', '\\frac{z_1}{z_2}=\\frac{z_1\\cdot\\bar{z_2}}{z_2\\cdot\\bar{z_2}}'],
        ['Módulo', '|z|=\\sqrt{a^{2}+b^{2}}'],
      ],
      ejercicios: [
        { t: 'in', p: '¿Cuánto vale $i^{2}$?', r: ['-1'], ph: 'Un número', teclas: ['-'],
          x: 'Es la definición de la unidad imaginaria.' },
        { t: 'mc', p: '¿Cuánto vale $i^{3}$?', o: ['$-i$', '$i$', '$1$', '$-1$'], r: 0,
          x: '$i^{3}=i^{2}\\cdot i=(-1)\\cdot i=-i$.' },
        { t: 'mc', p: '¿Cuánto vale $i^{27}$?', o: ['$-i$', '$i$', '$1$', '$-1$'], r: 0,
          x: 'Dividís $27$ por $4$: da resto $3$. Entonces $i^{27}=i^{3}=-i$.' },
        { t: 'mc', p: '¿Cuál es el conjugado de $z=3-5i$?',
          o: ['$3+5i$', '$-3+5i$', '$-3-5i$', '$5-3i$'], r: 0,
          x: 'Se cambia el signo de la parte imaginaria solamente.' },
        { t: 'mc', p: 'Para dividir $\\dfrac{-2+4i}{2i}$, ¿por qué multiplicás arriba y abajo?',
          o: ['Por $-2i$, el conjugado del denominador', 'Por $2i$', 'Por $-2$', 'Por el conjugado del numerador'], r: 0,
          x: 'Siempre por el conjugado del **denominador**: eso lo convierte en un número real.' },
        { t: 'mc', p: 'Resolvé $\\dfrac{-2+4i}{2i}$',
          o: ['$2+i$', '$2-i$', '$-2+i$', '$1+2i$'], r: 0,
          x: 'Numerador: $(-2+4i)(-2i)=4i+8$. Denominador: $-4i^{2}=4$. Da $\\frac{8+4i}{4}=2+i$.' },
        { t: 'hue', p: 'Si $z=7-2i$, entonces', tpl: '$\\mathrm{Re}(z)=$ ___ y $\\mathrm{Im}(z)=$ ___', r: [['7'], ['-2']],
          x: 'La parte imaginaria es el coeficiente de $i$ **con su signo**, no incluye la $i$.' },
        { t: 'in', p: '¿Cuánto vale $\\sqrt{-25}$?', r: ['5i', '5*i'], ph: 'Por ejemplo: 5i', teclas: ['i'],
          x: '$\\sqrt{25}\\cdot\\sqrt{-1}=5i$. Comprobación: $(5i)^{2}=25i^{2}=-25$ ✓' },
        { t: 'mc', p: '$(2+3i)(2-3i)$ es igual a',
          o: ['$13$', '$4-9i$', '$4+9i^{2}$', '$13i$'], r: 0,
          x: 'Diferencia de cuadrados: $2^{2}-(3i)^{2}=4-9i^{2}=4+9=13$. Un número por su conjugado siempre da un real.' },
        { t: 'in', p: '¿Cuánto vale $|3+4i|$?', r: ['5'], ph: 'Un número',
          x: '$|z|=\\sqrt{a^{2}+b^{2}}=\\sqrt{9+16}=\\sqrt{25}=5$.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u8l2',
      titulo: 'Forma trigonométrica y raíces',
      objetivo: 'Pasar de binómica a polar y calcular raíces n-ésimas.',
      teoria: [
        { p: 'Un complejo también se describe por **cuánto mide** y **hacia dónde apunta**. Eso es la forma trigonométrica (o polar).' },
        { def: ['Forma trigonométrica', '$$z=\\rho\\left[\\cos\\varphi+i\\,\\sen\\varphi\\right]$$ con módulo $\\rho=\\sqrt{a^{2}+b^{2}}$ y argumento $\\varphi=\\arctan\\dfrac{b}{a}$.'] },
        { ojo: 'El arcotangente devuelve siempre un ángulo entre $-\\frac{\\pi}{2}$ y $\\frac{\\pi}{2}$. Si el punto está en el segundo o tercer cuadrante hay que **sumarle $\\pi$**. Dibujar el punto antes de calcular evita el error.' },
        { ej: ['Pasar $z=-4+4i$ a forma trigonométrica  — del ejercicio 6 de la clase', [
          'Módulo: $\;\\rho=\\sqrt{(-4)^{2}+4^{2}}=\\sqrt{32}=4\\sqrt{2}$',
          'Argumento: $\;\\arctan\\dfrac{4}{-4}=\\arctan(-1)=-\\dfrac{\\pi}{4}$',
          'Pero el punto $(-4,\\,4)$ está en el **segundo cuadrante**, así que le sumo $\\pi$:',
          '$\;\\varphi=-\\dfrac{\\pi}{4}+\\pi=\\dfrac{3\\pi}{4}$',
          'Resultado: $\;z=4\\sqrt{2}\\left[\\cos\\dfrac{3\\pi}{4}+i\\,\\sen\\dfrac{3\\pi}{4}\\right]$',
        ]] },
        { h: 'Potencias: De Moivre' },
        { p: 'La forma trigonométrica vuelve trivial calcular potencias grandes:' },
        { mat: 'z^{n}=\\rho^{n}\\left[\\cos(n\\varphi)+i\\,\\sen(n\\varphi)\\right]' },
        { ej: ['Calcular $\\left(\\sqrt{3}+i\\right)^{30}$  — del ejercicio 5', [
          'Módulo: $\;\\rho=\\sqrt{3+1}=2$. Argumento: $\;\\varphi=\\arctan\\dfrac{1}{\\sqrt{3}}=\\dfrac{\\pi}{6}$',
          'De Moivre: $\;2^{30}\\left[\\cos\\left(30\\cdot\\dfrac{\\pi}{6}\\right)+i\\,\\sen\\left(30\\cdot\\dfrac{\\pi}{6}\\right)\\right]$',
          '$\;=2^{30}\\left[\\cos(5\\pi)+i\\,\\sen(5\\pi)\\right]$',
          'Y $\\cos(5\\pi)=-1$, $\\sen(5\\pi)=0$:',
          '$\;=-2^{30}$',
        ]] },
        { h: 'Radicación en C' },
        { def: ['Raíces n-ésimas', '$$w_k=\\sqrt[n]{\\rho}\\left[\\cos\\left(\\frac{\\varphi+2k\\pi}{n}\\right)+i\\,\\sen\\left(\\frac{\\varphi+2k\\pi}{n}\\right)\\right]$$ con $k=0,1,\\ldots,n-1$.'] },
        { p: 'Es decir: un complejo tiene **exactamente $n$ raíces $n$-ésimas**, todas con el mismo módulo, repartidas en ángulos iguales alrededor de una circunferencia.' },
        { truco: 'Para $\\sqrt{1+i}$ hay $n=2$, así que $k$ toma los valores $\\{0,\\,1\\}$: dos raíces, opuestas entre sí. Para una raíz cúbica, $k=\\{0,1,2\\}$: tres raíces a $120°$ una de otra.' },
      ],
      formulas: [
        ['Forma trigonométrica', 'z=\\rho\\left[\\cos\\varphi+i\\,\\sen\\varphi\\right]'],
        ['Módulo y argumento', '\\rho=\\sqrt{a^{2}+b^{2}} \\qquad \\varphi=\\arctan\\frac{b}{a}'],
        ['De Moivre', 'z^{n}=\\rho^{n}\\left[\\cos n\\varphi+i\\,\\sen n\\varphi\\right]'],
        ['Raíces', 'w_k=\\sqrt[n]{\\rho}\\left[\\cos\\frac{\\varphi+2k\\pi}{n}+i\\,\\sen\\frac{\\varphi+2k\\pi}{n}\\right]'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Cuál es el módulo de $z=-4+4i$?',
          o: ['$4\\sqrt{2}$', '$8$', '$4$', '$\\sqrt{8}$'], r: 0,
          x: '$\\rho=\\sqrt{16+16}=\\sqrt{32}=\\sqrt{16\\cdot 2}=4\\sqrt{2}$.' },
        { t: 'mc', p: '¿Y su argumento?',
          o: ['$\\dfrac{3\\pi}{4}$', '$-\\dfrac{\\pi}{4}$', '$\\dfrac{\\pi}{4}$', '$\\dfrac{\\pi}{2}$'], r: 0,
          x: 'El arcotangente da $-\\frac{\\pi}{4}$, pero el punto $(-4,4)$ está en el segundo cuadrante, así que hay que sumar $\\pi$.' },
        { t: 'vf', p: 'Si el punto está en el segundo cuadrante, hay que sumarle $\\pi$ al arcotangente.', r: true,
          x: 'El arcotangente sólo devuelve ángulos del primer y cuarto cuadrante. Para el segundo y tercero hay que corregir.' },
        { t: 'in', p: '¿Cuál es el módulo de $\\sqrt{3}+i$?', r: ['2'], ph: 'Un número',
          x: '$\\rho=\\sqrt{(\\sqrt{3})^{2}+1^{2}}=\\sqrt{3+1}=2$.' },
        { t: 'mc', p: '¿Cuál es el argumento de $\\sqrt{3}+i$?',
          o: ['$\\dfrac{\\pi}{6}$', '$\\dfrac{\\pi}{3}$', '$\\dfrac{\\pi}{4}$', '$\\dfrac{\\pi}{2}$'], r: 0,
          x: '$\\arctan\\frac{1}{\\sqrt{3}}=\\frac{\\pi}{6}$, que son $30°$. El punto está en el primer cuadrante, así que no hay corrección.' },
        { t: 'mc', p: 'Aplicando De Moivre, $\\left(\\sqrt{3}+i\\right)^{30}$ es igual a',
          o: ['$-2^{30}$', '$2^{30}$', '$2^{30}\\,i$', '$0$'], r: 0,
          x: '$2^{30}\\left[\\cos 5\\pi+i\\sen 5\\pi\\right]$, y como $\\cos 5\\pi=-1$ y $\\sen 5\\pi=0$, queda $-2^{30}$.' },
        { t: 'mc', p: '¿Cuántas raíces cúbicas tiene un número complejo?',
          o: ['Tres', 'Una', 'Dos', 'Infinitas'], r: 0,
          x: 'Un complejo tiene exactamente $n$ raíces $n$-ésimas, repartidas en ángulos iguales sobre una circunferencia.' },
        { t: 'mc', p: 'Para calcular $\\sqrt{1+i}$, ¿qué valores toma $k$?',
          o: ['$k=0$ y $k=1$', '$k=1$ y $k=2$', 'Sólo $k=0$', '$k=0,1,2$'], r: 0,
          x: '$k$ va de $0$ a $n-1$. Con $n=2$ son $k=0$ y $k=1$.' },
        { t: 'mc', p: 'En la fórmula de De Moivre, el módulo',
          o: ['Se eleva a la $n$', 'Se multiplica por $n$', 'Queda igual', 'Se divide por $n$'], r: 0,
          x: 'El módulo se eleva y el **ángulo se multiplica**. Confundir cuál es cuál es el error típico.' },
        { t: 'in', p: '¿Cuánto vale $\\cos(5\\pi)$?', r: ['-1'], ph: 'Un número', teclas: ['-'],
          x: '$5\\pi$ equivale a $\\pi$ (se dan dos vueltas completas y sobra $\\pi$), y $\\cos\\pi=-1$.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u8l3',
      titulo: 'Regiones del plano',
      objetivo: 'Traducir una condición con módulos a una figura del plano complejo.',
      teoria: [
        { p: 'Los complejos son puntos del plano, así que una desigualdad con módulos describe una **región**. Es el paso previo a hablar de dominios de funciones.' },
        { def: ['La clave', '$|z-z_0|$ es la **distancia** entre el punto $z$ y el punto $z_0$.'] },
        { tabla: [['Condición', 'Región'], [
          ['$|z-z_0|=r$', 'Circunferencia de centro $z_0$ y radio $r$'],
          ['$|z-z_0|<r$', 'Interior del círculo (sin el borde)'],
          ['$|z-z_0|\\le r$', 'Círculo con su borde'],
          ['$r_1<|z-z_0|<r_2$', 'Anillo entre dos circunferencias'],
          ['$a\\le\\mathrm{Re}(z)\\le b$', 'Banda vertical entre $x=a$ y $x=b$'],
          ['$a\\le\\mathrm{Im}(z)\\le b$', 'Banda horizontal entre $y=a$ e $y=b$'],
        ]] },
        { ej: ['$|z-(3+3i)|\\le 9$  — del ejercicio 3 de la clase', [
          'El centro es el punto $z_0=3+3i$, o sea $(3,\\,3)$',
          'El radio es $9$',
          'Como la desigualdad no es estricta, **el borde está incluido**',
          'Región: el círculo de centro $(3,3)$ y radio $9$, con su circunferencia',
        ]] },
        { ojo: 'Cuando la condición viene escrita como $|z-4+3i|$, hay que reordenar: es $|z-(4-3i)|$, así que el centro es $(4,\\,-3)$, no $(4,\\,3)$. El signo se invierte al sacarlo del paréntesis.' },
        { ej: ['$2<|z-i|<3$  — del ejercicio b) de la clase del 10/09', [
          'Centro en $z_0=i$, o sea el punto $(0,\\,1)$',
          'La distancia tiene que ser mayor que 2 y menor que 3',
          'Región: un **anillo** centrado en $(0,1)$, entre los radios 2 y 3, sin los bordes',
        ]] },
        { ej: ['$-1\\le\\mathrm{Re}(z)\\le 1$', [
          '$\\mathrm{Re}(z)=x$, así que la condición es $-1\\le x\\le 1$',
          'No dice nada sobre $y$: puede valer cualquier cosa',
          'Región: una **banda vertical** infinita entre las rectas $x=-1$ y $x=1$, con los bordes',
        ]] },
        { truco: 'Bordes: desigualdad **estricta** ($<$) es borde punteado y excluido; desigualdad con igual ($\\le$) es borde lleno e incluido. Igual que en Análisis I.' },
      ],
      formulas: [
        ['Distancia', '|z-z_0| = \\text{distancia de } z \\text{ a } z_0'],
        ['Circunferencia', '|z-z_0|=r'],
        ['Anillo', 'r_1<|z-z_0|<r_2'],
        ['Módulo', '|a+bi|=\\sqrt{a^{2}+b^{2}}'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Qué representa $|z-z_0|$?',
          o: ['La distancia entre $z$ y $z_0$', 'La suma de $z$ y $z_0$', 'El argumento de $z$', 'La parte real de $z$'], r: 0,
          x: 'Es la distancia en el plano complejo, igual que la distancia entre dos puntos del plano común.' },
        { t: 'mc', p: '$|z-(3+3i)|\\le 9$ describe',
          o: ['Un círculo de centro $(3,3)$ y radio $9$, con su borde', 'Una circunferencia de radio 9', 'Un anillo', 'Una banda vertical'], r: 0,
          x: 'Como la desigualdad incluye el igual, el borde entra. Si fuera $<$, sería sólo el interior.' },
        { t: 'mc', p: '¿Cuál es el centro de la región $|z-4+3i|=5$?',
          o: ['$(4,-3)$', '$(4,3)$', '$(-4,3)$', '$(4,5)$'], r: 0,
          x: 'Hay que reordenar: $|z-(4-3i)|$. El centro es $4-3i$, o sea el punto $(4,-3)$.' },
        { t: 'mc', p: '$2<|z-i|<3$ describe',
          o: ['Un anillo de centro $(0,1)$ entre radios 2 y 3', 'Un círculo de radio 3', 'Dos circunferencias', 'Una banda horizontal'], r: 0,
          x: 'Dos condiciones a la vez: más lejos que 2 y más cerca que 3. Eso es la corona entre las dos circunferencias.' },
        { t: 'mc', p: '$-1\\le\\mathrm{Re}(z)\\le 1$ describe',
          o: ['Una banda vertical entre $x=-1$ y $x=1$', 'Una banda horizontal', 'Un cuadrado', 'Un círculo de radio 1'], r: 0,
          x: '$\\mathrm{Re}(z)$ es la coordenada $x$. Como no hay condición sobre $y$, la banda es infinita hacia arriba y abajo.' },
        { t: 'mc', p: '$|z-i|=2$ describe',
          o: ['Una circunferencia de centro $(0,1)$ y radio 2', 'Un círculo lleno de radio 2', 'Un anillo', 'El punto $(0,1)$'], r: 0,
          x: 'Con el signo igual (sin desigualdad) es sólo el borde: la circunferencia, no el relleno.' },
        { t: 'vf', p: 'Si la desigualdad es estricta, el borde de la región no se incluye.', r: true,
          x: 'Con $<$ el borde queda afuera; con $\\le$ entra.' },
        { t: 'par', p: 'Emparejá cada condición con su figura',
          o: [['$|z-z_0|=r$', 'Circunferencia'], ['$|z-z_0|<r$', 'Círculo sin borde'], ['$r_1<|z-z_0|<r_2$', 'Anillo'], ['$a\\le\\mathrm{Im}(z)\\le b$', 'Banda horizontal']],
          x: 'Las cuatro que aparecen en la guía. Dibujarlas una vez alcanza para no confundirlas nunca más.' },
        { t: 'mc', p: '$\\mathrm{Im}(z)>0$ describe',
          o: ['El semiplano superior', 'El semiplano derecho', 'El eje real', 'Todo el plano'], r: 0,
          x: '$\\mathrm{Im}(z)=y$, así que $y>0$ es todo lo que está arriba del eje real.' },
        { t: 'in', p: '¿Cuál es el radio de la región $|z-2i|\\le 7$?', r: ['7'], ph: 'Un número',
          x: 'El número del lado derecho de la desigualdad es el radio; el centro es $2i$, o sea $(0,2)$.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u8l4',
      titulo: 'Funciones de variable compleja',
      objetivo: 'Separar f(z) en parte real e imaginaria y hallar el dominio.',
      teoria: [
        { def: ['Función de variable compleja', 'Una función $w=f(z)$ cuyo dominio es un conjunto de números complejos y cuya imagen también es compleja.'] },
        { p: 'Como $w$ es un complejo, se puede partir en dos funciones reales de **dos variables**:' },
        { mat: 'w=f(z)=u(x,y)+i\\,v(x,y)' },
        { tabla: [['Nombre', 'Notación'], [
          ['Parte real de $w$', '$\\mathrm{Re}(w)=u(x,y)$'],
          ['Parte imaginaria de $w$', '$\\mathrm{Im}(w)=v(x,y)$'],
        ]] },
        { p: 'El método es siempre el mismo: **reemplazar $z=x+iy$**, desarrollar, y separar lo que tiene $i$ de lo que no.' },
        { ej: ['Hallar $u$ y $v$ de $f(z)=z^{2}-4z$  — del ejercicio de la clase del 10/09', [
          'Reemplazo $z=x+iy$: $\;(x+iy)^{2}-4(x+iy)$',
          'Desarrollo el binomio: $\;x^{2}+2xyi+i^{2}y^{2}-4x-4yi$',
          'Uso $i^{2}=-1$: $\;x^{2}+2xyi-y^{2}-4x-4yi$',
          'Agrupo lo real y lo imaginario:',
          '$\;f(z)=\\left(x^{2}-y^{2}-4x\\right)+i\\left(2xy-4y\\right)$',
          'Entonces $\;u(x,y)=x^{2}-y^{2}-4x\;$ y $\;v(x,y)=2xy-4y$',
        ]] },
        { ojo: 'Al agrupar, la $i$ queda **afuera** del paréntesis imaginario. $v(x,y)$ es $2xy-4y$, no $i(2xy-4y)$.' },
        { h: 'Cuando hay un cociente' },
        { ej: ['$f(z)=\\dfrac{z}{z^{2}+1}$', [
          'Reemplazo: $\;\\dfrac{x+iy}{(x+iy)^{2}+1}$',
          'Desarrollo el denominador: $\;(x^{2}-y^{2}+1)+2xyi$',
          'Multiplico arriba y abajo por el conjugado del denominador:',
          'El denominador queda real: $\;(x^{2}-y^{2}+1)^{2}+4x^{2}y^{2}$',
          'Y recién ahí se puede separar $u$ de $v$',
        ]] },
        { h: 'Dominio' },
        { p: 'El dominio es el conjunto de complejos donde la función está definida. Como en las reales: **no se puede dividir por cero**.' },
        { ej: ['Dominio de $f(z)=\\dfrac{z}{z^{2}+1}$', [
          'Hay que excluir donde el denominador se anula: $\;z^{2}+1=0$',
          '$\;z^{2}=-1$, entonces $\;z=\\pm i$',
          'Dominio: todos los complejos **salvo** $z=i$ y $z=-i$',
        ]] },
        { truco: 'Ojo: en $\\mathbb{C}$, $z^{2}+1=0$ **sí** tiene soluciones. En los reales dirías "no se anula nunca"; acá te quedás sin dos puntos.' },
      ],
      formulas: [
        ['Descomposición', 'f(z)=u(x,y)+i\\,v(x,y)'],
        ['Sustitución', 'z=x+iy'],
        ['Binomio', '(x+iy)^{2}=x^{2}-y^{2}+2xyi'],
        ['Dominio', '\\text{excluir los } z \\text{ que anulan el denominador}'],
      ],
      ejercicios: [
        { t: 'mc', p: 'Una función de variable compleja se escribe como',
          o: ['$f(z)=u(x,y)+i\\,v(x,y)$', '$f(z)=u(x)+v(y)$', '$f(z)=u(z)\\cdot v(z)$', '$f(z)=x+iy$'], r: 0,
          x: 'Dos funciones reales de dos variables: una es la parte real y la otra la imaginaria.' },
        { t: 'mc', p: '¿Cuál es el primer paso para hallar $u$ y $v$?',
          o: ['Reemplazar $z=x+iy$', 'Derivar', 'Calcular el módulo', 'Hallar el dominio'], r: 0,
          x: 'Se reemplaza, se desarrolla y después se agrupa.' },
        { t: 'mc', p: '$(x+iy)^{2}$ es igual a',
          o: ['$x^{2}-y^{2}+2xyi$', '$x^{2}+y^{2}+2xyi$', '$x^{2}+y^{2}$', '$x^{2}+2xyi+y^{2}$'], r: 0,
          x: 'El binomio da $x^{2}+2xyi+i^{2}y^{2}$, y como $i^{2}=-1$ el último término resta.' },
        { t: 'hue', p: 'Para $f(z)=z^{2}-4z$:', tpl: '$u(x,y)=x^{2}-y^{2}-$ ___ $x$ y $v(x,y)=2xy-$ ___ $y$', r: [['4'], ['4']],
          x: 'El $-4z=-4x-4yi$ aporta $-4x$ a la parte real y $-4y$ a la imaginaria.' },
        { t: 'mc', p: 'En $f(z)=(x^{2}-y^{2}-4x)+i(2xy-4y)$, ¿cuál es $\\mathrm{Im}(f)$?',
          o: ['$2xy-4y$', '$i(2xy-4y)$', '$x^{2}-y^{2}-4x$', '$2xy$'], r: 0,
          x: 'La parte imaginaria es el coeficiente de $i$, sin la $i$.' },
        { t: 'mc', p: '¿Cuál es el dominio de $f(z)=\\dfrac{z}{z^{2}+1}$?',
          o: ['Todos los complejos salvo $z=i$ y $z=-i$', 'Todos los complejos', 'Todos salvo $z=0$', 'Todos salvo $z=1$ y $z=-1$'], r: 0,
          x: '$z^{2}+1=0$ da $z^{2}=-1$, o sea $z=\\pm i$. En $\\mathbb{C}$ esa ecuación sí tiene solución.' },
        { t: 'vf', p: 'En $\\mathbb{C}$, la ecuación $z^{2}+1=0$ no tiene solución.', r: false,
          x: 'En los reales no la tiene, pero en los complejos sí: $z=i$ y $z=-i$. Por eso el dominio pierde esos dos puntos.' },
        { t: 'mc', p: 'Para separar $u$ y $v$ en un cociente, ¿qué hacés?',
          o: ['Multiplico arriba y abajo por el conjugado del denominador', 'Derivo', 'Calculo el módulo', 'Paso a forma trigonométrica'], r: 0,
          x: 'Es la misma técnica que para dividir complejos: así el denominador se vuelve real y recién ahí se separa.' },
        { t: 'mc', p: 'Para $f(z)=\\dfrac{z}{z^{2}+1}$, el denominador real que queda es',
          o: ['$(x^{2}-y^{2}+1)^{2}+4x^{2}y^{2}$', '$(x^{2}-y^{2}+1)^{2}-4x^{2}y^{2}$', '$x^{2}+y^{2}+1$', '$(x^{2}+y^{2}+1)^{2}$'], r: 0,
          x: 'Es $(a+bi)(a-bi)=a^{2}+b^{2}$ con $a=x^{2}-y^{2}+1$ y $b=2xy$. Y $(2xy)^{2}=4x^{2}y^{2}$.' },
        { t: 'mc', p: '¿Cuál es el dominio de $f(z)=z^{2}-4z$?',
          o: ['Todos los complejos', 'Todos salvo $z=0$', 'Todos salvo $z=4$', 'Todos salvo $z=\\pm 2$'], r: 0,
          x: 'Es un polinomio: no hay divisiones ni raíces, así que está definida en todo $\\mathbb{C}$.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u8l5',
      titulo: 'Límites',
      objetivo: 'Calcular límites complejos y probar cuándo no existen.',
      teoria: [
        { def: ['Límite', 'Decimos que $\\lim_{z\\to z_0}f(z)=L$ si los valores de $f(z)$ se acercan arbitrariamente a $L$ cuando $z$ se acerca a $z_0$.'] },
        { ojo: 'Acá está la diferencia grande con Análisis I. En la recta real uno se puede acercar sólo por izquierda o por derecha. En el plano complejo se puede llegar a $z_0$ por **infinitas direcciones**, y el límite tiene que dar lo mismo por todas.' },
        { h: 'Límites radiales' },
        { p: 'Ese requisito da una herramienta muy práctica para **demostrar que un límite no existe**: alcanza con encontrar dos caminos que den resultados distintos.' },
        { num: ['Me acerco por el **eje $x$**: hago $y=0$ y calculo', 'Me acerco por el **eje $y$**: hago $x=0$ y calculo', 'Si los dos valores son distintos, el límite **no existe**'] },
        { ej: ['Calcular $\\lim_{z\\to 0}\\dfrac{\\mathrm{Re}(z)}{z}$  — el ejemplo de la clase del 10/09', [
          'Escribo $z=x+iy$, así que $\\mathrm{Re}(z)=x$ y la función es $\\dfrac{x}{x+iy}$',
          '**Por el eje $x$** (hago $y=0$): $\;\\lim_{x\\to 0}\\dfrac{x}{x+0i}=\\lim_{x\\to 0}\\dfrac{x}{x}=1$',
          '**Por el eje $y$** (hago $x=0$): $\;\\lim_{y\\to 0}\\dfrac{0}{0+iy}=0$',
          'Dan distinto ($1\\neq 0$), así que **el límite no existe**',
        ]] },
        { truco: 'Si el enunciado dice "demostrar que no existe el límite", el camino es siempre este: dos direcciones, dos resultados distintos, listo.' },
        { p: 'Y no hay sólo dos caminos. En el pizarrón la profe anotó la lista completa de trayectorias que conviene probar:' },
        { lista: [
          'El **eje $x$**: hacer $y=0$',
          'El **eje $y$**: hacer $x=0$',
          'Una **recta** cualquiera: $y=mx$',
          'La recta $y=x$',
          'La **parábola** $y=x^{2}$',
          'Una vertical: $x=1$',
        ] },
        { ej: ['Probar que no existe $\lim_{z\to 1}\dfrac{x+y-1}{z-1}$  — del pizarrón', [
          'Escribo $z-1=(x-1)+iy$',
          '**Por el eje $x$** ($y=0$): $\;\dfrac{x-1}{x-1}=1$',
          '**Por la vertical $x=1$**: $\;\dfrac{1+y-1}{0+iy}=\dfrac{y}{iy}=\dfrac{1}{i}$',
          'Racionalizo: $\;\dfrac{1}{i}\cdot\dfrac{-i}{-i}=\dfrac{-i}{-i^{2}}=\dfrac{-i}{1}=-i$',
          'Dan distinto ($1\neq -i$): **no existe el límite**',
        ]] },
        { truco: 'Acordate de $\dfrac{1}{i}=-i$. Sale multiplicando arriba y abajo por $-i$, y aparece seguido en estos ejercicios.' },
        { h: 'Límites que sí existen' },
        { p: 'Si la función es continua en $z_0$ (por ejemplo un polinomio), el límite se calcula **reemplazando directamente**.' },
        { ej: ['$\\lim_{z\\to i}\\left(4z^{3}-5z^{2}+4z+1-5i\\right)$', [
          'Es un polinomio, así que reemplazo $z=i$:',
          '$\;4i^{3}-5i^{2}+4i+1-5i$',
          'Uso $i^{3}=-i$ e $i^{2}=-1$: $\;-4i+5+4i+1-5i$',
          'Agrupo: $\;(5+1)+(-4+4-5)i=6-5i$',
        ]] },
        { h: 'Regla de L\'Hôpital' },
        { p: 'Vale igual que en los reales, y sirve para las mismas indeterminaciones:' },
        { mat: '\\lim_{z\\to z_0}\\frac{f(z)}{g(z)}=\\lim_{z\\to z_0}\\frac{f\'(z)}{g\'(z)}' },
        { p: 'Se aplica a las indeterminaciones $\\dfrac{0}{0}$, $\\dfrac{\\infty}{\\infty}$, $0\\cdot\\infty$, $\\infty-\\infty$, $0^{0}$, $\\infty^{0}$ y $1^{\\infty}$.' },
        { ej: ['$\\lim_{z\\to 0}\\dfrac{z-\\sen z}{z^{3}}$', [
          'Reemplazando da $\\dfrac{0}{0}$: indeterminado, aplico L\'Hôpital',
          'Derivo arriba y abajo: $\;\\lim_{z\\to 0}\\dfrac{1-\\cos z}{3z^{2}}$',
          'Sigue dando $\\dfrac{0}{0}$: derivo otra vez: $\;\\lim_{z\\to 0}\\dfrac{\\sen z}{6z}$',
          'Y otra vez: $\;\\lim_{z\\to 0}\\dfrac{\\cos z}{6}=\\dfrac{1}{6}$',
        ]] },
        { ojo: 'L\'Hôpital se aplica **sólo** si hay indeterminación. Derivar arriba y abajo cuando el límite ya se puede calcular directo da un resultado equivocado.' },
      ],
      formulas: [
        ['Límites radiales', 'y=0 \\text{ (eje x)} \\quad\\text{y}\\quad x=0 \\text{ (eje y)}'],
        ['No existe si', 'L_{\\text{eje }x} \\neq L_{\\text{eje }y}'],
        ['L\'Hôpital', '\\lim\\frac{f(z)}{g(z)}=\\lim\\frac{f\'(z)}{g\'(z)}'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Cuál es la diferencia entre un límite real y uno complejo?',
          o: ['En el plano se puede llegar al punto por infinitas direcciones', 'En el plano no existen los límites', 'En el plano hay que derivar primero', 'No hay diferencia'], r: 0,
          x: 'Y el límite tiene que dar lo mismo por todas. Por eso alcanza con dos caminos distintos para probar que no existe.' },
        { t: 'mc', p: 'Para acercarse por el eje $x$, ¿qué se hace?',
          o: ['Se toma $y=0$', 'Se toma $x=0$', 'Se toma $z=0$', 'Se deriva'], r: 0,
          x: 'El eje $x$ es donde la parte imaginaria vale cero.' },
        { t: 'in', p: 'En $\\lim_{z\\to 0}\\dfrac{\\mathrm{Re}(z)}{z}$, acercándose por el eje $x$ el límite da', r: ['1'], ph: 'Un número',
          x: 'Con $y=0$ queda $\\frac{x}{x}=1$ para todo $x\\neq 0$.' },
        { t: 'in', p: '¿Y acercándose por el eje $y$?', r: ['0'], ph: 'Un número',
          x: 'Con $x=0$, el numerador $\\mathrm{Re}(z)=0$ y el cociente es $\\frac{0}{iy}=0$.' },
        { t: 'mc', p: 'Entonces $\\lim_{z\\to 0}\\dfrac{\\mathrm{Re}(z)}{z}$',
          o: ['No existe', 'Vale 1', 'Vale 0', 'Vale $\\frac{1}{2}$'], r: 0,
          x: 'Dos caminos, dos resultados distintos. Con eso alcanza para concluir que no existe.' },
        { t: 'mc', p: '$\\lim_{z\\to i}\\left(4z^{3}-5z^{2}+4z+1-5i\\right)$ es igual a',
          o: ['$6-5i$', '$6+5i$', '$-6-5i$', '$0$'], r: 0,
          x: 'Reemplazando: $4(-i)-5(-1)+4i+1-5i=-4i+5+4i+1-5i=6-5i$.' },
        { t: 'mc', p: '¿Cuándo se puede aplicar L\'Hôpital?',
          o: ['Sólo si hay una indeterminación', 'Siempre', 'Sólo con polinomios', 'Sólo si el límite existe'], r: 0,
          x: 'Si no hay indeterminación, derivar arriba y abajo cambia el resultado y da mal.' },
        { t: 'mc', p: '$\\lim_{z\\to 0}\\dfrac{z-\\sen z}{z^{3}}$ es igual a',
          o: ['$\\dfrac{1}{6}$', '$0$', '$1$', '$\\dfrac{1}{3}$'], r: 0,
          x: 'Hay que aplicar L\'Hôpital tres veces hasta llegar a $\\frac{\\cos z}{6}$, que en $z=0$ da $\\frac{1}{6}$.' },
        { t: 'mc', p: '¿Cuál de estas NO es una indeterminación?', fijo: true,
          o: ['$\\dfrac{1}{0}$', '$\\dfrac{0}{0}$', '$\\dfrac{\\infty}{\\infty}$', '$1^{\\infty}$'], r: 0,
          x: '$\\frac{1}{0}$ tiende a infinito: no es indeterminado, está determinado. Las otras tres sí lo son.' },
        { t: 'mc', p: 'Además de los ejes, ¿qué otras trayectorias conviene probar?',
          o: ['Rectas $y=mx$, la parábola $y=x^{2}$, verticales como $x=1$', 'Sólo los ejes', 'Sólo circunferencias', 'Ninguna, con los ejes alcanza siempre'], r: 0,
          x: 'Es la lista del pizarrón. Si por los ejes da igual, todavía no probaste nada: hay que buscar otro camino.' },
        { t: 'in', p: '¿Cuánto vale $\\dfrac{1}{i}$?', r: ['-i', '-1i'], ph: 'Por ejemplo: -i', teclas: ['-', 'i'],
          x: 'Multiplicás arriba y abajo por $-i$: $\\frac{-i}{-i^{2}}=\\frac{-i}{1}=-i$.' },
        { t: 'ord', p: 'Ordená el método para probar que un límite no existe',
          o: ['Escribir $z=x+iy$ en la función', 'Calcular el límite por el eje $x$ (con $y=0$)', 'Calcular el límite por el eje $y$ (con $x=0$)', 'Comparar: si dan distinto, el límite no existe'],
          x: 'Si dieran iguales, no probaste nada: podría existir o no. Para probar que **sí** existe hace falta otro argumento.' },
      ],
    },
    /* ------------------------------------------------------------------ */
    {
      id: 'u8l6',
      titulo: 'Forma exponencial y logaritmo',
      objetivo: 'Usar la fórmula de Euler y entender por qué el logaritmo complejo tiene infinitos valores.',
      teoria: [
        { p: 'Hay una tercera forma de escribir un complejo, más compacta que la trigonométrica y la que se usa en ingeniería para señales.' },
        { def: ['Fórmula de Euler', '$$e^{i\\varphi}=\\cos\\varphi+i\\,\\sen\\varphi$$'] },
        { p: 'Como la forma trigonométrica era $z=\\rho\\left[\\cos\\varphi+i\\sen\\varphi\\right]$, el paréntesis entero **es** $e^{i\\varphi}$. Entonces:' },
        { mat: 'z=\\rho\\,e^{i\\varphi}' },
        { truco: 'En forma exponencial, multiplicar complejos es trivial: se multiplican los módulos y se suman los argumentos, igual que con cualquier potencia. $\\rho_1e^{i\\varphi_1}\\cdot\\rho_2e^{i\\varphi_2}=\\rho_1\\rho_2\\,e^{i(\\varphi_1+\\varphi_2)}$.' },
        { ej: ['Escribir $z=-4+4i$ en forma exponencial', [
          'Ya calculamos $\\rho=4\\sqrt{2}$ y $\\varphi=\\dfrac{3\\pi}{4}$',
          'Entonces $\;z=4\\sqrt{2}\\,e^{i\\frac{3\\pi}{4}}$',
        ]] },
        { p: 'De Moivre sale sola desde acá: elevar $\\left(\\rho e^{i\\varphi}\\right)^{n}$ da $\\rho^{n}e^{in\\varphi}$, que es exactamente $\\rho^{n}\\left[\\cos(n\\varphi)+i\\sen(n\\varphi)\\right]$.' },
        { h: 'El logaritmo de un complejo' },
        { p: 'Acá pasa algo que no tiene análogo en los reales. Como el argumento de un complejo se puede aumentar en vueltas enteras sin cambiar el punto, el logaritmo tiene **infinitos valores**.' },
        { def: ['Logaritmo natural complejo', '$$\\mathrm{Ln}\\,z=\\ln\\rho+i\\left(\\varphi+2k\\pi\\right) \\qquad k\\in\\mathbb{Z}$$'] },
        { p: 'La parte real es el logaritmo del módulo (un número real común) y la parte imaginaria es el argumento, más todas las vueltas que quieras dar.' },
        { def: ['Valor principal', 'El que sale con $k=0$: $\;\\mathrm{Ln}\\,z=\\ln\\rho+i\\varphi$. Es el que se usa salvo que el ejercicio pida todos.'] },
        { ej: ['Calcular $\\mathrm{Ln}(i)$', [
          'Módulo: $\;\\rho=|i|=1$. Argumento: el punto $(0,1)$ está sobre el eje imaginario positivo, así que $\\varphi=\\dfrac{\\pi}{2}$',
          '$\;\\mathrm{Ln}(i)=\\ln 1+i\\left(\\dfrac{\\pi}{2}+2k\\pi\\right)$',
          'Y como $\\ln 1=0$: $\;\\mathrm{Ln}(i)=i\\left(\\dfrac{\\pi}{2}+2k\\pi\\right)$',
          'Valor principal ($k=0$): $\;\\dfrac{\\pi}{2}i$',
        ]] },
        { ojo: 'En los reales no existe el logaritmo de un negativo. En los complejos sí: $\\mathrm{Ln}(-1)=\\ln 1+i\\pi=i\\pi$, porque $-1$ tiene módulo $1$ y argumento $\\pi$.' },
        { h: 'Las tres formas, una al lado de la otra' },
        { tabla: [['Forma', 'Escritura', 'Para qué sirve'], [
          ['Binómica', '$z=a+bi$', 'Sumar y restar'],
          ['Trigonométrica', '$z=\\rho\\left[\\cos\\varphi+i\\sen\\varphi\\right]$', 'Potencias y raíces'],
          ['Exponencial', '$z=\\rho\\,e^{i\\varphi}$', 'Productos, cocientes y logaritmos'],
        ]] },
      ],
      formulas: [
        ['Euler', 'e^{i\\varphi}=\\cos\\varphi+i\\,\\sen\\varphi'],
        ['Forma exponencial', 'z=\\rho\\,e^{i\\varphi}'],
        ['Logaritmo', '\\mathrm{Ln}\\,z=\\ln\\rho+i(\\varphi+2k\\pi), \; k\\in\\mathbb{Z}'],
        ['Argumento desde el módulo', '\\cos\\varphi=\\frac{a}{\\rho} \\qquad \\sen\\varphi=\\frac{b}{\\rho}'],
        ['Producto', '\\rho_1e^{i\\varphi_1}\\cdot\\rho_2e^{i\\varphi_2}=\\rho_1\\rho_2\\,e^{i(\\varphi_1+\\varphi_2)}'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Qué dice la fórmula de Euler?',
          o: ['$e^{i\\varphi}=\\cos\\varphi+i\\,\\sen\\varphi$', '$e^{i\\varphi}=\\sen\\varphi+i\\cos\\varphi$', '$e^{\\varphi}=\\cos\\varphi+i\\sen\\varphi$', '$e^{i\\varphi}=\\cos\\varphi-i\\,\\sen\\varphi$'], r: 0,
          x: 'El coseno va en la parte real y el seno en la imaginaria. Es lo que conecta la exponencial con la trigonometría.' },
        { t: 'mc', p: 'La forma exponencial de un complejo es',
          o: ['$z=\\rho\\,e^{i\\varphi}$', '$z=e^{\\rho\\varphi}$', '$z=\\rho+e^{i\\varphi}$', '$z=\\rho^{i\\varphi}$'], r: 0,
          x: 'El módulo multiplica y el argumento va en el exponente, junto con la $i$.' },
        { t: 'mc', p: '$z=-4+4i$ en forma exponencial es',
          o: ['$4\\sqrt{2}\\,e^{i\\frac{3\\pi}{4}}$', '$4\\sqrt{2}\\,e^{i\\frac{\\pi}{4}}$', '$8\\,e^{i\\frac{3\\pi}{4}}$', '$4\\sqrt{2}\\,e^{-i\\frac{\\pi}{4}}$'], r: 0,
          x: 'Mismo módulo y argumento que en trigonométrica: $\\rho=4\\sqrt{2}$ y $\\varphi=\\frac{3\\pi}{4}$ por estar en el segundo cuadrante.' },
        { t: 'mc', p: 'En forma exponencial, multiplicar dos complejos significa',
          o: ['Multiplicar los módulos y sumar los argumentos', 'Sumar los módulos y multiplicar los argumentos', 'Multiplicar módulos y argumentos', 'Sumar todo'], r: 0,
          x: 'Es la regla de las potencias de igual base: $e^{m}\\cdot e^{n}=e^{m+n}$. Por eso los argumentos se suman.' },
        { t: 'mc', p: '¿Por qué el logaritmo de un complejo tiene infinitos valores?',
          o: ['Porque al argumento se le puede sumar cualquier cantidad de vueltas $2k\\pi$', 'Porque el módulo puede ser negativo', 'Porque $i^{2}=-1$', 'Porque el logaritmo no existe en $\\mathbb{C}$'], r: 0,
          x: 'Girar una vuelta completa te deja en el mismo punto, pero cambia el argumento. Todos esos argumentos son válidos, así que hay un logaritmo por cada $k$.' },
        { t: 'mc', p: '$\\mathrm{Ln}\\,z$ es igual a',
          o: ['$\\ln\\rho+i(\\varphi+2k\\pi)$', '$\\ln\\rho\\cdot i\\varphi$', '$\\ln(\\rho+\\varphi)$', '$\\rho+i\\varphi$'], r: 0,
          x: 'Parte real: el logaritmo del módulo. Parte imaginaria: el argumento más las vueltas.' },
        { t: 'mc', p: 'El valor principal de $\\mathrm{Ln}(i)$ es',
          o: ['$\\dfrac{\\pi}{2}i$', '$0$', '$i$', '$\\ln\\dfrac{\\pi}{2}$'], r: 0,
          x: '$|i|=1$ así que $\\ln 1=0$; el argumento es $\\frac{\\pi}{2}$. Con $k=0$ queda $\\frac{\\pi}{2}i$.' },
        { t: 'in', p: '¿Cuál es el módulo de $i$?', r: ['1'], ph: 'Un número',
          x: '$i=0+1i$, así que $|i|=\\sqrt{0^{2}+1^{2}}=1$.' },
        { t: 'vf', p: 'En los complejos existe el logaritmo de un número negativo.', r: true,
          x: 'Sí: $\\mathrm{Ln}(-1)=\\ln 1+i\\pi=i\\pi$, porque $-1$ tiene módulo $1$ y argumento $\\pi$. En los reales no existe.' },
        { t: 'par', p: 'Emparejá cada forma con para qué conviene',
          o: [['$a+bi$', 'Sumar y restar'], ['$\\rho\\left[\\cos\\varphi+i\\sen\\varphi\\right]$', 'Potencias y raíces'], ['$\\rho\\,e^{i\\varphi}$', 'Productos y logaritmos']],
          x: 'Cada forma hace fácil una operación distinta. Elegir la forma correcta antes de arrancar ahorra media carilla.' },
      ],
    },
    /* ------------------------------------------------------------------ */
    {
      id: 'u8l7',
      titulo: 'Continuidad y derivada',
      objetivo: 'Analizar continuidad (incluso a trozos) y derivar funciones complejas.',
      teoria: [
        { h: 'Continuidad' },
        { def: ['Continua en un punto', '$f$ es continua en $z_0$ si $$\lim_{z\to z_0}f(z)=f(z_0)$$ es decir: **el límite tiene que coincidir con la imagen**.'] },
        { lista: [
          'Una función **polinómica** es continua en todo el plano.',
          'Una función **racional** es continua salvo donde el denominador se anula.',
        ] },
        { ej: ['¿Dónde es continua $f(z)=\dfrac{z-1}{z^{2}-(2-i)z-2i}$?', [
          'Busco los ceros del denominador con la resolvente: $a=1$, $b=-(2-i)$, $c=-2i$',
          'Sale $\;z=2\;$ y $\;z=-i$',
          'Verifico factorizando: $\;(z-2)(z+i)=z^{2}+iz-2z-2i=z^{2}-(2-i)z-2i$ ✓',
          'Es continua en $\;\mathbb{C}-\{2,\,-i\}$',
        ]] },
        { h: 'Funciones a trozos' },
        { p: 'Cuando la función está definida por partes, hay que comparar **el límite con la imagen**. Es el ejercicio que la profe dejó de tarea.' },
        { ej: ['Analizar la continuidad en $z=2$ de $f(z)=\begin{cases} \dfrac{z^{2}-z-2}{z-2} & z\neq 2 \\[4pt] -\dfrac{3}{2}z & z=2 \end{cases}$', [
          '**Límite:** factorizo el numerador: $\;z^{2}-z-2=(z-2)(z+1)$',
          'Simplifico y evalúo: $\;\lim_{z\to 2}(z+1)=3$',
          '**Imagen:** $\;f(2)=-\dfrac{3}{2}\cdot 2=-3$',
          'Comparo: $\;3\neq -3$',
          'La función es **discontinua** en $z=2$',
        ]] },
        { truco: 'Siempre los mismos dos pasos: calculás el límite (factorizando y simplificando si da $\frac{0}{0}$) y calculás la imagen. Si coinciden es continua; si no, no.' },
        { h: 'Derivada' },
        { def: ['Derivada compleja', '$$f\'(z_0)=\lim_{z\to z_0}\frac{f(z)-f(z_0)}{z-z_0}$$ si ese límite existe. Si $f$ es derivable en $z_0$, entonces es continua en $z_0$.'] },
        { truco: 'La buena noticia: **se usan las mismas reglas de derivación que para números reales**. Potencia, producto, cociente, cadena. La $i$ se trata como una constante.' },
        { ej: ['Derivar $f(z)=3z^{4}-5z^{3}+2z$', [
          'Regla de la potencia, término a término:',
          '$\;f\'(z)=12z^{3}-15z^{2}+2$',
        ]] },
        { ej: ['Derivar $y=\sen(5z)\cdot\cos(z)$  — del pizarrón', [
          'Es un producto: $\;(f\cdot g)\'=f\'g+fg\'$',
          '$\;f=\sen(5z) \Rightarrow f\'=5\cos(5z)$',
          '$\;g=\cos(z) \Rightarrow g\'=-\sen(z)$',
          '$\;y\'=5\cos(5z)\cos(z)+\sen(5z)\cdot\left[-\sen(z)\right]$',
        ]] },
        { h: 'Funciones analíticas' },
        { def: ['Analítica en un punto', '$f$ es analítica en $z_0$ si es derivable en $z_0$ **y en todo punto de una vecindad** de $z_0$.'] },
        { ojo: 'Analítica **no** es lo mismo que derivable. Derivable pide un solo punto; analítica pide todo un entorno alrededor.' },
        { p: 'Los **polinomios son derivables en todo** $\mathbb{C}$: por eso se llaman funciones **enteras**. Una racional deja de ser analítica en los ceros del denominador.' },
        { ej: ['¿Dónde no es analítica $f(z)=\dfrac{z-4+3i}{z^{2}-6z+25}$?', [
          'Igualo el denominador a cero: $\;z^{2}-6z+25=0$',
          '$\;z=\dfrac{6\pm\sqrt{36-100}}{2}=\dfrac{6\pm\sqrt{-64}}{2}=\dfrac{6\pm 8i}{2}=3\pm 4i$',
          'No es analítica en $\;3+4i\;$ ni en $\;3-4i$',
        ]] },
      ],
      formulas: [
        ['Continuidad', '\lim_{z\to z_0}f(z)=f(z_0)'],
        ['Derivada', 'f\'(z_0)=\lim_{z\to z_0}\frac{f(z)-f(z_0)}{z-z_0}'],
        ['Reglas', '\text{las mismas que en variable real}'],
        ['Producto', '(f\cdot g)\'=f\'g+f\,g\''],
        ['No analítica en', '\text{los ceros del denominador}'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Cuándo es continua $f$ en $z_0$?',
          o: ['Cuando el límite coincide con la imagen', 'Cuando existe el límite', 'Cuando existe la imagen', 'Cuando es derivable'], r: 0,
          x: 'Hacen falta las dos cosas y que además sean iguales: $\\lim_{z\\to z_0}f(z)=f(z_0)$.' },
        { t: 'mc', p: 'Factorizá el numerador de $\\dfrac{z^{2}-z-2}{z-2}$',
          o: ['$(z-2)(z+1)$', '$(z-2)(z-1)$', '$(z+2)(z-1)$', '$(z-2)^{2}$'], r: 0,
          x: 'Buscás dos números que multiplicados den $-2$ y sumados $-1$: son $-2$ y $1$.' },
        { t: 'in', p: 'Entonces $\\lim_{z\\to 2}\\dfrac{z^{2}-z-2}{z-2}$ vale', r: ['3'], ph: 'Un número',
          x: 'Simplificás el $(z-2)$ y queda $\\lim_{z\\to 2}(z+1)=3$.' },
        { t: 'in', p: 'Si en $z=2$ la función vale $f(2)=-\\dfrac{3}{2}z$, ¿cuánto da $f(2)$?', r: ['-3'], ph: 'Puede ser negativo', teclas: ['-'],
          x: '$-\\frac{3}{2}\\cdot 2=-3$.' },
        { t: 'vf', p: 'Con límite $3$ e imagen $-3$, la función es continua en $z=2$.', r: false,
          x: 'No coinciden, así que es **discontinua**. Ese es justo el punto del ejercicio.' },
        { t: 'mc', p: 'Las reglas para derivar una función compleja son',
          o: ['Las mismas que en variable real', 'Distintas: hay que usar Cauchy-Riemann', 'Sólo vale la regla de la potencia', 'Hay que separar en $u$ y $v$ primero'], r: 0,
          x: 'Potencia, producto, cociente y cadena funcionan igual. La $i$ es una constante más.' },
        { t: 'mc', p: 'Derivá $f(z)=3z^{4}-5z^{3}+2z$',
          o: ['$12z^{3}-15z^{2}+2$', '$12z^{3}-15z^{2}+2z$', '$3z^{3}-5z^{2}+2$', '$12z^{4}-15z^{3}+2$'], r: 0,
          x: 'Término a término. El $2z$ deriva en $2$, sin $z$.' },
        { t: 'mc', p: 'Derivá $f(z)=4z^{3}-(3+i)z^{2}-5z+4$  (Práctica 7)',
          o: ['$12z^{2}-2(3+i)z-5$', '$12z^{2}-(3+i)z-5$', '$12z^{2}-2(3+i)z-5+4$', '$12z^{2}-2(3+i)z$'], r: 0,
          x: 'El $(3+i)$ es constante: baja el $2$ del exponente. El $+4$ deriva en cero.' },
        { t: 'mc', p: 'Derivá $y=\\sen(5z)\\cos(z)$',
          o: ['$5\\cos(5z)\\cos(z)-\\sen(5z)\\sen(z)$', '$5\\cos(5z)\\sen(z)$', '$-5\\cos(5z)\\sen(z)$', '$\\cos(5z)\\cos(z)$'], r: 0,
          x: 'Producto: $f\'g+fg\'$, con $f\'=5\\cos(5z)$ y $g\'=-\\sen(z)$.' },
        { t: 'vf', p: 'Ser derivable en un punto alcanza para ser analítica ahí.', r: false,
          x: 'No: analítica pide ser derivable en **todo un entorno** del punto, no sólo en el punto.' },
        { t: 'mc', p: '¿Por qué los polinomios son funciones enteras?',
          o: ['Porque son derivables en todo punto del plano', 'Porque no tienen denominador', 'Porque tienen coeficientes enteros', 'Porque son continuos'], r: 0,
          x: 'Entera = analítica en todo $\\mathbb{C}$, y un polinomio es derivable en cualquier punto.' },
        { t: 'hue', p: 'Para $f(z)=\\dfrac{z-4+3i}{z^{2}-6z+25}$, no es analítica en $a\\pm bi$:',
          tpl: '$a=$ ___ y $b=$ ___', r: [['3'], ['4']],
          x: 'Resolvente: $z=\\frac{6\\pm\\sqrt{-64}}{2}=\\frac{6\\pm 8i}{2}=3\\pm 4i$.' },
      ],
    },

    /* ------------------------------------------------------------------ */
    {
      id: 'u8l8',
      titulo: 'Cauchy-Riemann',
      objetivo: 'Probar si una función es analítica usando derivadas parciales.',
      teoria: [
        { p: 'Hay una prueba concreta para decidir si una función compleja es analítica, y usa **derivadas parciales** de su parte real e imaginaria.' },
        { def: ['Ecuaciones de Cauchy-Riemann', 'Si $f(z)=u(x,y)+i\,v(x,y)$ es derivable en $z=x+iy$, entonces $$u_x=v_y \qquad\text{y}\qquad u_y=-v_x$$'] },
        { ojo: 'Son **dos** ecuaciones y hay que verificar las dos. Cuidado con el signo menos: va en la segunda, sobre $v_x$.' },
        { num: [
          'Reemplazar $z=x+iy$ y desarrollar',
          'Separar $u(x,y)$ (lo real) y $v(x,y)$ (lo que multiplica a $i$)',
          'Calcular las cuatro parciales',
          'Verificar las dos ecuaciones y ver **para qué puntos** se cumplen',
        ] },
        { truco: 'Al derivar respecto de $x$, la $y$ queda constante, y al revés. En el pizarrón la profe lo anota al costado: "$y$ cte", "$x$ cte".' },
        { ej: ['¿Es analítica $f(z)=z^{2}+z$?  — el ejemplo (1) del pizarrón', [
          'Reemplazo: $\;(x+iy)^{2}+(x+iy)=x^{2}-y^{2}+2xyi+x+iy$',
          'Separo: $\;u=x^{2}-y^{2}+x\;$ y $\;v=2xy+y$',
          'Parciales: $\;u_x=2x+1$, $\;u_y=-2y$, $\;v_x=2y$, $\;v_y=2x+1$',
          'Primera: $\;u_x=2x+1=v_y$ ✓',
          'Segunda: $\;u_y=-2y=-v_x$ ✓',
          'Se cumplen para todo $x$ e $y$: **analítica en todo** $\mathbb{C}$',
        ]] },
        { ej: ['¿Es analítica $f(z)=z^{2}+4z-1$?', [
          'Separo: $\;u=x^{2}-y^{2}-1+4x\;$ y $\;v=2xy+4y$',
          'Parciales: $\;u_x=2x+4$, $\;u_y=-2y$, $\;v_x=2y$, $\;v_y=2x+4$',
          'Las dos ecuaciones se cumplen siempre: **analítica en todo** $\mathbb{C}$',
        ]] },
        { truco: 'Control rápido: si $f(z)$ es un **polinomio en $z$**, ya es entera y Cauchy-Riemann se va a cumplir. Los ejercicios que valen la pena son los que vienen ya separados en $u$ y $v$: ahí sí puede fallar.' },
        { h: 'Cuando NO es analítica' },
        { ej: ['$f(z)=(2x^{2}+y)+i(y^{2}-x)$  — el otro ejemplo del pizarrón', [
          'Ya viene separada: $\;u=2x^{2}+y\;$ y $\;v=y^{2}-x$',
          'Parciales: $\;u_x=4x$, $\;u_y=1$, $\;v_x=-1$, $\;v_y=2y$',
          'Segunda: $\;u_y=1$ y $-v_x=1$ ✓ (se cumple siempre)',
          'Primera: $\;4x=2y$, o sea $\;y=2x$',
          'Eso es sólo una **recta**. Conclusión: **no es analítica para todo** $z\in\mathbb{C}$',
        ]] },
        { ojo: 'Si Cauchy-Riemann se cumple únicamente sobre una recta o una curva, la respuesta es que no es analítica: una recta no contiene ninguna vecindad, y analítica pide todo un entorno.' },
      ],
      formulas: [
        ['Cauchy-Riemann', 'u_x=v_y \qquad u_y=-v_x'],
        ['Notación larga', '\frac{\partial u}{\partial x}=\frac{\partial v}{\partial y} \qquad \frac{\partial u}{\partial y}=-\frac{\partial v}{\partial x}'],
        ['Control', 'f \text{ polinomio en } z \;\Rightarrow\; \text{entera}'],
      ],
      ejercicios: [
        { t: 'mc', p: '¿Cuáles son las ecuaciones de Cauchy-Riemann?',
          o: ['$u_x=v_y$ y $u_y=-v_x$', '$u_x=v_x$ y $u_y=v_y$', '$u_x=-v_y$ y $u_y=v_x$', '$u_x+v_y=0$ y $u_y+v_x=0$'], r: 0,
          x: 'El signo menos va en la segunda, delante de $v_x$. Cambiarlo de lugar es el error más común.' },
        { t: 'hue', p: 'Para $f(z)=z^{2}+z$, separando parte real e imaginaria:',
          tpl: '$u=x^{2}-y^{2}+$ ___ y $v=2xy+$ ___', r: [['x'], ['y']],
          x: 'Desarrollando $(x+iy)^{2}+(x+iy)$: la parte real es $x^{2}-y^{2}+x$ y la imaginaria $2xy+y$.' },
        { t: 'mc', p: 'Con $u=x^{2}-y^{2}+x$, ¿cuánto vale $u_x$?',
          o: ['$2x+1$', '$2x$', '$-2y$', '$2x-2y+1$'], r: 0,
          x: 'Derivás respecto de $x$ con $y$ constante: el $-y^{2}$ desaparece.' },
        { t: 'mc', p: 'Con $v=2xy+y$, ¿cuánto vale $v_y$?',
          o: ['$2x+1$', '$2y$', '$2x$', '$2xy$'], r: 0,
          x: 'Respecto de $y$: $2xy$ da $2x$ y el $y$ da $1$. Coincide con $u_x$ ✓' },
        { t: 'vf', p: '$f(z)=z^{2}+z$ es analítica en todo el plano complejo.', r: true,
          x: 'Las dos ecuaciones se cumplen para cualquier $x$ e $y$. Además es polinomio: entera.' },
        { t: 'mc', p: '¿Es analítica $f(z)=z^{2}+4z-1$?',
          o: ['Sí, en todo $\\mathbb{C}$', 'Sólo sobre una recta', 'No, en ningún punto', 'Sólo en el origen'], r: 0,
          x: '$u_x=2x+4=v_y$ ✓ y $u_y=-2y=-v_x$ ✓. Es polinomio: entera.' },
        { t: 'mc', p: 'Si $f(z)$ es un polinomio en $z$, entonces',
          o: ['Es entera y cumple Cauchy-Riemann en todo el plano', 'Nunca cumple Cauchy-Riemann', 'Sólo es analítica en el origen', 'Hay que verificar caso por caso'], r: 0,
          x: 'Derivable en todo punto. Sirve como control antes de hacer las cuentas.' },
        { t: 'mc', p: 'Para $f(z)=(2x^{2}+y)+i(y^{2}-x)$, Cauchy-Riemann se cumple sólo si',
          o: ['$y=2x$', '$y=x$', '$x=0$', 'Siempre'], r: 0,
          x: 'De $u_x=v_y$: $4x=2y$, o sea $y=2x$. La otra se cumple siempre.' },
        { t: 'mc', p: 'Entonces, ¿esa función es analítica?',
          o: ['No, porque una recta no contiene ningún entorno', 'Sí, sobre la recta $y=2x$', 'Sí, en todo el plano', 'Sí, sólo en el origen'], r: 0,
          x: 'Cumplirse sobre una recta no alcanza. No es analítica para todo $z\\in\\mathbb{C}$.' },
        { t: 'mc', p: 'Al calcular $u_x$, ¿qué hacés con la $y$?',
          o: ['La trato como constante', 'La derivo también', 'La reemplazo por cero', 'La paso al otro miembro'], r: 0,
          x: 'Es derivada **parcial**: se deriva respecto de una variable y la otra queda fija.' },
      ],
    },
  ],
});
